// @generated by sylphx-gen 0.1.0 from contracts@3118f36f16f799965338811e17ed3a9f565a9f136b14c95e9c94a1e21d42ea3e. Do not edit.
// `sylphx.agents.v1`.

import * as runtime from './runtime.js'
import './common.js'
import type * as common from './common.js'
import './sandboxes.js'
import type * as sandboxes from './sandboxes.js'

/**
 * An Agent is a versioned agent definition: model, instructions, tools, MCP
 * servers, skills, memory stores, tool policy and budget. Each create or
 * update that changes `spec` mints a new immutable AgentVersion; a session
 * pins the version it started on, so a change never alters a running
 * conversation.
 */
export interface Agent {
	/** `orgs/{org}/projects/{project}/envs/{env}/agents/{agent}`. */
	name?: string
	/** `agt_<cell><ulid>`; never reused. */
	readonly uid?: string
	/** Resource metadata. */
	meta?: common.ResourceMeta
	/** Desired state: the definition the next version takes. */
	spec?: AgentSpec
	/** Observed state. */
	readonly status?: AgentStatus
}

/** AgentBudget caps what one turn and one session may spend. */
export interface AgentBudget {
	/** Model and tool steps per turn, 1 to 1000; default 100. */
	maxStepsPerTurn?: number
	/** One turn's wall-clock deadline, 10s to 24h; default 30m. */
	turnTimeout?: string
	/**
	 * Spend per session in micro-USD, models and tools together; 0 is the
	 * project's spend limit only.
	 */
	maxSessionSpendMicros?: string
}

/**
 * An AgentSession is a durable conversation with one pinned AgentVersion.
 * Its conversation is its SessionEvent log. Each turn runs as one Sylphx
 * Workflows Run, and each model call and tool call is a step keyed by
 * `(session, turn, step)`, assigned by the runtime and never taken from the
 * model's tool-call id. An idle session holds no Run and no compute.
 */
export interface AgentSession {
	/** `orgs/{org}/projects/{project}/envs/{env}/agent_sessions/{agent_session}`. */
	name?: string
	/** `ases_<cell><ulid>`; never reused. */
	readonly uid?: string
	/** Resource metadata. */
	meta?: common.ResourceMeta
	/** The Agent the session talks to. */
	agent?: string
	/**
	 * The AgentVersion the session pinned; the Agent's current version when
	 * unset at create.
	 */
	agentVersion?: string
	/**
	 * The Sylphx Auth end user the session belongs to, set from the caller's
	 * end-user session; empty for a session a secret key started. An end user
	 * reads and changes only their own sessions.
	 */
	readonly endUser?: string
	/** A short title; set by the caller or summarised by the runtime. */
	title?: string
	/** The session's state. */
	readonly state?: SessionState
	/** The number of turns started, from 0. */
	readonly turnCount?: string
	/** The sequence of the newest event, from 0. */
	readonly lastEventSequence?: string
	/** When the session was created. */
	readonly createTime?: string
	/** When the last event was appended. */
	readonly updateTime?: string
	/** What the session has used so far. */
	readonly usage?: SessionUsage
	/** The Sylphx Sandboxes lease attached to the session, while it has one. */
	readonly environmentLease?: string
	/**
	 * The environment for this session; when omitted, use the pinned Agent
	 * version's default. An explicit value replaces that default.
	 */
	environment?: EnvironmentSpec
	/**
	 * Session-scoped credential bindings, keyed by the tool or MCP credential
	 * name. Values are references or opaque handles, never secret values.
	 */
	credentials?: Record<string, CredentialBinding>
	/**
	 * Granted platform Profiles to mount when the session starts, each by
	 * resource name and mode. The runtime never puts profile values in events.
	 */
	profiles?: ProfileMount[]
}

/**
 * AgentSpec is the caller-writable definition of an Agent. An AgentVersion
 * holds a frozen copy of it.
 */
export interface AgentSpec {
	/**
	 * The exact Sylphx AI catalog id (`ai_models`), set per Agent through the
	 * API as runtime state, never code or a deployed file. Agents in the same
	 * environment may use different models; the harness never remaps this id.
	 */
	model?: string
	/** The system instructions, at most 256 KiB. */
	instructions?: string
	/** The tools the agent may call, at most 128, each `name` once. */
	tools?: Tool[]
	/** The MCP servers whose tools the agent may call, at most 32. */
	mcpServers?: McpServer[]
	/** Skills: instruction packs the agent loads when relevant, at most 64. */
	skills?: Skill[]
	/**
	 * The memory stores the agent recalls from and writes to, as MemoryStore
	 * names; at most 8.
	 */
	memoryStores?: string[]
	/** The policy every tool call passes before it runs. */
	toolPolicy?: ToolPolicy
	/** Spend and time limits per turn and per session. */
	budget?: AgentBudget
	/**
	 * Whether end-user session access is intended for this agent. Reserved
	 * until the backend enforces end-user ownership; all contract methods
	 * currently require a secret key.
	 */
	endUserAccess?: boolean
	/**
	 * Whether sessions get a Sylphx Sandboxes environment (shell, files,
	 * browser, computer use), attached on first need and put in standby when
	 * idle.
	 */
	environment?: EnvironmentSpec
	/**
	 * The execution harness, independent of `model`: `runtime` (default),
	 * `claude_code` or `codex`. It is part of the immutable version, not an
	 * environment-wide setting. An omitted or empty value means `runtime`.
	 */
	harness?: string
}

/** AgentStatus is the observed state of an Agent. */
export interface AgentStatus {
	/** The generation this status was computed from. */
	readonly observedGeneration?: string
	/** Ready, Reconciling, Stalled. */
	readonly conditions?: common.Condition[]
	/** The newest version, which new sessions pin unless they name another. */
	readonly currentVersion?: string
	/** The number of the newest version, from 1. */
	readonly currentVersionNumber?: string
}

/**
 * An AgentVersion is one immutable snapshot of an Agent's definition. It is
 * written by the create or update that changed the Agent's spec, and never
 * changed after.
 */
export interface AgentVersion {
	/** `orgs/{org}/projects/{project}/envs/{env}/agents/{agent}/agent_versions/{agent_version}`. */
	name?: string
	/** `agv_<cell><ulid>`; never reused. */
	readonly uid?: string
	/** Resource metadata. */
	meta?: common.ResourceMeta
	/** The version number within the agent, from 1, with no gaps. */
	readonly versionNumber?: string
	/** The definition, frozen. */
	readonly spec?: AgentSpec
	/** The Agent generation that minted it. */
	readonly agentGeneration?: string
	/** When it was minted. */
	readonly createTime?: string
}

/** An Approval is a tool call the policy sent to a person, and its answer. */
export interface Approval {
	/** The ToolCall's `id`. */
	readonly callId?: string
	/** The answer, once given; unset while it waits. */
	readonly decision?: ApprovalDecision
	/**
	 * Whether the answer covers later calls of the same tool in this session
	 * ("always allow").
	 */
	readonly remember?: boolean
	/** Who answered. */
	readonly principal?: string
	/** The reason given, if any. */
	readonly reason?: string
}

/** A BuiltinTool is a tool the platform provides. */
export interface BuiltinTool {
	/** The built-in tool's id. */
	id?: string
	/** Tool-specific settings, at most 16 KiB of JSON. */
	config?: Record<string, unknown>
}

/**
 * A ClientTool is a tool the client runs: the session waits for its result
 * in state `AWAITING_CLIENT`.
 */
export interface ClientTool {
	/**
	 * How long the session waits for the result before the call fails, 1s to
	 * 24h; default 10m.
	 */
	timeout?: string
}

/** A ContentPart is one piece of a message. */
export interface ContentPart {
	/** Text. */
	text?: string
	/** A file, by Sylphx Data object URL or an https URL. */
	file?: FileRef
}

/** The request of CreateAgent. */
export interface CreateAgentRequest {
	/** The parent to create in. */
	parent: string
	/**
	 * The agent id, the final name segment; the server assigns one when
	 * empty.
	 */
	agentId?: string
	/** The agent to create; only caller-writable fields are read. */
	agent: Agent
	/** Validate and return the result without writing anything. */
	validateOnly?: boolean
}

/** The request of CreateAgentSession. */
export interface CreateAgentSessionRequest {
	/** The parent to create in. */
	parent: string
	/**
	 * The session id, the final name segment; the server assigns one when
	 * empty.
	 */
	agentSessionId?: string
	/** The session to create; only caller-writable fields are read. */
	agentSession: AgentSession
	/** Validate and return the result without writing anything. */
	validateOnly?: boolean
}

/** The request of CreateMemory. */
export interface CreateMemoryRequest {
	/** The memory store to create in. */
	parent: string
	/**
	 * The memory id, the final name segment; the server assigns one when
	 * empty.
	 */
	memoryId?: string
	/** The memory to create; only caller-writable fields are read. */
	memory: Memory
	/** Validate and return the result without writing anything. */
	validateOnly?: boolean
}

/** The request of CreateMemoryStore. */
export interface CreateMemoryStoreRequest {
	/** The parent to create in. */
	parent: string
	/**
	 * The memory store id, the final name segment; the server assigns one when
	 * empty.
	 */
	memoryStoreId?: string
	/** The memory store to create; only caller-writable fields are read. */
	memoryStore: MemoryStore
	/** Validate and return the result without writing anything. */
	validateOnly?: boolean
}

/**
 * A CredentialBinding names where the gateway takes a credential from. The
 * value is resolved at egress only; the model, the event log and traces see
 * the binding, never the value.
 */
export interface CredentialBinding {
	/** A Kernel Secret of this environment, by name. */
	secret?: string
	/** A Kernel Connection (a third-party OAuth installation), by name. */
	connection?: string
	/**
	 * The end user's own grant in Sylphx Auth's agent token vault, by
	 * provider id; the session's end user must hold it.
	 */
	endUserProvider?: string
	/**
	 * How the value is sent: `bearer` (default), `header:<Name>` or
	 * `query:<name>`.
	 */
	placement?: string
	/**
	 * An opaque credential handle issued for this session, resolved only at
	 * egress. This is never a credential value.
	 */
	handle?: string
}

/** The request of DecideAgentSessionApproval. */
export interface DecideAgentSessionApprovalRequest {
	/** The name of the session. */
	name: string
	/** The waiting ToolCall's `id`. */
	callId: string
	/** The answer. */
	decision: ApprovalDecision
	/**
	 * Also allow later calls of the same tool in this session without asking
	 * ("always allow"); only with APPROVE.
	 */
	remember?: boolean
	/** Why, at most 500 characters; the agent reads it with a rejection. */
	reason?: string
}

/** The request of DeleteAgent. */
export interface DeleteAgentRequest {
	/** The name of the agent to delete. */
	name: string
	/** Delete only if the current etag matches. */
	etag?: string
	/** Succeed when the agent does not exist. */
	allowMissing?: boolean
	/** Validate without deleting anything. */
	validateOnly?: boolean
	/**
	 * Also delete the agent's sessions; without it, an agent with sessions
	 * is refused with `INVALID_STATE`.
	 */
	force?: boolean
}

/** The request of DeleteAgentSession. */
export interface DeleteAgentSessionRequest {
	/** The name of the session to delete. */
	name: string
	/** Delete only if the current etag matches. */
	etag?: string
	/** Succeed when the session does not exist. */
	allowMissing?: boolean
	/** Validate without deleting anything. */
	validateOnly?: boolean
	/**
	 * Interrupt a running turn and delete; without it, a running session is
	 * refused with `INVALID_STATE`.
	 */
	force?: boolean
}

/** The request of DeleteMemory. */
export interface DeleteMemoryRequest {
	/** The name of the memory to delete. */
	name: string
	/** Delete only if the current etag matches. */
	etag?: string
	/** Succeed when the memory does not exist. */
	allowMissing?: boolean
	/** Validate without deleting anything. */
	validateOnly?: boolean
}

/** The request of DeleteMemoryStore. */
export interface DeleteMemoryStoreRequest {
	/** The name of the memory store to delete. */
	name: string
	/** Delete only if the current etag matches. */
	etag?: string
	/** Succeed when the memory store does not exist. */
	allowMissing?: boolean
	/** Validate without deleting anything. */
	validateOnly?: boolean
	/**
	 * Also delete the store's memories; without it, a store with memories is
	 * refused with `INVALID_STATE`.
	 */
	force?: boolean
}

/**
 * EnvironmentSpec requests a fresh Sandboxes lease for a session. An Agent's
 * version may provide a default; a session's explicit environment replaces it.
 */
export interface EnvironmentSpec {
	/** A Sylphx Sandboxes shape; empty gives sessions no environment. */
	shape?: string
	/**
	 * Put the environment in standby after this long idle, 1m to 24h; default
	 * 10m.
	 */
	idleStandby?: string
	/**
	 * The Sandboxes image: `template:<name>` or an artifact image by digest,
	 * passed unchanged to the lease's `image` field.
	 */
	template?: string
	/** The repository to prepare inside the fresh lease, if any. */
	repo?: RepositorySpec
	/** The lease's outbound policy, using the Sandboxes network contract. */
	egress?: sandboxes.LeaseNetwork
	/** The lease's CPU and cost ceiling, separate from model and tool spend. */
	budget?: sandboxes.LeaseBudget
	/**
	 * The lease's maximum wall time, passed to Sandboxes as `ttl`. The lease
	 * is released when the session ends even if this bound has not been reached.
	 */
	ttl?: string
}

/** ErrorEvent is a step or harness failure, without credential values. */
export interface ErrorEvent {
	/** The registry error code or harness error kind. */
	readonly kind?: string
	/** A safe error description. */
	readonly message?: string
}

/** FileChange is a file changed by a step's harness. */
export interface FileChange {
	/** The path relative to the session's repository root. */
	readonly path?: string
	/** `added`, `modified`, `deleted`, `renamed` or `copied`. */
	readonly change?: string
	/** Lines added, when reported by the harness. */
	readonly added?: string
	/** Lines removed, when reported by the harness. */
	readonly removed?: string
	/** The previous path, for a rename or copy. */
	readonly oldPath?: string
	/** `edit` for an incremental edit or `final` for the turn's final diff. */
	readonly source?: string
}

/** A FileRef names a file attached to a message. */
export interface FileRef {
	/** Where the file is. */
	uri?: string
	/** Its media type, for example `image/png`. */
	mediaType?: string
	/** Its display name. */
	filename?: string
}

/** A FunctionTool is a tool whose logic is the app's own server code. */
export interface FunctionTool {
	/**
	 * The HTTPS endpoint the gateway calls, a Hosting route or a verified
	 * Network Domain of this project.
	 */
	uri?: string
	/** One call's deadline, 1s to 15m; default 60s. */
	timeout?: string
}

/** The request of GetAgent. */
export interface GetAgentRequest {
	/** The name of the agent to get. */
	name: string
}

/** The request of GetAgentSession. */
export interface GetAgentSessionRequest {
	/** The name of the session to get. */
	name: string
}

/** The request of GetAgentVersion. */
export interface GetAgentVersionRequest {
	/** The name of the agent version to get. */
	name: string
}

/** The request of GetMemory. */
export interface GetMemoryRequest {
	/** The name of the memory to get. */
	name: string
}

/** The request of GetMemoryStore. */
export interface GetMemoryStoreRequest {
	/** The name of the memory store to get. */
	name: string
}

/** The request of GetSessionEvent. */
export interface GetSessionEventRequest {
	/** The name of the session event to get. */
	name: string
}

/** An HttpTool is an HTTP API the gateway calls on the agent's behalf. */
export interface HttpTool {
	/** An HTTPS URL of an OpenAPI 3 document. */
	openapiUri?: string
	/** An OpenAPI 3 document, at most 1 MiB of JSON. */
	openapi?: Record<string, unknown>
	/**
	 * The operation the tool calls; empty exposes every operation as its own
	 * tool named `<tool>_<operationId>`.
	 */
	operationId?: string
	/** The credential the gateway injects at egress; the model never sees it. */
	credential?: CredentialBinding
}

/** The request of InterruptAgentSession. */
export interface InterruptAgentSessionRequest {
	/** The name of the session. */
	name: string
	/** Why, recorded on the status event; at most 500 characters. */
	reason?: string
}

/** The request of ListAgentSessions. */
export interface ListAgentSessionsRequest {
	/** The parent to list in. */
	parent: string
	/** At most this many; default 50, clamped to 1000. */
	pageSize?: number
	/** `next_page_token` of the previous page. */
	pageToken?: string
	/** AIP-160 filter, limited to `agent`, `end_user` and `state`. */
	filter?: string
}

/** The response of ListAgentSessions. */
export interface ListAgentSessionsResponse {
	/** The page. */
	agentSessions?: AgentSession[]
	/** The token of the next page; empty on the last page. */
	nextPageToken?: string
}

/** The request of ListAgentVersions. */
export interface ListAgentVersionsRequest {
	/** The agent to list in. */
	parent: string
	/** At most this many; default 50, clamped to 1000. */
	pageSize?: number
	/** `next_page_token` of the previous page. */
	pageToken?: string
	/** AIP-160 filter, limited to `version_number`. */
	filter?: string
}

/** The response of ListAgentVersions. */
export interface ListAgentVersionsResponse {
	/** The page. */
	agentVersions?: AgentVersion[]
	/** The token of the next page; empty on the last page. */
	nextPageToken?: string
}

/** The request of ListAgents. */
export interface ListAgentsRequest {
	/** The parent to list in. */
	parent: string
	/** At most this many; default 50, clamped to 1000. */
	pageSize?: number
	/** `next_page_token` of the previous page. */
	pageToken?: string
	/** AIP-160 filter over labels and filterable fields. */
	filter?: string
	/** AIP-132 ordering over filterable fields. */
	orderBy?: string
}

/** The response of ListAgents. */
export interface ListAgentsResponse {
	/** The page. */
	agents?: Agent[]
	/** The token of the next page; empty on the last page. */
	nextPageToken?: string
}

/** The request of ListMemories. */
export interface ListMemoriesRequest {
	/** The memory store to list in. */
	parent: string
	/** At most this many; default 50, clamped to 1000. */
	pageSize?: number
	/** `next_page_token` of the previous page. */
	pageToken?: string
	/** AIP-160 filter, limited to `end_user` and `agent`. */
	filter?: string
}

/** The response of ListMemories. */
export interface ListMemoriesResponse {
	/** The page. */
	memories?: Memory[]
	/** The token of the next page; empty on the last page. */
	nextPageToken?: string
}

/** The request of ListMemoryStores. */
export interface ListMemoryStoresRequest {
	/** The parent to list in. */
	parent: string
	/** At most this many; default 50, clamped to 1000. */
	pageSize?: number
	/** `next_page_token` of the previous page. */
	pageToken?: string
	/** AIP-160 filter over labels and filterable fields. */
	filter?: string
	/** AIP-132 ordering over filterable fields. */
	orderBy?: string
}

/** The response of ListMemoryStores. */
export interface ListMemoryStoresResponse {
	/** The page. */
	memoryStores?: MemoryStore[]
	/** The token of the next page; empty on the last page. */
	nextPageToken?: string
}

/** The request of ListSessionEvents. */
export interface ListSessionEventsRequest {
	/** The session to list in. */
	parent: string
	/** At most this many; default 50, clamped to 1000. */
	pageSize?: number
	/** `next_page_token` of the previous page. */
	pageToken?: string
	/**
	 * AIP-160 filter, limited to `type` and `sequence`; for example
	 * `sequence > 42`.
	 */
	filter?: string
	/**
	 * When no event matches the filter, wait up to this long for one, at most
	 * 60s; unset answers at once.
	 */
	wait?: string
}

/** The response of ListSessionEvents. */
export interface ListSessionEventsResponse {
	/** The page. */
	sessionEvents?: SessionEvent[]
	/** The token of the next page; empty on the last page. */
	nextPageToken?: string
}

/** An McpServer is a remote MCP server whose tools the agent may call. */
export interface McpServer {
	/** The label its tools are prefixed with, unique within the agent. */
	label?: string
	/** The server's Streamable HTTP endpoint. */
	uri?: string
	/** Only these of its tools; empty allows every tool it lists. */
	allowedTools?: string[]
	/** The credential the gateway presents to the server. */
	credential?: CredentialBinding
}

/** A Memory is one long-term memory record: a fact with its provenance. */
export interface Memory {
	/** `orgs/{org}/projects/{project}/envs/{env}/memory_stores/{memory_store}/memories/{memory}`. */
	name?: string
	/** `mem_<cell><ulid>`; never reused. */
	readonly uid?: string
	/** Resource metadata. */
	meta?: common.ResourceMeta
	/** The memory, at most 16 KiB of text. */
	content?: string
	/** The end user it is about, for a store scoped to end users. */
	endUser?: string
	/** The agent it belongs to, for a store scoped to agents. */
	agent?: string
	/** Where it came from. */
	readonly provenance?: MemoryProvenance
	/** When it was written. */
	readonly createTime?: string
	/** When it was last changed. */
	readonly updateTime?: string
}

/** A MemoryMatch is one recalled memory and how well it matched. */
export interface MemoryMatch {
	/** The memory. */
	memory?: Memory
	/** The relevance, 0 to 1. */
	score?: number
}

/** MemoryProvenance records where a memory came from. */
export interface MemoryProvenance {
	/** Who wrote it. */
	readonly source?: MemorySource
	/** The session it was learned in, when an agent wrote it. */
	readonly session?: string
	/** The event it was learned from, when an agent wrote it. */
	readonly event?: string
	/** The principal that wrote it, when a caller did. */
	readonly principal?: string
}

/**
 * A MemoryStore holds long-term memory records with provenance, recalled by
 * hybrid full-text and vector search. Agents name the stores they use; a
 * store may be shared by many agents.
 */
export interface MemoryStore {
	/** `orgs/{org}/projects/{project}/envs/{env}/memory_stores/{memory_store}`. */
	name?: string
	/** `mst_<cell><ulid>`; never reused. */
	readonly uid?: string
	/** Resource metadata. */
	meta?: common.ResourceMeta
	/** Desired state. */
	spec?: MemoryStoreSpec
	/** Observed state. */
	readonly status?: MemoryStoreStatus
}

/** MemoryStoreSpec is the caller-writable state of a MemoryStore. */
export interface MemoryStoreSpec {
	/** What the store is for, shown to agents; at most 1024 characters. */
	description?: string
	/** Whose memories are kept apart. */
	scope?: MemoryScope
	/**
	 * Memories older than this since their last update are deleted, 1d to
	 * 3650d; unset keeps them until deleted.
	 */
	retention?: string
	/**
	 * Whether agents write memories themselves after each turn; otherwise
	 * only callers write them.
	 */
	agentWrites?: boolean
}

/** MemoryStoreStatus is the observed state of a MemoryStore. */
export interface MemoryStoreStatus {
	/** The generation this status was computed from. */
	readonly observedGeneration?: string
	/** Ready, Reconciling, Stalled. */
	readonly conditions?: common.Condition[]
	/** The number of memories. */
	readonly memoryCount?: string
	/** Bytes stored, content and index together; the billed quantity. */
	readonly storedBytes?: string
}

/** A Message is text and files from a user or the agent. */
export interface Message {
	/** The content, in order; 1 to 64 parts. */
	parts?: ContentPart[]
}

/** ProfileMount attaches a platform Profile by name, never its sign-in values. */
export interface ProfileMount {
	/** `orgs/{org}/projects/{project}/envs/{env}/profiles/{profile}`. */
	name?: string
	/**
	 * `read_only` (default) or `write_back`. Only a write_back grant saves
	 * changes at session end while its lease still answers; empty is read_only.
	 */
	mode?: string
}

/** RepositorySpec identifies the source to prepare in a session's lease. */
export interface RepositorySpec {
	/** The repository URI. Access uses the session's bound credential handles. */
	uri?: string
	/** The commit or ref to check out; empty uses the repository's default branch. */
	revision?: string
}

/** The request of SearchMemories. */
export interface SearchMemoriesRequest {
	/** The memory store to search. */
	parent: string
	/** What to recall, 1 to 2000 characters. */
	query: string
	/** Only memories about this end user. */
	endUser?: string
	/** Only memories of this agent. */
	agent?: string
	/** At most this many; default 10, clamped to 100. */
	pageSize?: number
	/** `next_page_token` of the previous page. */
	pageToken?: string
}

/** The response of SearchMemories. */
export interface SearchMemoriesResponse {
	/** The matches, best first. */
	matches?: MemoryMatch[]
	/** The token of the next page; empty on the last page. */
	nextPageToken?: string
}

/** The request of SendAgentSessionMessage. */
export interface SendAgentSessionMessageRequest {
	/** The name of the session. */
	name: string
	/** The message, 1 to 64 parts. */
	message: Message
}

/**
 * A SessionEvent is one entry of a session's append-only log: a user
 * message, model output, a tool call or result, an approval, or a status
 * change. Events are never changed or reordered; `sequence` is their order.
 */
export interface SessionEvent {
	/** `orgs/{org}/projects/{project}/envs/{env}/agent_sessions/{agent_session}/session_events/{session_event}`. */
	name?: string
	/** `sevt_<cell><ulid>`; never reused. */
	readonly uid?: string
	/** Resource metadata. */
	meta?: common.ResourceMeta
	/** The position in the session's log, from 1, with no gaps. */
	readonly sequence?: string
	/** What the event is. */
	readonly type?: SessionEventType
	/** The turn it belongs to, from 1; 0 for an event outside a turn. */
	readonly turn?: string
	/**
	 * The step within the turn, from 1, assigned by the runtime; 0 for an
	 * event that is not a step.
	 */
	readonly step?: string
	/** When it was appended. */
	readonly createTime?: string
	/** For USER_MESSAGE, STEER and AGENT_MESSAGE. */
	message?: Message
	/** For TOOL_CALL. */
	toolCall?: ToolCall
	/** For TOOL_RESULT. */
	toolResult?: ToolResult
	/** For APPROVAL_REQUESTED and APPROVAL_DECIDED. */
	approval?: Approval
	/** For STATUS. */
	statusChange?: StatusChange
	/** For THOUGHT: a reasoning summary, never private model reasoning. */
	thought?: Message
	/** For FILE_CHANGE. */
	fileChange?: FileChange
	/** For RESPONSE: the completed turn's answer and usage. */
	response?: TurnResult
	/** For ERROR. */
	error?: ErrorEvent
}

/**
 * SessionUsage is what a session has used. Model tokens are on the Sylphx AI
 * meter; this is the Agents part.
 */
export interface SessionUsage {
	/** Time turns were active. */
	readonly activeTurnDuration?: string
	/** Tool calls made through the gateway. */
	readonly gatewayCalls?: string
	/** Spend so far in micro-USD, models and tools together. */
	readonly spendMicros?: string
}

/**
 * A Skill is an instruction pack the agent loads when its description
 * matches the task.
 */
export interface Skill {
	/** The skill's name, unique within the agent. */
	name?: string
	/** When to use it, shown to the model; at most 1024 characters. */
	description?: string
	/** The instructions it loads, at most 256 KiB. */
	instructions?: string
}

/** A StatusChange is the session moving to a new state. */
export interface StatusChange {
	/** The state after the change. */
	readonly state?: SessionState
	/** Why, for FAILED and INTERRUPTED: a registry error code and message. */
	readonly reason?: string
}

/** The request of SteerAgentSession. */
export interface SteerAgentSessionRequest {
	/** The name of the session. */
	name: string
	/** The message, 1 to 64 parts. */
	message: Message
}

/** The request of SubmitAgentSessionToolResult. */
export interface SubmitAgentSessionToolResultRequest {
	/** The name of the session. */
	name: string
	/** The waiting client ToolCall's `id`. */
	callId: string
	/** The result, at most 1 MiB of JSON. */
	output: unknown
	/** Whether the call failed; `output` then holds the error. */
	error?: boolean
}

/**
 * A Tool is one tool an agent may call. Every call goes through the tool
 * gateway: the policy check, credential injection at egress (the model, the
 * event log and traces see a handle, never the value), the egress guard, and
 * one usage record and trace span per call.
 */
export interface Tool {
	/** The name the model calls, unique within the agent. */
	name?: string
	/** What the tool does, shown to the model; at most 4096 characters. */
	description?: string
	/** The JSON Schema of the tool's input. Built-in tools carry their own. */
	inputSchema?: Record<string, unknown>
	/**
	 * A platform tool: `shell`, `files`, `browser`, `computer`, `web_fetch`,
	 * `web_search` or `memory`.
	 */
	builtin?: BuiltinTool
	/** An HTTP API described by OpenAPI. */
	http?: HttpTool
	/**
	 * The app's own server code: the gateway calls it with a short-lived
	 * signed token bound to the session, turn and step.
	 */
	appFunction?: FunctionTool
	/**
	 * Run by the client: the app executes it and returns the result as an
	 * event (`:submitToolResult`).
	 */
	client?: ClientTool
}

/**
 * A ToolCall is the agent asking to call a tool. `id` is assigned by the
 * runtime; the model's own tool-call id is kept only as `model_call_id`, so
 * a model that repeats an id never collides two calls.
 */
export interface ToolCall {
	/** The call's id within the session, `(turn, step)` based. */
	readonly id?: string
	/** The tool name. */
	readonly tool?: string
	/** The input, as the model sent it. */
	readonly input?: Record<string, unknown>
	/** The model's own id for the call, as sent; never used as a key. */
	readonly modelCallId?: string
	/** Whether the client runs it (a ClientTool). */
	readonly client?: boolean
}

/**
 * A ToolPolicy decides each tool call before it runs. A grant is the
 * authorization: the policy asks a person only for a call no existing grant
 * covers. An OAuth scope, a credential bound to the tool, or an earlier
 * "always allow" is that grant.
 */
export interface ToolPolicy {
	/** The decision for a call no rule matches; default allow. */
	defaultDecision?: PolicyDecision
	/** Rules in order; the first match decides. At most 256. */
	rules?: ToolPolicyRule[]
	/**
	 * How long a call waits for a person's answer before it is denied, 1m to
	 * 7d; default 24h.
	 */
	approvalTimeout?: string
	/**
	 * Hosts every network call of the agent's tools may reach, beyond the
	 * tools' own endpoints; `*.example.com` matches subdomains. Private and
	 * internal addresses are refused whatever this says.
	 */
	egressAllowHosts?: string[]
}

/** A ToolPolicyRule matches tool calls by tool name. */
export interface ToolPolicyRule {
	/**
	 * A tool name, `<mcp label>__<tool>` for an MCP tool; `*` matches any
	 * characters.
	 */
	tool?: string
	/** The decision. */
	decision?: PolicyDecision
	/**
	 * A CEL condition over the call's `input`, the session's `end_user` and
	 * `labels`; the rule matches only when it is true. Empty always matches.
	 */
	condition?: string
}

/** A ToolResult is the outcome of one tool call. */
export interface ToolResult {
	/** The ToolCall's `id`. */
	readonly callId?: string
	/** The output. */
	readonly output?: unknown
	/** Whether the call failed; `output` then holds the error. */
	readonly error?: boolean
	/** How long the call took. */
	readonly duration?: string
}

/** TurnResult is a completed turn's response, usage and duration. */
export interface TurnResult {
	/** The final response's text. */
	readonly text?: string
	/** Whether the turn ended with an error. */
	readonly isError?: boolean
	/** Model token usage reported by the harness. */
	readonly usage?: TurnTokenUsage
	/** The reported cost, in micro-USD. */
	readonly costMicros?: string
	/** How long the turn ran. */
	readonly duration?: string
}

/** TurnTokenUsage is the model token usage reported for a completed turn. */
export interface TurnTokenUsage {
	/** Input tokens. */
	readonly inputTokens?: string
	/** Output tokens. */
	readonly outputTokens?: string
	/** Input tokens read from the model's cache. */
	readonly cacheReadTokens?: string
	/** Input tokens written to the model's cache. */
	readonly cacheWriteTokens?: string
}

/** The request of UpdateAgent. */
export interface UpdateAgentRequest {
	/** The agent to update; `name` identifies it. */
	agent: Agent
	/** The fields to write; unset writes every populated field. */
	updateMask?: string
	/** Create the agent when it does not exist (declarative upsert). */
	allowMissing?: boolean
	/** Validate and return the result without writing anything. */
	validateOnly?: boolean
}

/** The request of UpdateMemory. */
export interface UpdateMemoryRequest {
	/** The memory to update; `name` identifies it. */
	memory: Memory
	/** The fields to write; unset writes every populated field. */
	updateMask?: string
	/** Validate and return the result without writing anything. */
	validateOnly?: boolean
}

/** The request of UpdateMemoryStore. */
export interface UpdateMemoryStoreRequest {
	/** The memory store to update; `name` identifies it. */
	memoryStore: MemoryStore
	/** The fields to write; unset writes every populated field. */
	updateMask?: string
	/** Create the memory store when it does not exist (declarative upsert). */
	allowMissing?: boolean
	/** Validate and return the result without writing anything. */
	validateOnly?: boolean
}

/** ApprovalDecision is a person's answer to an approval. */
export type ApprovalDecision = 'approve' | 'reject' | (string & {})

/** MemoryScope is whose memories a store keeps apart. */
export type MemoryScope = 'project' | 'agent' | 'end_user' | (string & {})

/** MemorySource is who wrote a memory. */
export type MemorySource = 'agent' | 'api' | 'import' | (string & {})

/** PolicyDecision is what the tool policy does with a call. */
export type PolicyDecision = 'allow' | 'deny' | 'ask' | (string & {})

/** SessionEventType is what a session event records. */
export type SessionEventType = 'user_message' | 'steer' | 'agent_message' | 'tool_call' | 'tool_result' | 'approval_requested' | 'approval_decided' | 'status' | 'compaction' | 'thought' | 'file_change' | 'response' | 'error' | (string & {})

/** SessionState is where a session is. */
export type SessionState = 'idle' | 'running' | 'awaiting_approval' | 'awaiting_client' | 'failed' | (string & {})

runtime.registerSchemas({
	'sylphx.agents.v1.Agent': [
		['meta', 'meta', 'sylphx.common.v1.ResourceMeta'],
		['spec', 'spec', 'sylphx.agents.v1.AgentSpec'],
		['status', 'status', 'sylphx.agents.v1.AgentStatus'],
	],
	'sylphx.agents.v1.AgentBudget': [
		['maxStepsPerTurn', 'max_steps_per_turn'],
		['turnTimeout', 'turn_timeout'],
		['maxSessionSpendMicros', 'max_session_spend_micros'],
	],
	'sylphx.agents.v1.AgentSession': [
		['meta', 'meta', 'sylphx.common.v1.ResourceMeta'],
		['agentVersion', 'agent_version'],
		['endUser', 'end_user'],
		['turnCount', 'turn_count'],
		['lastEventSequence', 'last_event_sequence'],
		['createTime', 'create_time'],
		['updateTime', 'update_time'],
		['usage', 'usage', 'sylphx.agents.v1.SessionUsage'],
		['environmentLease', 'environment_lease'],
		['environment', 'environment', 'sylphx.agents.v1.EnvironmentSpec'],
		['credentials', 'credentials', 'sylphx.agents.v1.CredentialBinding', 'map'],
		['profiles', 'profiles', 'sylphx.agents.v1.ProfileMount'],
	],
	'sylphx.agents.v1.AgentSpec': [
		['tools', 'tools', 'sylphx.agents.v1.Tool'],
		['mcpServers', 'mcp_servers', 'sylphx.agents.v1.McpServer'],
		['skills', 'skills', 'sylphx.agents.v1.Skill'],
		['memoryStores', 'memory_stores'],
		['toolPolicy', 'tool_policy', 'sylphx.agents.v1.ToolPolicy'],
		['budget', 'budget', 'sylphx.agents.v1.AgentBudget'],
		['endUserAccess', 'end_user_access'],
		['environment', 'environment', 'sylphx.agents.v1.EnvironmentSpec'],
	],
	'sylphx.agents.v1.AgentStatus': [
		['observedGeneration', 'observed_generation'],
		['conditions', 'conditions', 'sylphx.common.v1.Condition'],
		['currentVersion', 'current_version'],
		['currentVersionNumber', 'current_version_number'],
	],
	'sylphx.agents.v1.AgentVersion': [
		['meta', 'meta', 'sylphx.common.v1.ResourceMeta'],
		['versionNumber', 'version_number'],
		['spec', 'spec', 'sylphx.agents.v1.AgentSpec'],
		['agentGeneration', 'agent_generation'],
		['createTime', 'create_time'],
	],
	'sylphx.agents.v1.Approval': [
		['callId', 'call_id'],
	],
	'sylphx.agents.v1.BuiltinTool': [
		['config', 'config', undefined, 'json'],
	],
	'sylphx.agents.v1.ClientTool': [],
	'sylphx.agents.v1.ContentPart': [
		['file', 'file', 'sylphx.agents.v1.FileRef'],
	],
	'sylphx.agents.v1.CreateAgentRequest': [
		['agentId', 'agent_id'],
		['agent', 'agent', 'sylphx.agents.v1.Agent'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.agents.v1.CreateAgentSessionRequest': [
		['agentSessionId', 'agent_session_id'],
		['agentSession', 'agent_session', 'sylphx.agents.v1.AgentSession'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.agents.v1.CreateMemoryRequest': [
		['memoryId', 'memory_id'],
		['memory', 'memory', 'sylphx.agents.v1.Memory'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.agents.v1.CreateMemoryStoreRequest': [
		['memoryStoreId', 'memory_store_id'],
		['memoryStore', 'memory_store', 'sylphx.agents.v1.MemoryStore'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.agents.v1.CredentialBinding': [
		['endUserProvider', 'end_user_provider'],
	],
	'sylphx.agents.v1.DecideAgentSessionApprovalRequest': [
		['callId', 'call_id'],
	],
	'sylphx.agents.v1.DeleteAgentRequest': [
		['allowMissing', 'allow_missing'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.agents.v1.DeleteAgentSessionRequest': [
		['allowMissing', 'allow_missing'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.agents.v1.DeleteMemoryRequest': [
		['allowMissing', 'allow_missing'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.agents.v1.DeleteMemoryStoreRequest': [
		['allowMissing', 'allow_missing'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.agents.v1.EnvironmentSpec': [
		['idleStandby', 'idle_standby'],
		['repo', 'repo', 'sylphx.agents.v1.RepositorySpec'],
		['egress', 'egress', 'sylphx.sandboxes.v1.LeaseNetwork'],
		['budget', 'budget', 'sylphx.sandboxes.v1.LeaseBudget'],
	],
	'sylphx.agents.v1.ErrorEvent': [],
	'sylphx.agents.v1.FileChange': [
		['oldPath', 'old_path'],
	],
	'sylphx.agents.v1.FileRef': [
		['mediaType', 'media_type'],
	],
	'sylphx.agents.v1.FunctionTool': [],
	'sylphx.agents.v1.GetAgentRequest': [],
	'sylphx.agents.v1.GetAgentSessionRequest': [],
	'sylphx.agents.v1.GetAgentVersionRequest': [],
	'sylphx.agents.v1.GetMemoryRequest': [],
	'sylphx.agents.v1.GetMemoryStoreRequest': [],
	'sylphx.agents.v1.GetSessionEventRequest': [],
	'sylphx.agents.v1.HttpTool': [
		['openapiUri', 'openapi_uri'],
		['openapi', 'openapi', undefined, 'json'],
		['operationId', 'operation_id'],
		['credential', 'credential', 'sylphx.agents.v1.CredentialBinding'],
	],
	'sylphx.agents.v1.InterruptAgentSessionRequest': [],
	'sylphx.agents.v1.ListAgentSessionsRequest': [
		['pageSize', 'page_size'],
		['pageToken', 'page_token'],
	],
	'sylphx.agents.v1.ListAgentSessionsResponse': [
		['agentSessions', 'agent_sessions', 'sylphx.agents.v1.AgentSession'],
		['nextPageToken', 'next_page_token'],
	],
	'sylphx.agents.v1.ListAgentVersionsRequest': [
		['pageSize', 'page_size'],
		['pageToken', 'page_token'],
	],
	'sylphx.agents.v1.ListAgentVersionsResponse': [
		['agentVersions', 'agent_versions', 'sylphx.agents.v1.AgentVersion'],
		['nextPageToken', 'next_page_token'],
	],
	'sylphx.agents.v1.ListAgentsRequest': [
		['pageSize', 'page_size'],
		['pageToken', 'page_token'],
		['orderBy', 'order_by'],
	],
	'sylphx.agents.v1.ListAgentsResponse': [
		['agents', 'agents', 'sylphx.agents.v1.Agent'],
		['nextPageToken', 'next_page_token'],
	],
	'sylphx.agents.v1.ListMemoriesRequest': [
		['pageSize', 'page_size'],
		['pageToken', 'page_token'],
	],
	'sylphx.agents.v1.ListMemoriesResponse': [
		['memories', 'memories', 'sylphx.agents.v1.Memory'],
		['nextPageToken', 'next_page_token'],
	],
	'sylphx.agents.v1.ListMemoryStoresRequest': [
		['pageSize', 'page_size'],
		['pageToken', 'page_token'],
		['orderBy', 'order_by'],
	],
	'sylphx.agents.v1.ListMemoryStoresResponse': [
		['memoryStores', 'memory_stores', 'sylphx.agents.v1.MemoryStore'],
		['nextPageToken', 'next_page_token'],
	],
	'sylphx.agents.v1.ListSessionEventsRequest': [
		['pageSize', 'page_size'],
		['pageToken', 'page_token'],
	],
	'sylphx.agents.v1.ListSessionEventsResponse': [
		['sessionEvents', 'session_events', 'sylphx.agents.v1.SessionEvent'],
		['nextPageToken', 'next_page_token'],
	],
	'sylphx.agents.v1.McpServer': [
		['allowedTools', 'allowed_tools'],
		['credential', 'credential', 'sylphx.agents.v1.CredentialBinding'],
	],
	'sylphx.agents.v1.Memory': [
		['meta', 'meta', 'sylphx.common.v1.ResourceMeta'],
		['endUser', 'end_user'],
		['provenance', 'provenance', 'sylphx.agents.v1.MemoryProvenance'],
		['createTime', 'create_time'],
		['updateTime', 'update_time'],
	],
	'sylphx.agents.v1.MemoryMatch': [
		['memory', 'memory', 'sylphx.agents.v1.Memory'],
	],
	'sylphx.agents.v1.MemoryProvenance': [],
	'sylphx.agents.v1.MemoryStore': [
		['meta', 'meta', 'sylphx.common.v1.ResourceMeta'],
		['spec', 'spec', 'sylphx.agents.v1.MemoryStoreSpec'],
		['status', 'status', 'sylphx.agents.v1.MemoryStoreStatus'],
	],
	'sylphx.agents.v1.MemoryStoreSpec': [
		['agentWrites', 'agent_writes'],
	],
	'sylphx.agents.v1.MemoryStoreStatus': [
		['observedGeneration', 'observed_generation'],
		['conditions', 'conditions', 'sylphx.common.v1.Condition'],
		['memoryCount', 'memory_count'],
		['storedBytes', 'stored_bytes'],
	],
	'sylphx.agents.v1.Message': [
		['parts', 'parts', 'sylphx.agents.v1.ContentPart'],
	],
	'sylphx.agents.v1.ProfileMount': [],
	'sylphx.agents.v1.RepositorySpec': [],
	'sylphx.agents.v1.SearchMemoriesRequest': [
		['endUser', 'end_user'],
		['pageSize', 'page_size'],
		['pageToken', 'page_token'],
	],
	'sylphx.agents.v1.SearchMemoriesResponse': [
		['matches', 'matches', 'sylphx.agents.v1.MemoryMatch'],
		['nextPageToken', 'next_page_token'],
	],
	'sylphx.agents.v1.SendAgentSessionMessageRequest': [
		['message', 'message', 'sylphx.agents.v1.Message'],
	],
	'sylphx.agents.v1.SessionEvent': [
		['meta', 'meta', 'sylphx.common.v1.ResourceMeta'],
		['createTime', 'create_time'],
		['message', 'message', 'sylphx.agents.v1.Message'],
		['toolCall', 'tool_call', 'sylphx.agents.v1.ToolCall'],
		['toolResult', 'tool_result', 'sylphx.agents.v1.ToolResult'],
		['approval', 'approval', 'sylphx.agents.v1.Approval'],
		['statusChange', 'status_change', 'sylphx.agents.v1.StatusChange'],
		['thought', 'thought', 'sylphx.agents.v1.Message'],
		['fileChange', 'file_change', 'sylphx.agents.v1.FileChange'],
		['response', 'response', 'sylphx.agents.v1.TurnResult'],
		['error', 'error', 'sylphx.agents.v1.ErrorEvent'],
	],
	'sylphx.agents.v1.SessionUsage': [
		['activeTurnDuration', 'active_turn_duration'],
		['gatewayCalls', 'gateway_calls'],
		['spendMicros', 'spend_micros'],
	],
	'sylphx.agents.v1.Skill': [],
	'sylphx.agents.v1.StatusChange': [],
	'sylphx.agents.v1.SteerAgentSessionRequest': [
		['message', 'message', 'sylphx.agents.v1.Message'],
	],
	'sylphx.agents.v1.SubmitAgentSessionToolResultRequest': [
		['callId', 'call_id'],
		['output', 'output', undefined, 'json'],
	],
	'sylphx.agents.v1.Tool': [
		['inputSchema', 'input_schema', undefined, 'json'],
		['builtin', 'builtin', 'sylphx.agents.v1.BuiltinTool'],
		['http', 'http', 'sylphx.agents.v1.HttpTool'],
		['appFunction', 'app_function', 'sylphx.agents.v1.FunctionTool'],
		['client', 'client', 'sylphx.agents.v1.ClientTool'],
	],
	'sylphx.agents.v1.ToolCall': [
		['input', 'input', undefined, 'json'],
		['modelCallId', 'model_call_id'],
	],
	'sylphx.agents.v1.ToolPolicy': [
		['defaultDecision', 'default_decision'],
		['rules', 'rules', 'sylphx.agents.v1.ToolPolicyRule'],
		['approvalTimeout', 'approval_timeout'],
		['egressAllowHosts', 'egress_allow_hosts'],
	],
	'sylphx.agents.v1.ToolPolicyRule': [],
	'sylphx.agents.v1.ToolResult': [
		['callId', 'call_id'],
		['output', 'output', undefined, 'json'],
	],
	'sylphx.agents.v1.TurnResult': [
		['isError', 'is_error'],
		['usage', 'usage', 'sylphx.agents.v1.TurnTokenUsage'],
		['costMicros', 'cost_micros'],
	],
	'sylphx.agents.v1.TurnTokenUsage': [
		['inputTokens', 'input_tokens'],
		['outputTokens', 'output_tokens'],
		['cacheReadTokens', 'cache_read_tokens'],
		['cacheWriteTokens', 'cache_write_tokens'],
	],
	'sylphx.agents.v1.UpdateAgentRequest': [
		['agent', 'agent', 'sylphx.agents.v1.Agent'],
		['updateMask', 'update_mask'],
		['allowMissing', 'allow_missing'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.agents.v1.UpdateMemoryRequest': [
		['memory', 'memory', 'sylphx.agents.v1.Memory'],
		['updateMask', 'update_mask'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.agents.v1.UpdateMemoryStoreRequest': [
		['memoryStore', 'memory_store', 'sylphx.agents.v1.MemoryStore'],
		['updateMask', 'update_mask'],
		['allowMissing', 'allow_missing'],
		['validateOnly', 'validate_only'],
	],
})

/**
 * AgentsService is Sylphx Agents, the platform's hosted agent runtime
 * (ADR-01M495TCCBZGSQ68A4P4G428H2). Apps call it instead of building their
 * own agent loop, session store, memory and credential handling.
 *
 * Scopes: `agents:read` and `agents:write` manage agents, versions and
 * memory stores with a secret key. `agents:sessions` runs sessions and reads
 * and deletes session and memory records. All methods currently require a
 * secret key. Publishable-key access is deferred until the backend enforces
 * end-user ownership of sessions and memories and `end_user_access` on Agents.
 *
 * Namespace of Sylphx Agents on `Sylphx`.
 */
export class AgentsApi {
	/** The `agents` collection. */
	readonly agents: AgentsCollection
	/** The `agent_versions` collection. */
	readonly agentVersions: AgentVersionsCollection
	/** The `agent_sessions` collection. */
	readonly agentSessions: AgentSessionsCollection
	/** The `session_events` collection. */
	readonly sessionEvents: SessionEventsCollection
	/** The `memory_stores` collection. */
	readonly memoryStores: MemoryStoresCollection
	/** The `memories` collection. */
	readonly memories: MemoriesCollection

	constructor(client: runtime.Client) {
		this.agents = new AgentsCollection(client)
		this.agentVersions = new AgentVersionsCollection(client)
		this.agentSessions = new AgentSessionsCollection(client)
		this.sessionEvents = new SessionEventsCollection(client)
		this.memoryStores = new MemoryStoresCollection(client)
		this.memories = new MemoriesCollection(client)
	}
}

/** `agents` of Sylphx Agents: Resource type `agents.sylphx.com/Agent`. */
export class AgentsCollection {
	private readonly client: runtime.Client

	constructor(client: runtime.Client) {
		this.client = client
	}

	/**
	 * Gets an agent.
	 *
	 * `GET /v1/{name=orgs/*\/projects/*\/envs/*\/agents/*}` · permission `agents:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
	 */
	async get(request: GetAgentRequest): Promise<Agent> {
		return this.client.call<Agent>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/agents/*', 'name')}`,
			responseType: 'sylphx.agents.v1.Agent',
			mutation: false,
		})
	}

	/**
	 * Lists agents.
	 *
	 * `GET /v1/{parent=orgs/*\/projects/*\/envs/*}/agents` · permission `agents:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
	 */
	async list(request: ListAgentsRequest): Promise<ListAgentsResponse> {
		return this.client.call<ListAgentsResponse>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*/projects/*/envs/*', 'parent')}/agents`,
			query: { page_size: request.pageSize, page_token: request.pageToken, filter: request.filter, order_by: request.orderBy },
			responseType: 'sylphx.agents.v1.ListAgentsResponse',
			mutation: false,
		})
	}

	/** Every item of every page of `list`. */
	async *listAll(request: ListAgentsRequest): AsyncGenerator<Agent> {
		let next: ListAgentsRequest = request
		for (;;) {
			const page = await this.list(next)
			yield* page.agents ?? []
			if (page.nextPageToken === undefined || page.nextPageToken === '') return
			next = { ...request, pageToken: page.nextPageToken }
		}
	}

	/**
	 * Creates an agent and its version 1.
	 *
	 * `POST /v1/{parent=orgs/*\/projects/*\/envs/*}/agents` · permission `agents:write` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `RESOURCE_ALREADY_EXISTS`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`, `PLAN_LIMIT_REACHED`.
	 */
	async create(request: CreateAgentRequest): Promise<Agent> {
		return this.client.call<Agent>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*/projects/*/envs/*', 'parent')}/agents`,
			query: { agent_id: request.agentId, validate_only: request.validateOnly },
			body: request.agent ?? {},
			bodyType: 'sylphx.agents.v1.Agent',
			responseType: 'sylphx.agents.v1.Agent',
			mutation: true,
		})
	}

	/**
	 * Updates an agent. A change to `spec` mints the next AgentVersion;
	 * sessions already started keep the version they pinned.
	 *
	 * `PATCH /v1/{agent.name=orgs/*\/projects/*\/envs/*\/agents/*}` · permission `agents:write` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async update(request: UpdateAgentRequest): Promise<Agent> {
		return this.client.call<Agent>({
			method: 'PATCH',
			path: `/v1/${runtime.pathParam(request.agent?.name, 'orgs/*/projects/*/envs/*/agents/*', 'agent.name')}`,
			query: { update_mask: request.updateMask, allow_missing: request.allowMissing, validate_only: request.validateOnly },
			body: request.agent ?? {},
			bodyType: 'sylphx.agents.v1.Agent',
			responseType: 'sylphx.agents.v1.Agent',
			mutation: true,
		})
	}

	/**
	 * Deletes an agent and its versions. An agent with sessions is refused
	 * with `INVALID_STATE` unless `force` is set, which deletes them too.
	 *
	 * `DELETE /v1/{name=orgs/*\/projects/*\/envs/*\/agents/*}` · permission `agents:write` · effect `destructive`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_STATE`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async delete(request: DeleteAgentRequest): Promise<Record<string, never>> {
		return this.client.call<Record<string, never>>({
			method: 'DELETE',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/agents/*', 'name')}`,
			query: { etag: request.etag, allow_missing: request.allowMissing, validate_only: request.validateOnly, force: request.force },
			mutation: true,
		})
	}
}

/** `agent_versions` of Sylphx Agents: Resource type `agents.sylphx.com/AgentVersion`. */
export class AgentVersionsCollection {
	private readonly client: runtime.Client

	constructor(client: runtime.Client) {
		this.client = client
	}

	/**
	 * Gets an agent version.
	 *
	 * `GET /v1/{name=orgs/*\/projects/*\/envs/*\/agents/*\/agent_versions/*}` · permission `agents:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
	 */
	async get(request: GetAgentVersionRequest): Promise<AgentVersion> {
		return this.client.call<AgentVersion>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/agents/*/agent_versions/*', 'name')}`,
			responseType: 'sylphx.agents.v1.AgentVersion',
			mutation: false,
		})
	}

	/**
	 * Lists an agent's versions, newest first.
	 *
	 * `GET /v1/{parent=orgs/*\/projects/*\/envs/*\/agents/*}/agent_versions` · permission `agents:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
	 */
	async list(request: ListAgentVersionsRequest): Promise<ListAgentVersionsResponse> {
		return this.client.call<ListAgentVersionsResponse>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*/projects/*/envs/*/agents/*', 'parent')}/agent_versions`,
			query: { page_size: request.pageSize, page_token: request.pageToken, filter: request.filter },
			responseType: 'sylphx.agents.v1.ListAgentVersionsResponse',
			mutation: false,
		})
	}

	/** Every item of every page of `list`. */
	async *listAll(request: ListAgentVersionsRequest): AsyncGenerator<AgentVersion> {
		let next: ListAgentVersionsRequest = request
		for (;;) {
			const page = await this.list(next)
			yield* page.agentVersions ?? []
			if (page.nextPageToken === undefined || page.nextPageToken === '') return
			next = { ...request, pageToken: page.nextPageToken }
		}
	}
}

/** `agent_sessions` of Sylphx Agents: Resource type `agents.sylphx.com/AgentSession`. */
export class AgentSessionsCollection {
	private readonly client: runtime.Client

	constructor(client: runtime.Client) {
		this.client = client
	}

	/**
	 * Starts a session of an agent, pinned to its current version unless
	 * `agent_version` names another. Requires a secret key until end-user
	 * ownership is implemented. The session starts idle; `:send` starts its
	 * first turn.
	 *
	 * `POST /v1/{parent=orgs/*\/projects/*\/envs/*}/agent_sessions` · permission `agents:sessions` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `RESOURCE_ALREADY_EXISTS`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`, `PLAN_LIMIT_REACHED`, `SPEND_LIMIT_REACHED`.
	 */
	async create(request: CreateAgentSessionRequest): Promise<AgentSession> {
		return this.client.call<AgentSession>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*/projects/*/envs/*', 'parent')}/agent_sessions`,
			query: { agent_session_id: request.agentSessionId, validate_only: request.validateOnly },
			body: request.agentSession ?? {},
			bodyType: 'sylphx.agents.v1.AgentSession',
			responseType: 'sylphx.agents.v1.AgentSession',
			mutation: true,
		})
	}

	/**
	 * Gets a session.
	 *
	 * `GET /v1/{name=orgs/*\/projects/*\/envs/*\/agent_sessions/*}` · permission `agents:sessions` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
	 */
	async get(request: GetAgentSessionRequest): Promise<AgentSession> {
		return this.client.call<AgentSession>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/agent_sessions/*', 'name')}`,
			responseType: 'sylphx.agents.v1.AgentSession',
			mutation: false,
		})
	}

	/**
	 * Lists sessions, newest first. With a publishable key, only the caller's
	 * end user's sessions.
	 *
	 * `GET /v1/{parent=orgs/*\/projects/*\/envs/*}/agent_sessions` · permission `agents:sessions` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
	 */
	async list(request: ListAgentSessionsRequest): Promise<ListAgentSessionsResponse> {
		return this.client.call<ListAgentSessionsResponse>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*/projects/*/envs/*', 'parent')}/agent_sessions`,
			query: { page_size: request.pageSize, page_token: request.pageToken, filter: request.filter },
			responseType: 'sylphx.agents.v1.ListAgentSessionsResponse',
			mutation: false,
		})
	}

	/** Every item of every page of `list`. */
	async *listAll(request: ListAgentSessionsRequest): AsyncGenerator<AgentSession> {
		let next: ListAgentSessionsRequest = request
		for (;;) {
			const page = await this.list(next)
			yield* page.agentSessions ?? []
			if (page.nextPageToken === undefined || page.nextPageToken === '') return
			next = { ...request, pageToken: page.nextPageToken }
		}
	}

	/**
	 * Deletes a session and its events. A session whose turn is running is
	 * refused with `INVALID_STATE` unless `force` is set, which interrupts it
	 * first.
	 *
	 * `DELETE /v1/{name=orgs/*\/projects/*\/envs/*\/agent_sessions/*}` · permission `agents:sessions` · effect `destructive`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_STATE`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async delete(request: DeleteAgentSessionRequest): Promise<Record<string, never>> {
		return this.client.call<Record<string, never>>({
			method: 'DELETE',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/agent_sessions/*', 'name')}`,
			query: { etag: request.etag, allow_missing: request.allowMissing, validate_only: request.validateOnly, force: request.force },
			mutation: true,
		})
	}

	/**
	 * Sends a user message. On an idle or failed session it starts a new turn;
	 * while a turn runs it is refused with `INVALID_STATE` (use `:steer`).
	 * The same `Idempotency-Key` returns the same event.
	 *
	 * `POST /v1/{name=orgs/*\/projects/*\/envs/*\/agent_sessions/*}:send` · permission `agents:sessions` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_FIELD`, `INVALID_STATE`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`, `SPEND_LIMIT_REACHED`.
	 */
	async send(request: SendAgentSessionMessageRequest): Promise<SessionEvent> {
		return this.client.call<SessionEvent>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/agent_sessions/*', 'name')}:send`,
			body: runtime.omit(request, ['name']),
			bodyType: 'sylphx.agents.v1.SendAgentSessionMessageRequest',
			responseType: 'sylphx.agents.v1.SessionEvent',
			mutation: true,
		})
	}

	/**
	 * Sends a message into the running turn; the agent reads it at its next
	 * step. On an idle session it is the same as `:send`.
	 *
	 * `POST /v1/{name=orgs/*\/projects/*\/envs/*\/agent_sessions/*}:steer` · permission `agents:sessions` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_FIELD`, `INVALID_STATE`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async steer(request: SteerAgentSessionRequest): Promise<SessionEvent> {
		return this.client.call<SessionEvent>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/agent_sessions/*', 'name')}:steer`,
			body: runtime.omit(request, ['name']),
			bodyType: 'sylphx.agents.v1.SteerAgentSessionRequest',
			responseType: 'sylphx.agents.v1.SessionEvent',
			mutation: true,
		})
	}

	/**
	 * Stops the running turn at its current step. Calls already made keep
	 * their results; the session becomes idle. A no-op on an idle session.
	 *
	 * `POST /v1/{name=orgs/*\/projects/*\/envs/*\/agent_sessions/*}:interrupt` · permission `agents:sessions` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_FIELD`, `INVALID_STATE`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async interrupt(request: InterruptAgentSessionRequest): Promise<AgentSession> {
		return this.client.call<AgentSession>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/agent_sessions/*', 'name')}:interrupt`,
			body: runtime.omit(request, ['name']),
			bodyType: 'sylphx.agents.v1.InterruptAgentSessionRequest',
			responseType: 'sylphx.agents.v1.AgentSession',
			mutation: true,
		})
	}

	/**
	 * Answers a tool call waiting for approval; the turn continues.
	 *
	 * `POST /v1/{name=orgs/*\/projects/*\/envs/*\/agent_sessions/*}:decideApproval` · permission `agents:sessions` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_FIELD`, `INVALID_STATE`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async decideApproval(request: DecideAgentSessionApprovalRequest): Promise<SessionEvent> {
		return this.client.call<SessionEvent>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/agent_sessions/*', 'name')}:decideApproval`,
			body: runtime.omit(request, ['name']),
			bodyType: 'sylphx.agents.v1.DecideAgentSessionApprovalRequest',
			responseType: 'sylphx.agents.v1.SessionEvent',
			mutation: true,
		})
	}

	/**
	 * Returns the result of a client tool call; the turn continues.
	 *
	 * `POST /v1/{name=orgs/*\/projects/*\/envs/*\/agent_sessions/*}:submitToolResult` · permission `agents:sessions` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_FIELD`, `INVALID_STATE`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async submitToolResult(request: SubmitAgentSessionToolResultRequest): Promise<SessionEvent> {
		return this.client.call<SessionEvent>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/agent_sessions/*', 'name')}:submitToolResult`,
			body: runtime.omit(request, ['name']),
			bodyType: 'sylphx.agents.v1.SubmitAgentSessionToolResultRequest',
			responseType: 'sylphx.agents.v1.SessionEvent',
			mutation: true,
		})
	}
}

/** `session_events` of Sylphx Agents: Resource type `agents.sylphx.com/SessionEvent`. */
export class SessionEventsCollection {
	private readonly client: runtime.Client

	constructor(client: runtime.Client) {
		this.client = client
	}

	/**
	 * Gets a session event.
	 *
	 * `GET /v1/{name=orgs/*\/projects/*\/envs/*\/agent_sessions/*\/session_events/*}` · permission `agents:sessions` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
	 */
	async get(request: GetSessionEventRequest): Promise<SessionEvent> {
		return this.client.call<SessionEvent>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/agent_sessions/*/session_events/*', 'name')}`,
			responseType: 'sylphx.agents.v1.SessionEvent',
			mutation: false,
		})
	}

	/**
	 * Lists a session's events in sequence order. To follow a session, call
	 * again with the filter `sequence > N`, N the last sequence read; `wait`
	 * holds the call open until a newer event is appended or the wait ends.
	 *
	 * `GET /v1/{parent=orgs/*\/projects/*\/envs/*\/agent_sessions/*}/session_events` · permission `agents:sessions` · effect `read`
	 *
	 * Errors: `RESOURCE_NOT_FOUND`, `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
	 */
	async list(request: ListSessionEventsRequest): Promise<ListSessionEventsResponse> {
		return this.client.call<ListSessionEventsResponse>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*/projects/*/envs/*/agent_sessions/*', 'parent')}/session_events`,
			query: { page_size: request.pageSize, page_token: request.pageToken, filter: request.filter, wait: request.wait },
			responseType: 'sylphx.agents.v1.ListSessionEventsResponse',
			mutation: false,
		})
	}

	/** Every item of every page of `list`. */
	async *listAll(request: ListSessionEventsRequest): AsyncGenerator<SessionEvent> {
		let next: ListSessionEventsRequest = request
		for (;;) {
			const page = await this.list(next)
			yield* page.sessionEvents ?? []
			if (page.nextPageToken === undefined || page.nextPageToken === '') return
			next = { ...request, pageToken: page.nextPageToken }
		}
	}
}

/** `memory_stores` of Sylphx Agents: Resource type `agents.sylphx.com/MemoryStore`. */
export class MemoryStoresCollection {
	private readonly client: runtime.Client

	constructor(client: runtime.Client) {
		this.client = client
	}

	/**
	 * Gets a memory store.
	 *
	 * `GET /v1/{name=orgs/*\/projects/*\/envs/*\/memory_stores/*}` · permission `agents:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
	 */
	async get(request: GetMemoryStoreRequest): Promise<MemoryStore> {
		return this.client.call<MemoryStore>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/memory_stores/*', 'name')}`,
			responseType: 'sylphx.agents.v1.MemoryStore',
			mutation: false,
		})
	}

	/**
	 * Lists memory stores.
	 *
	 * `GET /v1/{parent=orgs/*\/projects/*\/envs/*}/memory_stores` · permission `agents:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
	 */
	async list(request: ListMemoryStoresRequest): Promise<ListMemoryStoresResponse> {
		return this.client.call<ListMemoryStoresResponse>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*/projects/*/envs/*', 'parent')}/memory_stores`,
			query: { page_size: request.pageSize, page_token: request.pageToken, filter: request.filter, order_by: request.orderBy },
			responseType: 'sylphx.agents.v1.ListMemoryStoresResponse',
			mutation: false,
		})
	}

	/** Every item of every page of `list`. */
	async *listAll(request: ListMemoryStoresRequest): AsyncGenerator<MemoryStore> {
		let next: ListMemoryStoresRequest = request
		for (;;) {
			const page = await this.list(next)
			yield* page.memoryStores ?? []
			if (page.nextPageToken === undefined || page.nextPageToken === '') return
			next = { ...request, pageToken: page.nextPageToken }
		}
	}

	/**
	 * Creates a memory store.
	 *
	 * `POST /v1/{parent=orgs/*\/projects/*\/envs/*}/memory_stores` · permission `agents:write` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `RESOURCE_ALREADY_EXISTS`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`, `PLAN_LIMIT_REACHED`.
	 */
	async create(request: CreateMemoryStoreRequest): Promise<MemoryStore> {
		return this.client.call<MemoryStore>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*/projects/*/envs/*', 'parent')}/memory_stores`,
			query: { memory_store_id: request.memoryStoreId, validate_only: request.validateOnly },
			body: request.memoryStore ?? {},
			bodyType: 'sylphx.agents.v1.MemoryStore',
			responseType: 'sylphx.agents.v1.MemoryStore',
			mutation: true,
		})
	}

	/**
	 * Updates a memory store.
	 *
	 * `PATCH /v1/{memory_store.name=orgs/*\/projects/*\/envs/*\/memory_stores/*}` · permission `agents:write` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async update(request: UpdateMemoryStoreRequest): Promise<MemoryStore> {
		return this.client.call<MemoryStore>({
			method: 'PATCH',
			path: `/v1/${runtime.pathParam(request.memoryStore?.name, 'orgs/*/projects/*/envs/*/memory_stores/*', 'memory_store.name')}`,
			query: { update_mask: request.updateMask, allow_missing: request.allowMissing, validate_only: request.validateOnly },
			body: request.memoryStore ?? {},
			bodyType: 'sylphx.agents.v1.MemoryStore',
			responseType: 'sylphx.agents.v1.MemoryStore',
			mutation: true,
		})
	}

	/**
	 * Deletes a memory store. A store an agent names is refused with
	 * `RESOURCE_IN_USE`; a store with memories is refused with `INVALID_STATE`
	 * unless `force` is set, which deletes them too.
	 *
	 * `DELETE /v1/{name=orgs/*\/projects/*\/envs/*\/memory_stores/*}` · permission `agents:write` · effect `destructive`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_STATE`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`, `RESOURCE_IN_USE`.
	 */
	async delete(request: DeleteMemoryStoreRequest): Promise<Record<string, never>> {
		return this.client.call<Record<string, never>>({
			method: 'DELETE',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/memory_stores/*', 'name')}`,
			query: { etag: request.etag, allow_missing: request.allowMissing, validate_only: request.validateOnly, force: request.force },
			mutation: true,
		})
	}
}

/** `memories` of Sylphx Agents: Resource type `agents.sylphx.com/Memory`. */
export class MemoriesCollection {
	private readonly client: runtime.Client

	constructor(client: runtime.Client) {
		this.client = client
	}

	/**
	 * Gets a memory.
	 *
	 * `GET /v1/{name=orgs/*\/projects/*\/envs/*\/memory_stores/*\/memories/*}` · permission `agents:sessions` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
	 */
	async get(request: GetMemoryRequest): Promise<Memory> {
		return this.client.call<Memory>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/memory_stores/*/memories/*', 'name')}`,
			responseType: 'sylphx.agents.v1.Memory',
			mutation: false,
		})
	}

	/**
	 * Lists a store's memories, newest first. With a publishable key, only the
	 * caller's end user's memories.
	 *
	 * `GET /v1/{parent=orgs/*\/projects/*\/envs/*\/memory_stores/*}/memories` · permission `agents:sessions` · effect `read`
	 *
	 * Errors: `RESOURCE_NOT_FOUND`, `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
	 */
	async list(request: ListMemoriesRequest): Promise<ListMemoriesResponse> {
		return this.client.call<ListMemoriesResponse>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*/projects/*/envs/*/memory_stores/*', 'parent')}/memories`,
			query: { page_size: request.pageSize, page_token: request.pageToken, filter: request.filter },
			responseType: 'sylphx.agents.v1.ListMemoriesResponse',
			mutation: false,
		})
	}

	/** Every item of every page of `list`. */
	async *listAll(request: ListMemoriesRequest): AsyncGenerator<Memory> {
		let next: ListMemoriesRequest = request
		for (;;) {
			const page = await this.list(next)
			yield* page.memories ?? []
			if (page.nextPageToken === undefined || page.nextPageToken === '') return
			next = { ...request, pageToken: page.nextPageToken }
		}
	}

	/**
	 * Writes a memory.
	 *
	 * `POST /v1/{parent=orgs/*\/projects/*\/envs/*\/memory_stores/*}/memories` · permission `agents:write` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `RESOURCE_ALREADY_EXISTS`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`, `PLAN_LIMIT_REACHED`.
	 */
	async create(request: CreateMemoryRequest): Promise<Memory> {
		return this.client.call<Memory>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*/projects/*/envs/*/memory_stores/*', 'parent')}/memories`,
			query: { memory_id: request.memoryId, validate_only: request.validateOnly },
			body: request.memory ?? {},
			bodyType: 'sylphx.agents.v1.Memory',
			responseType: 'sylphx.agents.v1.Memory',
			mutation: true,
		})
	}

	/**
	 * Changes a memory's content.
	 *
	 * `PATCH /v1/{memory.name=orgs/*\/projects/*\/envs/*\/memory_stores/*\/memories/*}` · permission `agents:write` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async update(request: UpdateMemoryRequest): Promise<Memory> {
		return this.client.call<Memory>({
			method: 'PATCH',
			path: `/v1/${runtime.pathParam(request.memory?.name, 'orgs/*/projects/*/envs/*/memory_stores/*/memories/*', 'memory.name')}`,
			query: { update_mask: request.updateMask, validate_only: request.validateOnly },
			body: request.memory ?? {},
			bodyType: 'sylphx.agents.v1.Memory',
			responseType: 'sylphx.agents.v1.Memory',
			mutation: true,
		})
	}

	/**
	 * Deletes a memory. An end user may delete their own.
	 *
	 * `DELETE /v1/{name=orgs/*\/projects/*\/envs/*\/memory_stores/*\/memories/*}` · permission `agents:sessions` · effect `destructive`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_STATE`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async delete(request: DeleteMemoryRequest): Promise<Record<string, never>> {
		return this.client.call<Record<string, never>>({
			method: 'DELETE',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/memory_stores/*/memories/*', 'name')}`,
			query: { etag: request.etag, allow_missing: request.allowMissing, validate_only: request.validateOnly },
			mutation: true,
		})
	}

	/**
	 * Recalls the memories that best match a query, by hybrid full-text and
	 * vector search. With a publishable key, only the caller's end user's
	 * memories. A read with a request body, like a query.
	 *
	 * `POST /v1/{parent=orgs/*\/projects/*\/envs/*\/memory_stores/*}/memories:search` · permission `agents:sessions` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_FIELD`.
	 */
	async search(request: SearchMemoriesRequest): Promise<SearchMemoriesResponse> {
		return this.client.call<SearchMemoriesResponse>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*/projects/*/envs/*/memory_stores/*', 'parent')}/memories:search`,
			body: runtime.omit(request, ['parent']),
			bodyType: 'sylphx.agents.v1.SearchMemoriesRequest',
			responseType: 'sylphx.agents.v1.SearchMemoriesResponse',
			mutation: true,
		})
	}
}
