// @generated by sylphx-gen 0.1.0 from contracts@1174780dbd31849e23212fb82bd846cdde4210734bd62d17f192504a09ee593c. Do not edit.
// `sylphx.auth.v1`.

import * as runtime from './runtime.js'
import './common.js'
import type * as common from './common.js'

/**
 * An Auth Config is the app scope of Sylphx Auth in one environment: which
 * sign-in methods the customer's app offers, and its MFA, passkey, lockout,
 * session, CAPTCHA, and Account Portal policy. Every Auth fact is scoped to
 * one `orgs/{o}/projects/{p}/envs/{e}`; an environment has exactly one Auth
 * Config, id `default`.
 */
export interface AuthConfig {
	/** `orgs/{org}/projects/{project}/envs/{env}/auth_configs/{auth_config}`. */
	name?: string
	/** `acf_<cell><ulid>`; never reused. */
	readonly uid?: string
	/** Resource metadata. */
	meta?: common.ResourceMeta
	/** Desired state. */
	spec?: AuthConfigSpec
	/** Observed state. */
	readonly status?: AuthConfigStatus
}

/** AuthConfigSpec is the caller-writable state of an AuthConfig. */
export interface AuthConfigSpec {
	/** Sign-in methods offered to end users. */
	authMethods?: AuthMethod[]
	/** Require a second factor for every end user. */
	mfaRequired?: boolean
	/** Passkey policy; unset enforces nothing. */
	passkeyPolicy?: PasskeyPolicy
	/** Progressive lockout by user and IP. */
	lockoutEnabled?: boolean
	/** Session limits. */
	sessionPolicy?: SessionPolicy
	/**
	 * A Kernel Secrets Secret holding the CAPTCHA verifier secret; unset
	 * disables CAPTCHA.
	 */
	captchaSecret?: string
	/** Account Portal origin and branding. */
	portal?: PortalConfig
	/**
	 * The Notify Sending Domain Auth mail is sent from; unset uses the Sylphx
	 * default.
	 */
	mailSendingDomain?: string
	/** A Sylphx Data database end users are synced into; unset disables sync. */
	userSyncDatabase?: string
}

/** AuthConfigStatus is the observed state of an AuthConfig. */
export interface AuthConfigStatus {
	/** The generation this status was computed from. */
	readonly observedGeneration?: string
	/** Ready, Reconciling, Stalled. */
	readonly conditions?: common.Condition[]
	/** The Account Portal origin in use. */
	readonly portalOrigin?: string
	/** The OAuth issuer URI; tokens verify from its JWKS. */
	readonly issuerUri?: string
}

/** The request of CreateCustomerOrganization. */
export interface CreateCustomerOrganizationRequest {
	/** The parent to create in. */
	parent: string
	/**
	 * The customer organization id, the final name segment; the server assigns
	 * one when empty.
	 */
	customerOrganizationId?: string
	/** The customer organization to create; only caller-writable fields are read. */
	customerOrganization: CustomerOrganization
	/** Validate and return the result without writing anything. */
	validateOnly?: boolean
}

/** The request of CreateEndUser. */
export interface CreateEndUserRequest {
	/** The parent to create in. */
	parent: string
	/**
	 * The end user id, the final name segment; the server assigns one when
	 * empty.
	 */
	endUserId?: string
	/** The end user to create; only caller-writable fields are read. */
	endUser: EndUser
	/** Validate and return the result without writing anything. */
	validateOnly?: boolean
}

/** The request of CreateMembership. */
export interface CreateMembershipRequest {
	/** The parent to create in. */
	parent: string
	/**
	 * The membership id, the final name segment; the server assigns one when
	 * empty.
	 */
	membershipId?: string
	/** The membership to create; only caller-writable fields are read. */
	membership: Membership
	/** Validate and return the result without writing anything. */
	validateOnly?: boolean
}

/** The request of CreateOauthClient. */
export interface CreateOauthClientRequest {
	/** The parent to create in. */
	parent: string
	/**
	 * The OAuth client id, the final name segment; the server assigns one when
	 * empty.
	 */
	oauthClientId?: string
	/** The OAuth client to create; only caller-writable fields are read. */
	oauthClient: OauthClient
	/** Validate and return the result without writing anything. */
	validateOnly?: boolean
}

/**
 * A Customer Organization is a B2B tenant inside a customer's app. It is never
 * a Sylphx org and never a Resource name segment of anything but its own
 * memberships.
 */
export interface CustomerOrganization {
	/** `orgs/{org}/projects/{project}/envs/{env}/customer_organizations/{customer_organization}`. */
	name?: string
	/** `cor_<cell><ulid>`; never reused. */
	readonly uid?: string
	/** Resource metadata. */
	meta?: common.ResourceMeta
	/** Unique within the environment. */
	slug?: string
	/** Verified email domains; end users with a matching verified email may join. */
	readonly verifiedDomains?: string[]
	/** App data. */
	publicMetadata?: Record<string, unknown>
	/** Live memberships. */
	readonly memberCount?: number
}

/** The request of DeleteCustomerOrganization. */
export interface DeleteCustomerOrganizationRequest {
	/** The name of the customer organization to delete. */
	name: string
	/** Delete only if the current etag matches. */
	etag?: string
	/** Succeed when the customer organization does not exist. */
	allowMissing?: boolean
	/** Validate without deleting anything. */
	validateOnly?: boolean
	/** Also close every membership. */
	force?: boolean
}

/** The request of DeleteEndUser. */
export interface DeleteEndUserRequest {
	/** The name of the end user to delete. */
	name: string
	/** Delete only if the current etag matches. */
	etag?: string
	/** Succeed when the end user does not exist. */
	allowMissing?: boolean
	/** Validate without deleting anything. */
	validateOnly?: boolean
	/** Also delete the end user's memberships; sessions are always revoked. */
	force?: boolean
}

/** The request of DeleteMembership. */
export interface DeleteMembershipRequest {
	/** The name of the membership to delete. */
	name: string
	/** Delete only if the current etag matches. */
	etag?: string
	/** Succeed when the membership does not exist. */
	allowMissing?: boolean
	/** Validate without deleting anything. */
	validateOnly?: boolean
}

/** The request of DeleteOauthClient. */
export interface DeleteOauthClientRequest {
	/** The name of the OAuth client to delete. */
	name: string
	/** Delete only if the current etag matches. */
	etag?: string
	/** Succeed when the OAuth client does not exist. */
	allowMissing?: boolean
	/** Validate without deleting anything. */
	validateOnly?: boolean
}

/**
 * An End User is a user of a customer's app, never a Sylphx member or
 * principal. `(scope, email)` is unique among live end users. Delete is
 * revocation: it revokes every session and refuses new ones.
 */
export interface EndUser {
	/** `orgs/{org}/projects/{project}/envs/{env}/end_users/{end_user}`. */
	name?: string
	/** `usr_<cell><ulid>`; never reused. */
	readonly uid?: string
	/** Resource metadata. */
	meta?: common.ResourceMeta
	/** The primary email address. */
	email?: string
	/** When `email` was verified. */
	readonly emailVerifyTime?: string
	/** An initial password; write-only, checked against breached passwords. */
	password?: string
	/** The lifecycle state. */
	readonly state?: EndUserState
	/** Enrolled factors. */
	readonly factors?: AuthMethod[]
	/** App data readable by the end user's own tokens. */
	publicMetadata?: Record<string, unknown>
	/** App data readable only with an Access key. */
	privateMetadata?: Record<string, unknown>
	/** The last successful sign-in. */
	readonly lastLoginTime?: string
}

/** The request of GetAuthConfig. */
export interface GetAuthConfigRequest {
	/** The name of the auth config to get. */
	name: string
}

/** The request of GetCustomerOrganization. */
export interface GetCustomerOrganizationRequest {
	/** The name of the customer organization to get. */
	name: string
}

/** The request of GetEndUser. */
export interface GetEndUserRequest {
	/** The name of the end user to get. */
	name: string
}

/** The request of GetMembership. */
export interface GetMembershipRequest {
	/** The name of the membership to get. */
	name: string
}

/** The request of GetOauthClient. */
export interface GetOauthClientRequest {
	/** The name of the OAuth client to get. */
	name: string
}

/** The request of GetSession. */
export interface GetSessionRequest {
	/** The name of the session to get. */
	name: string
}

/** The request of ListCustomerOrganizations. */
export interface ListCustomerOrganizationsRequest {
	/** The parent to list in. */
	parent: string
	/** At most this many; default 50, clamped to 1000. */
	pageSize?: number
	/** `next_page_token` of the previous page. */
	pageToken?: string
	/** AIP-160 filter over labels and filterable fields. */
	filter?: string
	/** AIP-132 ordering over filterable fields. */
	orderBy?: string
}

/** The response of ListCustomerOrganizations. */
export interface ListCustomerOrganizationsResponse {
	/** The page. */
	customerOrganizations?: CustomerOrganization[]
	/** The token of the next page; empty on the last page. */
	nextPageToken?: string
}

/** The request of ListEndUsers. */
export interface ListEndUsersRequest {
	/** The parent to list in. */
	parent: string
	/** At most this many; default 50, clamped to 1000. */
	pageSize?: number
	/** `next_page_token` of the previous page. */
	pageToken?: string
	/** AIP-160 filter over labels and filterable fields. */
	filter?: string
	/** AIP-132 ordering over filterable fields. */
	orderBy?: string
}

/** The response of ListEndUsers. */
export interface ListEndUsersResponse {
	/** The page. */
	endUsers?: EndUser[]
	/** The token of the next page; empty on the last page. */
	nextPageToken?: string
}

/** The request of ListMemberships. */
export interface ListMembershipsRequest {
	/** The parent to list in. */
	parent: string
	/** At most this many; default 50, clamped to 1000. */
	pageSize?: number
	/** `next_page_token` of the previous page. */
	pageToken?: string
	/** AIP-160 filter over labels and filterable fields. */
	filter?: string
	/** AIP-132 ordering over filterable fields. */
	orderBy?: string
}

/** The response of ListMemberships. */
export interface ListMembershipsResponse {
	/** The page. */
	memberships?: Membership[]
	/** The token of the next page; empty on the last page. */
	nextPageToken?: string
}

/** The request of ListOauthClients. */
export interface ListOauthClientsRequest {
	/** The parent to list in. */
	parent: string
	/** At most this many; default 50, clamped to 1000. */
	pageSize?: number
	/** `next_page_token` of the previous page. */
	pageToken?: string
	/** AIP-160 filter over labels and filterable fields. */
	filter?: string
	/** AIP-132 ordering over filterable fields. */
	orderBy?: string
}

/** The response of ListOauthClients. */
export interface ListOauthClientsResponse {
	/** The page. */
	oauthClients?: OauthClient[]
	/** The token of the next page; empty on the last page. */
	nextPageToken?: string
}

/** The request of ListSessions. */
export interface ListSessionsRequest {
	/** The parent to list in. */
	parent: string
	/** At most this many; default 50, clamped to 1000. */
	pageSize?: number
	/** `next_page_token` of the previous page. */
	pageToken?: string
	/** AIP-160 filter over labels and filterable fields. */
	filter?: string
	/** AIP-132 ordering over filterable fields. */
	orderBy?: string
}

/** The response of ListSessions. */
export interface ListSessionsResponse {
	/** The page. */
	sessions?: Session[]
	/** The token of the next page; empty on the last page. */
	nextPageToken?: string
}

/**
 * A Membership places an end user in a customer organization with app-defined
 * roles. Roles are app data, not Access policy. Changes append to history with
 * a current head per (user, organization); Delete closes the membership.
 */
export interface Membership {
	/** `orgs/{org}/projects/{project}/envs/{env}/customer_organizations/{customer_organization}/memberships/{membership}`. */
	name?: string
	/** `mbr_<cell><ulid>`; never reused. */
	readonly uid?: string
	/** Resource metadata. */
	meta?: common.ResourceMeta
	/** The member. */
	endUser?: string
	/** App-defined roles, for example `admin`. */
	roles?: string[]
}

/**
 * An OAuth Client is a relying party of the customer's authorization server:
 * its app, API, or CLI. Tokens are signed by a Kernel Keys handle and verify
 * offline from the published JWKS.
 */
export interface OauthClient {
	/** `orgs/{org}/projects/{project}/envs/{env}/oauth_clients/{oauth_client}`. */
	name?: string
	/** `ocl_<cell><ulid>`; never reused. */
	readonly uid?: string
	/** Resource metadata. */
	meta?: common.ResourceMeta
	/** Desired state. */
	spec?: OauthClientSpec
	/** Observed state. */
	readonly status?: OauthClientStatus
}

/** OauthClientSpec is the caller-writable state of an OauthClient. */
export interface OauthClientSpec {
	/** Confidential or public. */
	clientType?: OauthClientType
	/** How the client authenticates at the token endpoint. */
	tokenEndpointAuthMethod?: TokenEndpointAuthMethod
	/** Exact redirect URIs. */
	redirectUris?: string[]
	/** Allowed grants. */
	grantTypes?: GrantType[]
	/** Scopes the client may request. */
	scopes?: string[]
	/** The client's JWKS URI, for `private_key_jwt`. */
	jwksUri?: string
	/** Require DPoP-bound tokens (RFC 9449). */
	dpopRequired?: boolean
	/** Access token lifetime; default 1h. */
	accessTokenTtl?: string
	/** Refresh token lifetime; default 30d. */
	refreshTokenTtl?: string
}

/** OauthClientStatus is the observed state of an OauthClient. */
export interface OauthClientStatus {
	/** The generation this status was computed from. */
	readonly observedGeneration?: string
	/** Ready, Reconciling, Stalled. */
	readonly conditions?: common.Condition[]
	/** The OAuth `client_id`. */
	readonly clientId?: string
	/**
	 * The client secret, for `client_secret_basic`; set only in the responses of
	 * Create and RollSecret.
	 */
	readonly clientSecret?: string
	/** The last four characters of the client secret. */
	readonly clientSecretLast4?: string
}

/** Passkey requirements. */
export interface PasskeyPolicy {
	/** Require a passkey for every end user. */
	required?: boolean
	/** Refuse synced (multi-device) passkeys. */
	deviceBound?: boolean
	/** Allowed authenticator AAGUIDs; empty allows any. */
	aaguidAllowlist?: string[]
}

/** Account Portal origin and branding. */
export interface PortalConfig {
	/**
	 * A verified Network Domain serving the portal; unset uses the default
	 * origin.
	 */
	customDomain?: string
	/** The product name shown to end users. */
	productTitle?: string
	/** An HTTPS logo URI. */
	logoUri?: string
	/** The primary color, `#rrggbb`. */
	primaryColor?: string
	/** Show Sylphx branding. */
	sylphxBranding?: boolean
}

/** The request of ReactivateEndUser. */
export interface ReactivateEndUserRequest {
	/** The name of the end user. */
	name: string
	/** Act only if the current etag matches. */
	etag?: string
}

/** The request of RevokeEndUserSessions. */
export interface RevokeEndUserSessionsRequest {
	/** The name of the end user. */
	name: string
}

/** The response of RevokeEndUserSessions. */
export interface RevokeEndUserSessionsResponse {
	/** Sessions revoked. */
	revokedCount?: number
}

/** The request of RevokeSession. */
export interface RevokeSessionRequest {
	/** The name of the session. */
	name: string
}

/** The request of RollOauthClientSecret. */
export interface RollOauthClientSecretRequest {
	/** The name of the OAuth client. */
	name: string
	/** How long the old secret keeps verifying; default 24h. */
	gracePeriod?: string
	/** Act only if the current etag matches. */
	etag?: string
	/** Validate without writing anything. */
	validateOnly?: boolean
}

/**
 * A Session is an opaque Auth session of an end user, issued by a sign-in
 * ceremony. Sessions are revoked, never deleted; revocation is a CAEP signal
 * delivered through Sylphx Events.
 */
export interface Session {
	/** `orgs/{org}/projects/{project}/envs/{env}/end_users/{end_user}/sessions/{session}`. */
	name?: string
	/** `ses_<cell><ulid>`; never reused. */
	readonly uid?: string
	/** Resource metadata. */
	meta?: common.ResourceMeta
	/** The session state. */
	readonly state?: SessionState
	/** How the session was established. */
	readonly assurance?: AuthMethod
	/** Whether a second factor was presented. */
	readonly mfa?: boolean
	/** The active customer organization. */
	readonly activeOrganization?: string
	/** The OAuth client the session signed in to, if any. */
	readonly oauthClient?: string
	/** The client IP at sign-in. */
	readonly ipAddress?: string
	/** The user agent at sign-in. */
	readonly userAgent?: string
	/** The last authenticated use. */
	readonly lastActiveTime?: string
	/** When the session expires. */
	readonly expireTime?: string
	/** When the session was revoked. */
	readonly revokeTime?: string
	/** Why the session was revoked. */
	readonly revokeReason?: SessionRevokeReason
}

/** Session limits. */
export interface SessionPolicy {
	/**
	 * Concurrent sessions per end user; excess sessions are revoked, oldest
	 * first. 0 is unlimited.
	 */
	maxConcurrentSessions?: number
	/** Revoke after this long without use; default 30d. */
	idleTimeout?: string
	/** Revoke this long after sign-in regardless of use; default 90d. */
	absoluteTimeout?: string
	/** Bind sessions to network and agent; a mismatch demands step-up. */
	fingerprintBinding?: boolean
}

/** The request of SuspendEndUser. */
export interface SuspendEndUserRequest {
	/** The name of the end user. */
	name: string
	/** Why; shown to administrators only. */
	reason?: string
	/** Act only if the current etag matches. */
	etag?: string
}

/** The request of UpdateAuthConfig. */
export interface UpdateAuthConfigRequest {
	/** The auth config to update; `name` identifies it. */
	authConfig: AuthConfig
	/** The fields to write; unset writes every populated field. */
	updateMask?: string
	/** Create the auth config when it does not exist (declarative upsert). */
	allowMissing?: boolean
	/** Validate and return the result without writing anything. */
	validateOnly?: boolean
}

/** The request of UpdateCustomerOrganization. */
export interface UpdateCustomerOrganizationRequest {
	/** The customer organization to update; `name` identifies it. */
	customerOrganization: CustomerOrganization
	/** The fields to write; unset writes every populated field. */
	updateMask?: string
	/**
	 * Create the customer organization when it does not exist (declarative
	 * upsert).
	 */
	allowMissing?: boolean
	/** Validate and return the result without writing anything. */
	validateOnly?: boolean
}

/** The request of UpdateEndUser. */
export interface UpdateEndUserRequest {
	/** The end user to update; `name` identifies it. */
	endUser: EndUser
	/** The fields to write; unset writes every populated field. */
	updateMask?: string
	/** Validate and return the result without writing anything. */
	validateOnly?: boolean
}

/** The request of UpdateMembership. */
export interface UpdateMembershipRequest {
	/** The membership to update; `name` identifies it. */
	membership: Membership
	/** The fields to write; unset writes every populated field. */
	updateMask?: string
	/** Validate and return the result without writing anything. */
	validateOnly?: boolean
}

/** The request of UpdateOauthClient. */
export interface UpdateOauthClientRequest {
	/** The OAuth client to update; `name` identifies it. */
	oauthClient: OauthClient
	/** The fields to write; unset writes every populated field. */
	updateMask?: string
	/** Create the OAuth client when it does not exist (declarative upsert). */
	allowMissing?: boolean
	/** Validate and return the result without writing anything. */
	validateOnly?: boolean
}

/** A sign-in method or factor. */
export type AuthMethod = 'password' | 'magic_link' | 'email_otp' | 'passkey' | 'totp' | 'oidc' | 'saml' | (string & {})

/** The lifecycle state of an end user. */
export type EndUserState = 'active' | 'suspended' | (string & {})

/** An OAuth grant. */
export type GrantType = 'authorization_code' | 'refresh_token' | 'device_code' | 'client_credentials' | (string & {})

/** RFC 6749 client type. */
export type OauthClientType = 'confidential' | 'public' | (string & {})

/** Why a session was revoked. */
export type SessionRevokeReason = 'sign_out' | 'user' | 'admin' | 'session_limit' | 'recovery' | 'suspended' | 'deleted' | 'fingerprint' | (string & {})

/** The state of a session. */
export type SessionState = 'active' | 'revoked' | 'expired' | (string & {})

/** How a client authenticates at the token endpoint. */
export type TokenEndpointAuthMethod = 'none' | 'client_secret_basic' | 'private_key_jwt' | (string & {})

runtime.registerSchemas({
	'sylphx.auth.v1.AuthConfig': [
		['meta', 'meta', 'sylphx.common.v1.ResourceMeta'],
		['spec', 'spec', 'sylphx.auth.v1.AuthConfigSpec'],
		['status', 'status', 'sylphx.auth.v1.AuthConfigStatus'],
	],
	'sylphx.auth.v1.AuthConfigSpec': [
		['authMethods', 'auth_methods'],
		['mfaRequired', 'mfa_required'],
		['passkeyPolicy', 'passkey_policy', 'sylphx.auth.v1.PasskeyPolicy'],
		['lockoutEnabled', 'lockout_enabled'],
		['sessionPolicy', 'session_policy', 'sylphx.auth.v1.SessionPolicy'],
		['captchaSecret', 'captcha_secret'],
		['portal', 'portal', 'sylphx.auth.v1.PortalConfig'],
		['mailSendingDomain', 'mail_sending_domain'],
		['userSyncDatabase', 'user_sync_database'],
	],
	'sylphx.auth.v1.AuthConfigStatus': [
		['observedGeneration', 'observed_generation'],
		['conditions', 'conditions', 'sylphx.common.v1.Condition'],
		['portalOrigin', 'portal_origin'],
		['issuerUri', 'issuer_uri'],
	],
	'sylphx.auth.v1.CreateCustomerOrganizationRequest': [
		['customerOrganizationId', 'customer_organization_id'],
		['customerOrganization', 'customer_organization', 'sylphx.auth.v1.CustomerOrganization'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.auth.v1.CreateEndUserRequest': [
		['endUserId', 'end_user_id'],
		['endUser', 'end_user', 'sylphx.auth.v1.EndUser'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.auth.v1.CreateMembershipRequest': [
		['membershipId', 'membership_id'],
		['membership', 'membership', 'sylphx.auth.v1.Membership'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.auth.v1.CreateOauthClientRequest': [
		['oauthClientId', 'oauth_client_id'],
		['oauthClient', 'oauth_client', 'sylphx.auth.v1.OauthClient'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.auth.v1.CustomerOrganization': [
		['meta', 'meta', 'sylphx.common.v1.ResourceMeta'],
		['verifiedDomains', 'verified_domains'],
		['publicMetadata', 'public_metadata', undefined, 'json'],
		['memberCount', 'member_count'],
	],
	'sylphx.auth.v1.DeleteCustomerOrganizationRequest': [
		['allowMissing', 'allow_missing'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.auth.v1.DeleteEndUserRequest': [
		['allowMissing', 'allow_missing'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.auth.v1.DeleteMembershipRequest': [
		['allowMissing', 'allow_missing'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.auth.v1.DeleteOauthClientRequest': [
		['allowMissing', 'allow_missing'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.auth.v1.EndUser': [
		['meta', 'meta', 'sylphx.common.v1.ResourceMeta'],
		['emailVerifyTime', 'email_verify_time'],
		['publicMetadata', 'public_metadata', undefined, 'json'],
		['privateMetadata', 'private_metadata', undefined, 'json'],
		['lastLoginTime', 'last_login_time'],
	],
	'sylphx.auth.v1.GetAuthConfigRequest': [],
	'sylphx.auth.v1.GetCustomerOrganizationRequest': [],
	'sylphx.auth.v1.GetEndUserRequest': [],
	'sylphx.auth.v1.GetMembershipRequest': [],
	'sylphx.auth.v1.GetOauthClientRequest': [],
	'sylphx.auth.v1.GetSessionRequest': [],
	'sylphx.auth.v1.ListCustomerOrganizationsRequest': [
		['pageSize', 'page_size'],
		['pageToken', 'page_token'],
		['orderBy', 'order_by'],
	],
	'sylphx.auth.v1.ListCustomerOrganizationsResponse': [
		['customerOrganizations', 'customer_organizations', 'sylphx.auth.v1.CustomerOrganization'],
		['nextPageToken', 'next_page_token'],
	],
	'sylphx.auth.v1.ListEndUsersRequest': [
		['pageSize', 'page_size'],
		['pageToken', 'page_token'],
		['orderBy', 'order_by'],
	],
	'sylphx.auth.v1.ListEndUsersResponse': [
		['endUsers', 'end_users', 'sylphx.auth.v1.EndUser'],
		['nextPageToken', 'next_page_token'],
	],
	'sylphx.auth.v1.ListMembershipsRequest': [
		['pageSize', 'page_size'],
		['pageToken', 'page_token'],
		['orderBy', 'order_by'],
	],
	'sylphx.auth.v1.ListMembershipsResponse': [
		['memberships', 'memberships', 'sylphx.auth.v1.Membership'],
		['nextPageToken', 'next_page_token'],
	],
	'sylphx.auth.v1.ListOauthClientsRequest': [
		['pageSize', 'page_size'],
		['pageToken', 'page_token'],
		['orderBy', 'order_by'],
	],
	'sylphx.auth.v1.ListOauthClientsResponse': [
		['oauthClients', 'oauth_clients', 'sylphx.auth.v1.OauthClient'],
		['nextPageToken', 'next_page_token'],
	],
	'sylphx.auth.v1.ListSessionsRequest': [
		['pageSize', 'page_size'],
		['pageToken', 'page_token'],
		['orderBy', 'order_by'],
	],
	'sylphx.auth.v1.ListSessionsResponse': [
		['sessions', 'sessions', 'sylphx.auth.v1.Session'],
		['nextPageToken', 'next_page_token'],
	],
	'sylphx.auth.v1.Membership': [
		['meta', 'meta', 'sylphx.common.v1.ResourceMeta'],
		['endUser', 'end_user'],
	],
	'sylphx.auth.v1.OauthClient': [
		['meta', 'meta', 'sylphx.common.v1.ResourceMeta'],
		['spec', 'spec', 'sylphx.auth.v1.OauthClientSpec'],
		['status', 'status', 'sylphx.auth.v1.OauthClientStatus'],
	],
	'sylphx.auth.v1.OauthClientSpec': [
		['clientType', 'client_type'],
		['tokenEndpointAuthMethod', 'token_endpoint_auth_method'],
		['redirectUris', 'redirect_uris'],
		['grantTypes', 'grant_types'],
		['jwksUri', 'jwks_uri'],
		['dpopRequired', 'dpop_required'],
		['accessTokenTtl', 'access_token_ttl'],
		['refreshTokenTtl', 'refresh_token_ttl'],
	],
	'sylphx.auth.v1.OauthClientStatus': [
		['observedGeneration', 'observed_generation'],
		['conditions', 'conditions', 'sylphx.common.v1.Condition'],
		['clientId', 'client_id'],
		['clientSecret', 'client_secret'],
		['clientSecretLast4', 'client_secret_last4'],
	],
	'sylphx.auth.v1.PasskeyPolicy': [
		['deviceBound', 'device_bound'],
		['aaguidAllowlist', 'aaguid_allowlist'],
	],
	'sylphx.auth.v1.PortalConfig': [
		['customDomain', 'custom_domain'],
		['productTitle', 'product_title'],
		['logoUri', 'logo_uri'],
		['primaryColor', 'primary_color'],
		['sylphxBranding', 'sylphx_branding'],
	],
	'sylphx.auth.v1.ReactivateEndUserRequest': [],
	'sylphx.auth.v1.RevokeEndUserSessionsRequest': [],
	'sylphx.auth.v1.RevokeEndUserSessionsResponse': [
		['revokedCount', 'revoked_count'],
	],
	'sylphx.auth.v1.RevokeSessionRequest': [],
	'sylphx.auth.v1.RollOauthClientSecretRequest': [
		['gracePeriod', 'grace_period'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.auth.v1.Session': [
		['meta', 'meta', 'sylphx.common.v1.ResourceMeta'],
		['activeOrganization', 'active_organization'],
		['oauthClient', 'oauth_client'],
		['ipAddress', 'ip_address'],
		['userAgent', 'user_agent'],
		['lastActiveTime', 'last_active_time'],
		['expireTime', 'expire_time'],
		['revokeTime', 'revoke_time'],
		['revokeReason', 'revoke_reason'],
	],
	'sylphx.auth.v1.SessionPolicy': [
		['maxConcurrentSessions', 'max_concurrent_sessions'],
		['idleTimeout', 'idle_timeout'],
		['absoluteTimeout', 'absolute_timeout'],
		['fingerprintBinding', 'fingerprint_binding'],
	],
	'sylphx.auth.v1.SuspendEndUserRequest': [],
	'sylphx.auth.v1.UpdateAuthConfigRequest': [
		['authConfig', 'auth_config', 'sylphx.auth.v1.AuthConfig'],
		['updateMask', 'update_mask'],
		['allowMissing', 'allow_missing'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.auth.v1.UpdateCustomerOrganizationRequest': [
		['customerOrganization', 'customer_organization', 'sylphx.auth.v1.CustomerOrganization'],
		['updateMask', 'update_mask'],
		['allowMissing', 'allow_missing'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.auth.v1.UpdateEndUserRequest': [
		['endUser', 'end_user', 'sylphx.auth.v1.EndUser'],
		['updateMask', 'update_mask'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.auth.v1.UpdateMembershipRequest': [
		['membership', 'membership', 'sylphx.auth.v1.Membership'],
		['updateMask', 'update_mask'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.auth.v1.UpdateOauthClientRequest': [
		['oauthClient', 'oauth_client', 'sylphx.auth.v1.OauthClient'],
		['updateMask', 'update_mask'],
		['allowMissing', 'allow_missing'],
		['validateOnly', 'validate_only'],
	],
})

/**
 * AuthService is Sylphx Auth's management surface: sign-in for a customer's
 * own users, their sessions, customer organizations, and OAuth clients
 * (docs/services/auth/vision.md). Sylphx orgs, members, principals, and keys
 * are Kernel Access, never Auth. End-user ceremonies (sign-in, recovery, OAuth
 * authorize and token) are protocol endpoints, not Resource methods.
 *
 * Namespace of Sylphx Auth on `Sylphx`.
 */
export class AuthApi {
	/** The `auth_configs` collection. */
	readonly authConfigs: AuthConfigsCollection
	/** The `end_users` collection. */
	readonly endUsers: EndUsersCollection
	/** The `sessions` collection. */
	readonly sessions: SessionsCollection
	/** The `customer_organizations` collection. */
	readonly customerOrganizations: CustomerOrganizationsCollection
	/** The `memberships` collection. */
	readonly memberships: MembershipsCollection
	/** The `oauth_clients` collection. */
	readonly oauthClients: OauthClientsCollection

	constructor(client: runtime.Client) {
		this.authConfigs = new AuthConfigsCollection(client)
		this.endUsers = new EndUsersCollection(client)
		this.sessions = new SessionsCollection(client)
		this.customerOrganizations = new CustomerOrganizationsCollection(client)
		this.memberships = new MembershipsCollection(client)
		this.oauthClients = new OauthClientsCollection(client)
	}
}

/** `auth_configs` of Sylphx Auth: Resource type `auth.sylphx.com/AuthConfig`. */
export class AuthConfigsCollection {
	private readonly client: runtime.Client

	constructor(client: runtime.Client) {
		this.client = client
	}

	/**
	 * Gets an auth config.
	 *
	 * `GET /v1/{name=orgs/*\/projects/*\/envs/*\/auth_configs/*}` · permission `auth:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
	 */
	async get(request: GetAuthConfigRequest): Promise<AuthConfig> {
		return this.client.call<AuthConfig>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/auth_configs/*', 'name')}`,
			responseType: 'sylphx.auth.v1.AuthConfig',
			mutation: false,
		})
	}

	/**
	 * Updates an auth config.
	 *
	 * `PATCH /v1/{auth_config.name=orgs/*\/projects/*\/envs/*\/auth_configs/*}` · permission `auth:write` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async update(request: UpdateAuthConfigRequest): Promise<AuthConfig> {
		return this.client.call<AuthConfig>({
			method: 'PATCH',
			path: `/v1/${runtime.pathParam(request.authConfig?.name, 'orgs/*/projects/*/envs/*/auth_configs/*', 'auth_config.name')}`,
			query: { update_mask: request.updateMask, allow_missing: request.allowMissing, validate_only: request.validateOnly },
			body: request.authConfig ?? {},
			bodyType: 'sylphx.auth.v1.AuthConfig',
			responseType: 'sylphx.auth.v1.AuthConfig',
			mutation: true,
		})
	}
}

/** `end_users` of Sylphx Auth: Resource type `auth.sylphx.com/EndUser`. */
export class EndUsersCollection {
	private readonly client: runtime.Client

	constructor(client: runtime.Client) {
		this.client = client
	}

	/**
	 * Gets an end user.
	 *
	 * `GET /v1/{name=orgs/*\/projects/*\/envs/*\/end_users/*}` · permission `auth:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
	 */
	async get(request: GetEndUserRequest): Promise<EndUser> {
		return this.client.call<EndUser>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/end_users/*', 'name')}`,
			responseType: 'sylphx.auth.v1.EndUser',
			mutation: false,
		})
	}

	/**
	 * Lists end users.
	 *
	 * `GET /v1/{parent=orgs/*\/projects/*\/envs/*}/end_users` · permission `auth:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
	 */
	async list(request: ListEndUsersRequest): Promise<ListEndUsersResponse> {
		return this.client.call<ListEndUsersResponse>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*/projects/*/envs/*', 'parent')}/end_users`,
			query: { page_size: request.pageSize, page_token: request.pageToken, filter: request.filter, order_by: request.orderBy },
			responseType: 'sylphx.auth.v1.ListEndUsersResponse',
			mutation: false,
		})
	}

	/** Every item of every page of `list`. */
	async *listAll(request: ListEndUsersRequest): AsyncGenerator<EndUser> {
		let next: ListEndUsersRequest = request
		for (;;) {
			const page = await this.list(next)
			yield* page.endUsers ?? []
			if (page.nextPageToken === undefined || page.nextPageToken === '') return
			next = { ...request, pageToken: page.nextPageToken }
		}
	}

	/**
	 * Creates an end user.
	 *
	 * `POST /v1/{parent=orgs/*\/projects/*\/envs/*}/end_users` · permission `auth:write` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `RESOURCE_ALREADY_EXISTS`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`, `PLAN_LIMIT_REACHED`.
	 */
	async create(request: CreateEndUserRequest): Promise<EndUser> {
		return this.client.call<EndUser>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*/projects/*/envs/*', 'parent')}/end_users`,
			query: { end_user_id: request.endUserId, validate_only: request.validateOnly },
			body: request.endUser ?? {},
			bodyType: 'sylphx.auth.v1.EndUser',
			responseType: 'sylphx.auth.v1.EndUser',
			mutation: true,
		})
	}

	/**
	 * Updates an end user.
	 *
	 * `PATCH /v1/{end_user.name=orgs/*\/projects/*\/envs/*\/end_users/*}` · permission `auth:write` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async update(request: UpdateEndUserRequest): Promise<EndUser> {
		return this.client.call<EndUser>({
			method: 'PATCH',
			path: `/v1/${runtime.pathParam(request.endUser?.name, 'orgs/*/projects/*/envs/*/end_users/*', 'end_user.name')}`,
			query: { update_mask: request.updateMask, validate_only: request.validateOnly },
			body: request.endUser ?? {},
			bodyType: 'sylphx.auth.v1.EndUser',
			responseType: 'sylphx.auth.v1.EndUser',
			mutation: true,
		})
	}

	/**
	 * Deletes an end user.
	 *
	 * `DELETE /v1/{name=orgs/*\/projects/*\/envs/*\/end_users/*}` · permission `auth:write` · effect `destructive`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async delete(request: DeleteEndUserRequest): Promise<Record<string, never>> {
		return this.client.call<Record<string, never>>({
			method: 'DELETE',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/end_users/*', 'name')}`,
			query: { etag: request.etag, allow_missing: request.allowMissing, validate_only: request.validateOnly, force: request.force },
			mutation: true,
		})
	}

	/**
	 * Suspends an end user: sessions are revoked and sign-in is refused.
	 *
	 * `POST /v1/{name=orgs/*\/projects/*\/envs/*\/end_users/*}:suspend` · permission `auth:write` · effect `destructive`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_FIELD`, `INVALID_STATE`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`, `ETAG_MISMATCH`.
	 */
	async suspend(request: SuspendEndUserRequest): Promise<EndUser> {
		return this.client.call<EndUser>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/end_users/*', 'name')}:suspend`,
			body: runtime.omit(request, ['name']),
			bodyType: 'sylphx.auth.v1.SuspendEndUserRequest',
			responseType: 'sylphx.auth.v1.EndUser',
			mutation: true,
		})
	}

	/**
	 * Reactivates a suspended end user.
	 *
	 * `POST /v1/{name=orgs/*\/projects/*\/envs/*\/end_users/*}:reactivate` · permission `auth:write` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_FIELD`, `INVALID_STATE`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`, `ETAG_MISMATCH`.
	 */
	async reactivate(request: ReactivateEndUserRequest): Promise<EndUser> {
		return this.client.call<EndUser>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/end_users/*', 'name')}:reactivate`,
			body: runtime.omit(request, ['name']),
			bodyType: 'sylphx.auth.v1.ReactivateEndUserRequest',
			responseType: 'sylphx.auth.v1.EndUser',
			mutation: true,
		})
	}

	/**
	 * Revokes every session of an end user.
	 *
	 * `POST /v1/{name=orgs/*\/projects/*\/envs/*\/end_users/*}:revokeSessions` · permission `auth:write` · effect `destructive`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_FIELD`, `INVALID_STATE`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async revokeSessions(request: RevokeEndUserSessionsRequest): Promise<RevokeEndUserSessionsResponse> {
		return this.client.call<RevokeEndUserSessionsResponse>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/end_users/*', 'name')}:revokeSessions`,
			body: runtime.omit(request, ['name']),
			bodyType: 'sylphx.auth.v1.RevokeEndUserSessionsRequest',
			responseType: 'sylphx.auth.v1.RevokeEndUserSessionsResponse',
			mutation: true,
		})
	}
}

/** `sessions` of Sylphx Auth: Resource type `auth.sylphx.com/Session`. */
export class SessionsCollection {
	private readonly client: runtime.Client

	constructor(client: runtime.Client) {
		this.client = client
	}

	/**
	 * Gets a session.
	 *
	 * `GET /v1/{name=orgs/*\/projects/*\/envs/*\/end_users/*\/sessions/*}` · permission `auth:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
	 */
	async get(request: GetSessionRequest): Promise<Session> {
		return this.client.call<Session>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/end_users/*/sessions/*', 'name')}`,
			responseType: 'sylphx.auth.v1.Session',
			mutation: false,
		})
	}

	/**
	 * Lists sessions.
	 *
	 * `GET /v1/{parent=orgs/*\/projects/*\/envs/*\/end_users/*}/sessions` · permission `auth:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
	 */
	async list(request: ListSessionsRequest): Promise<ListSessionsResponse> {
		return this.client.call<ListSessionsResponse>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*/projects/*/envs/*/end_users/*', 'parent')}/sessions`,
			query: { page_size: request.pageSize, page_token: request.pageToken, filter: request.filter, order_by: request.orderBy },
			responseType: 'sylphx.auth.v1.ListSessionsResponse',
			mutation: false,
		})
	}

	/** Every item of every page of `list`. */
	async *listAll(request: ListSessionsRequest): AsyncGenerator<Session> {
		let next: ListSessionsRequest = request
		for (;;) {
			const page = await this.list(next)
			yield* page.sessions ?? []
			if (page.nextPageToken === undefined || page.nextPageToken === '') return
			next = { ...request, pageToken: page.nextPageToken }
		}
	}

	/**
	 * Revokes a session.
	 *
	 * `POST /v1/{name=orgs/*\/projects/*\/envs/*\/end_users/*\/sessions/*}:revoke` · permission `auth:write` · effect `destructive`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_FIELD`, `INVALID_STATE`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async revoke(request: RevokeSessionRequest): Promise<Session> {
		return this.client.call<Session>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/end_users/*/sessions/*', 'name')}:revoke`,
			body: runtime.omit(request, ['name']),
			bodyType: 'sylphx.auth.v1.RevokeSessionRequest',
			responseType: 'sylphx.auth.v1.Session',
			mutation: true,
		})
	}
}

/** `customer_organizations` of Sylphx Auth: Resource type `auth.sylphx.com/CustomerOrganization`. */
export class CustomerOrganizationsCollection {
	private readonly client: runtime.Client

	constructor(client: runtime.Client) {
		this.client = client
	}

	/**
	 * Gets a customer organization.
	 *
	 * `GET /v1/{name=orgs/*\/projects/*\/envs/*\/customer_organizations/*}` · permission `auth:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
	 */
	async get(request: GetCustomerOrganizationRequest): Promise<CustomerOrganization> {
		return this.client.call<CustomerOrganization>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/customer_organizations/*', 'name')}`,
			responseType: 'sylphx.auth.v1.CustomerOrganization',
			mutation: false,
		})
	}

	/**
	 * Lists customer organizations.
	 *
	 * `GET /v1/{parent=orgs/*\/projects/*\/envs/*}/customer_organizations` · permission `auth:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
	 */
	async list(request: ListCustomerOrganizationsRequest): Promise<ListCustomerOrganizationsResponse> {
		return this.client.call<ListCustomerOrganizationsResponse>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*/projects/*/envs/*', 'parent')}/customer_organizations`,
			query: { page_size: request.pageSize, page_token: request.pageToken, filter: request.filter, order_by: request.orderBy },
			responseType: 'sylphx.auth.v1.ListCustomerOrganizationsResponse',
			mutation: false,
		})
	}

	/** Every item of every page of `list`. */
	async *listAll(request: ListCustomerOrganizationsRequest): AsyncGenerator<CustomerOrganization> {
		let next: ListCustomerOrganizationsRequest = request
		for (;;) {
			const page = await this.list(next)
			yield* page.customerOrganizations ?? []
			if (page.nextPageToken === undefined || page.nextPageToken === '') return
			next = { ...request, pageToken: page.nextPageToken }
		}
	}

	/**
	 * Creates a customer organization.
	 *
	 * `POST /v1/{parent=orgs/*\/projects/*\/envs/*}/customer_organizations` · permission `auth:write` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `RESOURCE_ALREADY_EXISTS`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`, `PLAN_LIMIT_REACHED`.
	 */
	async create(request: CreateCustomerOrganizationRequest): Promise<CustomerOrganization> {
		return this.client.call<CustomerOrganization>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*/projects/*/envs/*', 'parent')}/customer_organizations`,
			query: { customer_organization_id: request.customerOrganizationId, validate_only: request.validateOnly },
			body: request.customerOrganization ?? {},
			bodyType: 'sylphx.auth.v1.CustomerOrganization',
			responseType: 'sylphx.auth.v1.CustomerOrganization',
			mutation: true,
		})
	}

	/**
	 * Updates a customer organization.
	 *
	 * `PATCH /v1/{customer_organization.name=orgs/*\/projects/*\/envs/*\/customer_organizations/*}` · permission `auth:write` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async update(request: UpdateCustomerOrganizationRequest): Promise<CustomerOrganization> {
		return this.client.call<CustomerOrganization>({
			method: 'PATCH',
			path: `/v1/${runtime.pathParam(request.customerOrganization?.name, 'orgs/*/projects/*/envs/*/customer_organizations/*', 'customer_organization.name')}`,
			query: { update_mask: request.updateMask, allow_missing: request.allowMissing, validate_only: request.validateOnly },
			body: request.customerOrganization ?? {},
			bodyType: 'sylphx.auth.v1.CustomerOrganization',
			responseType: 'sylphx.auth.v1.CustomerOrganization',
			mutation: true,
		})
	}

	/**
	 * Deletes a customer organization.
	 *
	 * `DELETE /v1/{name=orgs/*\/projects/*\/envs/*\/customer_organizations/*}` · permission `auth:write` · effect `destructive`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async delete(request: DeleteCustomerOrganizationRequest): Promise<Record<string, never>> {
		return this.client.call<Record<string, never>>({
			method: 'DELETE',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/customer_organizations/*', 'name')}`,
			query: { etag: request.etag, allow_missing: request.allowMissing, validate_only: request.validateOnly, force: request.force },
			mutation: true,
		})
	}
}

/** `memberships` of Sylphx Auth: Resource type `auth.sylphx.com/Membership`. */
export class MembershipsCollection {
	private readonly client: runtime.Client

	constructor(client: runtime.Client) {
		this.client = client
	}

	/**
	 * Gets a membership.
	 *
	 * `GET /v1/{name=orgs/*\/projects/*\/envs/*\/customer_organizations/*\/memberships/*}` · permission `auth:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
	 */
	async get(request: GetMembershipRequest): Promise<Membership> {
		return this.client.call<Membership>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/customer_organizations/*/memberships/*', 'name')}`,
			responseType: 'sylphx.auth.v1.Membership',
			mutation: false,
		})
	}

	/**
	 * Lists memberships.
	 *
	 * `GET /v1/{parent=orgs/*\/projects/*\/envs/*\/customer_organizations/*}/memberships` · permission `auth:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
	 */
	async list(request: ListMembershipsRequest): Promise<ListMembershipsResponse> {
		return this.client.call<ListMembershipsResponse>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*/projects/*/envs/*/customer_organizations/*', 'parent')}/memberships`,
			query: { page_size: request.pageSize, page_token: request.pageToken, filter: request.filter, order_by: request.orderBy },
			responseType: 'sylphx.auth.v1.ListMembershipsResponse',
			mutation: false,
		})
	}

	/** Every item of every page of `list`. */
	async *listAll(request: ListMembershipsRequest): AsyncGenerator<Membership> {
		let next: ListMembershipsRequest = request
		for (;;) {
			const page = await this.list(next)
			yield* page.memberships ?? []
			if (page.nextPageToken === undefined || page.nextPageToken === '') return
			next = { ...request, pageToken: page.nextPageToken }
		}
	}

	/**
	 * Creates a membership.
	 *
	 * `POST /v1/{parent=orgs/*\/projects/*\/envs/*\/customer_organizations/*}/memberships` · permission `auth:write` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `RESOURCE_ALREADY_EXISTS`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`, `PLAN_LIMIT_REACHED`.
	 */
	async create(request: CreateMembershipRequest): Promise<Membership> {
		return this.client.call<Membership>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*/projects/*/envs/*/customer_organizations/*', 'parent')}/memberships`,
			query: { membership_id: request.membershipId, validate_only: request.validateOnly },
			body: request.membership ?? {},
			bodyType: 'sylphx.auth.v1.Membership',
			responseType: 'sylphx.auth.v1.Membership',
			mutation: true,
		})
	}

	/**
	 * Updates a membership.
	 *
	 * `PATCH /v1/{membership.name=orgs/*\/projects/*\/envs/*\/customer_organizations/*\/memberships/*}` · permission `auth:write` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async update(request: UpdateMembershipRequest): Promise<Membership> {
		return this.client.call<Membership>({
			method: 'PATCH',
			path: `/v1/${runtime.pathParam(request.membership?.name, 'orgs/*/projects/*/envs/*/customer_organizations/*/memberships/*', 'membership.name')}`,
			query: { update_mask: request.updateMask, validate_only: request.validateOnly },
			body: request.membership ?? {},
			bodyType: 'sylphx.auth.v1.Membership',
			responseType: 'sylphx.auth.v1.Membership',
			mutation: true,
		})
	}

	/**
	 * Deletes a membership.
	 *
	 * `DELETE /v1/{name=orgs/*\/projects/*\/envs/*\/customer_organizations/*\/memberships/*}` · permission `auth:write` · effect `destructive`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async delete(request: DeleteMembershipRequest): Promise<Record<string, never>> {
		return this.client.call<Record<string, never>>({
			method: 'DELETE',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/customer_organizations/*/memberships/*', 'name')}`,
			query: { etag: request.etag, allow_missing: request.allowMissing, validate_only: request.validateOnly },
			mutation: true,
		})
	}
}

/** `oauth_clients` of Sylphx Auth: Resource type `auth.sylphx.com/OauthClient`. */
export class OauthClientsCollection {
	private readonly client: runtime.Client

	constructor(client: runtime.Client) {
		this.client = client
	}

	/**
	 * Gets an OAuth client.
	 *
	 * `GET /v1/{name=orgs/*\/projects/*\/envs/*\/oauth_clients/*}` · permission `auth:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
	 */
	async get(request: GetOauthClientRequest): Promise<OauthClient> {
		return this.client.call<OauthClient>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/oauth_clients/*', 'name')}`,
			responseType: 'sylphx.auth.v1.OauthClient',
			mutation: false,
		})
	}

	/**
	 * Lists OAuth clients.
	 *
	 * `GET /v1/{parent=orgs/*\/projects/*\/envs/*}/oauth_clients` · permission `auth:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
	 */
	async list(request: ListOauthClientsRequest): Promise<ListOauthClientsResponse> {
		return this.client.call<ListOauthClientsResponse>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*/projects/*/envs/*', 'parent')}/oauth_clients`,
			query: { page_size: request.pageSize, page_token: request.pageToken, filter: request.filter, order_by: request.orderBy },
			responseType: 'sylphx.auth.v1.ListOauthClientsResponse',
			mutation: false,
		})
	}

	/** Every item of every page of `list`. */
	async *listAll(request: ListOauthClientsRequest): AsyncGenerator<OauthClient> {
		let next: ListOauthClientsRequest = request
		for (;;) {
			const page = await this.list(next)
			yield* page.oauthClients ?? []
			if (page.nextPageToken === undefined || page.nextPageToken === '') return
			next = { ...request, pageToken: page.nextPageToken }
		}
	}

	/**
	 * Creates an OAuth client.
	 *
	 * `POST /v1/{parent=orgs/*\/projects/*\/envs/*}/oauth_clients` · permission `auth:write` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `RESOURCE_ALREADY_EXISTS`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`, `PLAN_LIMIT_REACHED`.
	 */
	async create(request: CreateOauthClientRequest): Promise<OauthClient> {
		return this.client.call<OauthClient>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*/projects/*/envs/*', 'parent')}/oauth_clients`,
			query: { oauth_client_id: request.oauthClientId, validate_only: request.validateOnly },
			body: request.oauthClient ?? {},
			bodyType: 'sylphx.auth.v1.OauthClient',
			responseType: 'sylphx.auth.v1.OauthClient',
			mutation: true,
		})
	}

	/**
	 * Updates an OAuth client.
	 *
	 * `PATCH /v1/{oauth_client.name=orgs/*\/projects/*\/envs/*\/oauth_clients/*}` · permission `auth:write` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async update(request: UpdateOauthClientRequest): Promise<OauthClient> {
		return this.client.call<OauthClient>({
			method: 'PATCH',
			path: `/v1/${runtime.pathParam(request.oauthClient?.name, 'orgs/*/projects/*/envs/*/oauth_clients/*', 'oauth_client.name')}`,
			query: { update_mask: request.updateMask, allow_missing: request.allowMissing, validate_only: request.validateOnly },
			body: request.oauthClient ?? {},
			bodyType: 'sylphx.auth.v1.OauthClient',
			responseType: 'sylphx.auth.v1.OauthClient',
			mutation: true,
		})
	}

	/**
	 * Deletes an OAuth client.
	 *
	 * `DELETE /v1/{name=orgs/*\/projects/*\/envs/*\/oauth_clients/*}` · permission `auth:write` · effect `destructive`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async delete(request: DeleteOauthClientRequest): Promise<Record<string, never>> {
		return this.client.call<Record<string, never>>({
			method: 'DELETE',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/oauth_clients/*', 'name')}`,
			query: { etag: request.etag, allow_missing: request.allowMissing, validate_only: request.validateOnly },
			mutation: true,
		})
	}

	/**
	 * Issues a new client secret, returned once; the old one verifies until
	 * `grace_period` ends.
	 *
	 * `POST /v1/{name=orgs/*\/projects/*\/envs/*\/oauth_clients/*}:rollSecret` · permission `auth:write` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_FIELD`, `INVALID_STATE`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`, `ETAG_MISMATCH`.
	 */
	async rollSecret(request: RollOauthClientSecretRequest): Promise<OauthClient> {
		return this.client.call<OauthClient>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/projects/*/envs/*/oauth_clients/*', 'name')}:rollSecret`,
			body: runtime.omit(request, ['name']),
			bodyType: 'sylphx.auth.v1.RollOauthClientSecretRequest',
			responseType: 'sylphx.auth.v1.OauthClient',
			mutation: true,
		})
	}
}
