// @generated by sylphx-gen 0.1.0 from contracts@319768ce752defa9d02611bfe923266f6cc56ce7cd067e6845cd6a507417c6aa. Do not edit.
// `sylphx.billing.v1`.

import * as runtime from './runtime.js'
import './common.js'
import type * as common from './common.js'

/**
 * A BillingAccount is an org's plan subscription and payment standing: the
 * plan it is on, its spend limit, and its billing period. Each org has
 * exactly one, `orgs/{org}/billing_accounts/default`, created with the org.
 */
export interface BillingAccount {
	/** `orgs/{org}/billing_accounts/default`. */
	name?: string
	/** `bac_<cell><ulid>`. */
	readonly uid?: string
	/** Resource metadata. */
	meta?: common.ResourceMeta
	/** Desired state. */
	spec?: BillingAccountSpec
	/** Observed state. */
	readonly status?: BillingAccountStatus
}

/** BillingAccountSpec is the caller-writable state of a BillingAccount. */
export interface BillingAccountSpec {
	/**
	 * The plan to be on, for example `plans/pro`. A change takes effect at
	 * once; an upgrade to Pro is prorated by day and requires a payment method.
	 */
	plan?: string
	/**
	 * The monthly spend limit on usage past the included amounts. Unset means
	 * the default (USD 200) unless `unlimited_spend` is set.
	 */
	spendLimit?: Money
	/** No spend limit; requires a verified payment method. */
	unlimitedSpend?: boolean
	/** Where invoices and payment notices are sent. */
	billingEmail?: string
}

/** BillingAccountStatus is the observed state of a BillingAccount. */
export interface BillingAccountStatus {
	/** The generation this status was computed from. */
	readonly observedGeneration?: string
	/** Ready, Reconciling, Stalled. */
	readonly conditions?: common.Condition[]
	/** The plan version the org is on, for example `2026-11-02`. */
	readonly planVersion?: string
	/** The payment standing. */
	readonly state?: BillingAccountState
	/** The currency every invoice of the org is in, ISO 4217. */
	readonly currencyCode?: string
	/** The start of the current billing period. */
	readonly periodStartTime?: string
	/** The end of the current billing period. */
	readonly periodEndTime?: string
	/** A payment method is on file and verified. */
	readonly paymentMethodVerified?: boolean
	/**
	 * The spend limit in force, after the default is applied; unset when
	 * unlimited.
	 */
	readonly effectiveSpendLimit?: Money
	/**
	 * The default payment method, for example `visa •••• 4242`; empty when
	 * none is saved.
	 */
	readonly paymentMethod?: string
}

/**
 * A BudgetLease is budget Billing pre-authorized for one holder to spend
 * on hard-spend usage without calling Billing per request (metering.md §8).
 * Readable by the org; written only by Billing.
 */
export interface BudgetLease {
	/** `orgs/{org}/budget_leases/{budget_lease}`. */
	name?: string
	/** `bl_<cell><ulid>`. */
	readonly uid?: string
	/** Resource metadata. */
	readonly meta?: common.ResourceMeta
	/**
	 * The holder: a SPIFFE role and Cell, for example
	 * `services/sandboxes/cells/hk01`.
	 */
	readonly holder?: string
	/** The pool: `sandboxes`, `ai`, `runners`, or `notify.sms`. */
	readonly pool?: string
	/**
	 * Billing's valuation of the grant at list price, in nano-USD; 0 for a
	 * class Sylphx runs but does not sell.
	 */
	readonly grantedNanoUsd?: string
	/**
	 * The fence: monotonic per org, holder, and lease key; a renewal carrying
	 * an older value is refused.
	 */
	readonly fence?: string
	/** When the holder stops debiting the lease. */
	readonly expireTime?: string
	/** The lease's lifecycle state. */
	readonly state?: BudgetLeaseState
	/** The debit the holder reported on renew or release, in nano-USD. */
	readonly reportedDebitNanoUsd?: string
	/** The debit rated from ingested usage, in nano-USD. */
	readonly settledDebitNanoUsd?: string
	/**
	 * The leased meter. A lease is in the meter's units: the holder never
	 * holds a price, Billing prices each grant from its price book.
	 */
	readonly meter?: string
	/** The meter version leased. */
	readonly meterVersion?: number
	/** The lease key: the meter's required dimensions. */
	readonly dimensions?: Record<string, string>
	/** The units granted, in the meter's base unit. */
	readonly grantedQuantity?: string
	/** The units the holder reported on renew or release. */
	readonly reportedDebitQuantity?: string
	/** The units ingested usage attributes to the lease. */
	readonly settledQuantity?: string
}

/** CreditNote is an append-only correction of a finalized invoice. */
export interface CreditNote {
	/** The human-readable credit note number. */
	readonly number?: string
	/** The amount credited. */
	readonly total?: Money
	/** A customer-safe reason. */
	readonly reason?: string
	/** When the credit note was issued. */
	readonly issueTime?: string
}

/** The request of GetBillingAccount. */
export interface GetBillingAccountRequest {
	/** The name of the billing account to get. */
	name: string
}

/** The request of GetBudgetLease. */
export interface GetBudgetLeaseRequest {
	/** The name of the budget lease to get. */
	name: string
}

/** The request of GetInvoice. */
export interface GetInvoiceRequest {
	/** The name of the invoice to get. */
	name: string
}

/** The request of GetMeter. */
export interface GetMeterRequest {
	/** The name of the meter to get. */
	name: string
}

/** The request of GetPlan. */
export interface GetPlanRequest {
	/** The name of the plan to get. */
	name: string
}

/** The request of GetUsageReport. */
export interface GetUsageReportRequest {
	/** The name of the usage report to get. */
	name: string
}

/**
 * An Invoice is one org's bill for one billing period: per-service meter
 * lines, the plan fee, and late usage from earlier periods. Finalization
 * freezes it; a correction is a credit note, never an edit.
 */
export interface Invoice {
	/** `orgs/{org}/invoices/{invoice}`. */
	name?: string
	/** `inv_<cell><ulid>`. */
	readonly uid?: string
	/** Resource metadata. */
	readonly meta?: common.ResourceMeta
	/** The human-readable invoice number, unique per org. */
	readonly number?: string
	/** The invoice's lifecycle state. */
	readonly state?: InvoiceState
	/** ISO 4217 currency of every amount. */
	readonly currencyCode?: string
	/** The start of the billed period. */
	readonly periodStartTime?: string
	/** The end of the billed period. */
	readonly periodEndTime?: string
	/** The lines, grouped by service. */
	readonly lines?: InvoiceLine[]
	/** The sum of the rounded lines before tax. */
	readonly subtotal?: Money
	/** Tax. */
	readonly tax?: Money
	/** Subtotal plus tax. */
	readonly total?: Money
	/** What is still owed. */
	readonly amountDue?: Money
	/** What has been paid, confirmed by provider readback. */
	readonly amountPaid?: Money
	/** When the invoice was finalized. */
	readonly finalizeTime?: string
	/** When payment is due. */
	readonly dueTime?: string
	/** When the invoice was paid in full. */
	readonly paidTime?: string
	/**
	 * The share of the period's usage that had reached Billing when the
	 * invoice was finalized, from 0 to 1; below 1 the invoice carries a note.
	 */
	readonly completeness?: number
	/** Credit notes issued against this invoice, oldest first. */
	readonly creditNotes?: CreditNote[]
}

/** InvoiceLine is one line of an invoice. */
export interface InvoiceLine {
	/** What the line charges for. */
	readonly kind?: InvoiceLineKind
	/** A customer-safe description. */
	readonly description?: string
	/** The service the line belongs to; empty for the plan fee. */
	readonly service?: string
	/** The meter id, for usage lines. */
	readonly meter?: string
	/** The meter version, for usage lines. */
	readonly meterVersion?: number
	/** The dimensions the price matched. */
	readonly dimensions?: Record<string, string>
	/** The price tier, from 1. */
	readonly tier?: number
	/** The rated quantity, in the meter's base unit. */
	readonly quantity?: string
	/** The price per base unit. */
	readonly unitAmountMinor?: Rational
	/** The line amount, rounded half-even to minor units. */
	readonly amount?: Money
}

/** The request of ListBillingAccounts. */
export interface ListBillingAccountsRequest {
	/** The org to list in. */
	parent: string
	/** At most this many; default 50, clamped to 1000. */
	pageSize?: number
	/** `next_page_token` of the previous page. */
	pageToken?: string
	/** AIP-160 filter over labels and filterable fields. */
	filter?: string
	/** AIP-132 ordering over filterable fields. */
	orderBy?: string
}

/** The response of ListBillingAccounts. */
export interface ListBillingAccountsResponse {
	/** The page. */
	billingAccounts?: BillingAccount[]
	/** The token of the next page; empty on the last page. */
	nextPageToken?: string
}

/** The request of ListBudgetLeases. */
export interface ListBudgetLeasesRequest {
	/** The org to list in. */
	parent: string
	/** At most this many; default 50, clamped to 1000. */
	pageSize?: number
	/** `next_page_token` of the previous page. */
	pageToken?: string
	/** AIP-160 filter over labels and filterable fields. */
	filter?: string
	/** AIP-132 ordering over filterable fields. */
	orderBy?: string
}

/** The response of ListBudgetLeases. */
export interface ListBudgetLeasesResponse {
	/** The page. */
	budgetLeases?: BudgetLease[]
	/** The token of the next page; empty on the last page. */
	nextPageToken?: string
}

/** The request of ListInvoices. */
export interface ListInvoicesRequest {
	/** The org to list in. */
	parent: string
	/** At most this many; default 50, clamped to 1000. */
	pageSize?: number
	/** `next_page_token` of the previous page. */
	pageToken?: string
	/** AIP-160 filter over labels and filterable fields. */
	filter?: string
	/** AIP-132 ordering over filterable fields. */
	orderBy?: string
}

/** The response of ListInvoices. */
export interface ListInvoicesResponse {
	/** The page. */
	invoices?: Invoice[]
	/** The token of the next page; empty on the last page. */
	nextPageToken?: string
}

/** The request of ListMeters. */
export interface ListMetersRequest {
	/** At most this many; default 50, clamped to 1000. */
	pageSize?: number
	/** `next_page_token` of the previous page. */
	pageToken?: string
	/** AIP-160 filter over labels and filterable fields. */
	filter?: string
	/** AIP-132 ordering over filterable fields. */
	orderBy?: string
}

/** The response of ListMeters. */
export interface ListMetersResponse {
	/** The page. */
	meters?: Meter[]
	/** The token of the next page; empty on the last page. */
	nextPageToken?: string
}

/** The request of ListPlans. */
export interface ListPlansRequest {
	/** At most this many; default 50, clamped to 1000. */
	pageSize?: number
	/** `next_page_token` of the previous page. */
	pageToken?: string
	/** AIP-160 filter over labels and filterable fields. */
	filter?: string
	/** AIP-132 ordering over filterable fields. */
	orderBy?: string
}

/** The response of ListPlans. */
export interface ListPlansResponse {
	/** The page. */
	plans?: Plan[]
	/** The token of the next page; empty on the last page. */
	nextPageToken?: string
}

/** The request of ListUsageReports. */
export interface ListUsageReportsRequest {
	/** The org to list in. */
	parent: string
	/** At most this many; default 50, clamped to 1000. */
	pageSize?: number
	/** `next_page_token` of the previous page. */
	pageToken?: string
	/** AIP-160 filter over labels and filterable fields. */
	filter?: string
	/** AIP-132 ordering over filterable fields. */
	orderBy?: string
}

/** The response of ListUsageReports. */
export interface ListUsageReportsResponse {
	/** The page. */
	usageReports?: UsageReport[]
	/** The token of the next page; empty on the last page. */
	nextPageToken?: string
}

/**
 * A Meter is one billable quantity a service emits, for example
 * `hosting.vcpu_seconds` (metering.md §4). Meters are top-level and
 * read-only; each has immutable versions, and a usage event names the
 * version it was measured under.
 */
export interface Meter {
	/**
	 * `meters/{meter}`, where `{meter}` is the meter id
	 * `{service}.{quantity}`, for example `meters/hosting.vcpu_seconds`.
	 */
	name?: string
	/** `mtr_<cell><ulid>`. */
	readonly uid?: string
	/** Resource metadata. */
	readonly meta?: common.ResourceMeta
	/** The service that emits the meter; the meter id's prefix. */
	readonly service?: string
	/** The version new usage is measured under. */
	readonly currentVersion?: number
	/** Every version, oldest first. */
	readonly versions?: MeterVersion[]
}

/** MeterDimension is one key a usage event of a meter may carry. */
export interface MeterDimension {
	/** The dimension key, for example `class`. */
	readonly key?: string
	/** The allowed values; empty means a bounded free-form string. */
	readonly values?: string[]
	/** Every event must carry it. */
	readonly required?: boolean
}

/**
 * MeterPrice is a plan's included quantity and price for one meter version,
 * optionally narrowed to a dimension set (metering.md §4.3).
 */
export interface MeterPrice {
	/** The meter id. */
	readonly meter?: string
	/** The meter version the price applies to. */
	readonly meterVersion?: number
	/**
	 * The dimensions a usage row must carry for this price to apply; the most
	 * specific match wins.
	 */
	readonly dimensionMatch?: Record<string, string>
	/** The quantity included per period, in the meter's base unit. */
	readonly included?: string
	/** What happens past the included quantity. */
	readonly overage?: Overage
	/** Price tiers past the included quantity, lowest first. */
	readonly tiers?: PriceTier[]
}

/** MeterVersion is one immutable definition of a meter. */
export interface MeterVersion {
	/** The version number, from 1. */
	readonly version?: number
	/** The base unit, for example `s`, `B`, or `tokens`. */
	readonly unit?: string
	/** How quantities combine over a period. */
	readonly aggregation?: MeterAggregation
	/** The dimensions a usage event may carry; at most 8. */
	readonly dimensions?: MeterDimension[]
	/** Spend is bounded by budget leases (metering.md §8). */
	readonly hardSpend?: boolean
	/**
	 * A quantity is an integer count of 1/value_scale base units; 1 for
	 * integral units.
	 */
	readonly valueScale?: string
	/** When usage starts being measured under this version. */
	readonly effectiveTime?: string
}

/** Money is an amount in one currency, in integer minor units. */
export interface Money {
	/** ISO 4217 currency, for example `USD`. */
	currencyCode?: string
	/** The amount in the currency's minor unit (cents for USD). */
	unitsMinor?: string
}

/**
 * A Plan is a public or private price list: Free, Pro, and the private
 * plans onboarding needs (`agent-trial`, partner plans). Plans are top-level
 * and read-only; each has immutable dated versions, and an org is on
 * exactly one plan version at a time.
 */
export interface Plan {
	/** `plans/{plan}`, for example `plans/pro`. */
	name?: string
	/** `pln_<cell><ulid>`. */
	readonly uid?: string
	/** Resource metadata. */
	readonly meta?: common.ResourceMeta
	/**
	 * Listed on the pricing page; private plans are visible only to their
	 * orgs.
	 */
	readonly listed?: boolean
	/** The version new subscriptions start on, for example `2026-11-02`. */
	readonly currentVersion?: string
	/** Every version, oldest first. */
	readonly versions?: PlanVersion[]
}

/** PlanVersion is one immutable, dated version of a plan. */
export interface PlanVersion {
	/** The version, the date it takes effect: `YYYY-MM-DD`. */
	readonly version?: string
	/** When the version takes effect. */
	readonly effectiveTime?: string
	/** The monthly fee, charged in advance. */
	readonly fee?: Money
	/** A monthly usage credit applied to overage. */
	readonly includedCredit?: Money
	/** A payment method is required to be on this plan. */
	readonly paymentMethodRequired?: boolean
	/** Included quantity and price per meter. */
	readonly meterPrices?: MeterPrice[]
	/**
	 * The most Resources per collection, for example `projects`; -1 means
	 * unlimited.
	 */
	readonly resourceLimits?: Record<string, string>
	/**
	 * Requests per minute per rate class (`rate_limit_policies` × 60, without
	 * bursts or bands).
	 */
	readonly rateLimits?: Record<string, string>
	/**
	 * The rate limit per rate class (`control`, `inference`) as a token bucket,
	 * then the higher limits of each committed-spend band.
	 */
	readonly rateLimitPolicies?: RateLimitPolicy[]
}

/** PriceTier is one tier of a graduated price. */
export interface PriceTier {
	/**
	 * The tier ends at this quantity in the period, inclusive; 0 means
	 * unbounded.
	 */
	readonly upperBound?: string
	/** The price per base unit, in minor units of the plan's currency. */
	readonly unitAmountMinor?: Rational
}

/** The request of QueryUsageReports. */
export interface QueryUsageReportsRequest {
	/** The org to query. */
	parent: string
	/** The start of the range, inclusive. */
	startTime: string
	/** The end of the range, exclusive; at most 400 days after `start_time`. */
	endTime: string
	/** The bucket width. */
	granularity: UsageGranularity
	/** Only these projects; empty means every project. */
	projects?: string[]
	/** Only these meter ids; empty means every meter. */
	meters?: string[]
	/** Group by project in addition to meter. */
	groupProjects?: boolean
	/** Dimension keys to group by, for example `model`. */
	groupDimensions?: string[]
}

/** The response of QueryUsageReports. */
export interface QueryUsageReportsResponse {
	/** One row per bucket and group, in time order; at most 10,000. */
	rows?: UsageRow[]
	/** The share of the range's usage that has reached Billing, from 0 to 1. */
	completeness?: number
	/** The instant the answer reflects. */
	computeTime?: string
	/**
	 * Each emitting service's watermark: the time of the oldest usage it has
	 * not yet delivered (metering.md §7.4).
	 */
	watermarks?: Record<string, string>
}

/** RateLimitPolicy is one rate class's token bucket on a plan version. */
export interface RateLimitPolicy {
	/** `control` (the Resource API) or `inference` (AI requests). */
	readonly rateClass?: string
	/** Sustained requests per second, per org. */
	readonly requestsPerSecond?: string
	/** Requests the bucket holds for a burst. */
	readonly burst?: string
	/** Set on a band: the committed monthly spend from which it applies. */
	readonly minMonthlySpend?: Money
}

/**
 * Rational is an exact fraction; prices per unit are rational so rating
 * rounds once, at the invoice line.
 */
export interface Rational {
	/** The numerator. */
	numerator?: string
	/** The denominator; never zero. */
	denominator?: string
}

/** The request of SetupPaymentMethod. */
export interface SetupPaymentMethodRequest {
	/** The billing account, `orgs/{org}/billing_accounts/default`. */
	name: string
}

/**
 * The response of SetupPaymentMethod: what the console needs to collect a
 * payment method with the provider's own client library.
 */
export interface SetupPaymentMethodResponse {
	/** The provider, `stripe`. */
	readonly provider?: string
	/** The provider's client secret for this setup; single use. */
	readonly clientSecret?: string
	/** The provider's publishable key for its client library. */
	readonly publishableKey?: string
}

/** The request of UpdateBillingAccount. */
export interface UpdateBillingAccountRequest {
	/** The billing account to update; `name` identifies it. */
	billingAccount: BillingAccount
	/** The fields to write; unset writes every populated field. */
	updateMask?: string
	/** Validate and return the result without writing anything. */
	validateOnly?: boolean
}

/** UsageLine is the usage of one project, meter, and dimension set. */
export interface UsageLine {
	/**
	 * The project that used it; empty for org-level usage (Runners, Network
	 * domains), whose attribution is a dimension such as `repo`.
	 */
	readonly project?: string
	/** The meter id. */
	readonly meter?: string
	/** The meter version. */
	readonly meterVersion?: number
	/** The dimensions. */
	readonly dimensions?: Record<string, string>
	/** The aggregated quantity, in the meter's base unit. */
	readonly quantity?: string
	/** How many usage events were aggregated. */
	readonly eventCount?: string
	/**
	 * The rated amount so far, before rounding to the invoice line; unset
	 * while the meter has no price for these dimensions.
	 */
	readonly amount?: Money
	/** The service that emits the meter. */
	readonly service?: string
	/**
	 * What the usage cost Sylphx to serve, for a class Sylphx runs but does
	 * not sell (an internal Sandboxes class rates at zero and shows its cost
	 * here); unset otherwise.
	 */
	readonly shadowCost?: Money
}

/**
 * A UsageReport is an org's usage summary for one billing period, rolled up
 * per project, meter, and dimensions, with how complete it is. The id is the
 * period, for example `orgs/{org}/usage_reports/2026-11`.
 */
export interface UsageReport {
	/** `orgs/{org}/usage_reports/{YYYY-MM}`. */
	name?: string
	/** `usr_<cell><ulid>`. */
	readonly uid?: string
	/** Resource metadata. */
	readonly meta?: common.ResourceMeta
	/** The start of the period. */
	readonly periodStartTime?: string
	/** The end of the period. */
	readonly periodEndTime?: string
	/** One line per project, meter, and dimension set. */
	readonly lines?: UsageLine[]
	/**
	 * The share of the period's usage that has reached Billing, from 0 to 1,
	 * from every emitter's watermark (metering.md §7.4).
	 */
	readonly completeness?: number
	/** The instant the report reflects. */
	readonly computeTime?: string
	/** The period's invoice, once one exists. */
	readonly invoice?: string
	/**
	 * Each emitting service's watermark: the time of the oldest usage it has
	 * not yet delivered (metering.md §7.4).
	 */
	readonly watermarks?: Record<string, string>
}

/** UsageRow is one bucket of a usage query. */
export interface UsageRow {
	/** The start of the bucket. */
	readonly startTime?: string
	/** The end of the bucket. */
	readonly endTime?: string
	/** The project, when grouped by project. */
	readonly project?: string
	/** The meter id. */
	readonly meter?: string
	/** The dimensions grouped on. */
	readonly dimensions?: Record<string, string>
	/** The aggregated quantity, in the meter's base unit. */
	readonly quantity?: string
	/** The service that emits the meter. */
	readonly service?: string
}

/** BillingAccountState is an org's payment standing. */
export type BillingAccountState = 'active' | 'past_due' | 'suspended' | (string & {})

/** BudgetLeaseState is the lifecycle state of a BudgetLease. */
export type BudgetLeaseState = 'active' | 'released' | 'expired' | 'settled' | 'refused' | (string & {})

/** InvoiceLineKind is what an invoice line charges for. */
export type InvoiceLineKind = 'fee' | 'usage' | 'late_usage' | 'credit' | 'proration' | (string & {})

/** InvoiceState is the lifecycle state of an Invoice. */
export type InvoiceState = 'draft' | 'open' | 'paid' | 'void' | 'uncollectible' | (string & {})

/** MeterAggregation is how a meter's quantities combine over a period. */
export type MeterAggregation = 'sum' | 'max' | 'last' | 'unique_count' | (string & {})

/** Overage is what happens when usage passes a plan's included quantity. */
export type Overage = 'deny' | 'bill' | 'bill_until_spend_limit' | (string & {})

/** UsageGranularity is the bucket width of a usage query. */
export type UsageGranularity = 'hour' | 'day' | 'period' | (string & {})

runtime.registerSchemas({
	'sylphx.billing.v1.BillingAccount': [
		['meta', 'meta', 'sylphx.common.v1.ResourceMeta'],
		['spec', 'spec', 'sylphx.billing.v1.BillingAccountSpec'],
		['status', 'status', 'sylphx.billing.v1.BillingAccountStatus'],
	],
	'sylphx.billing.v1.BillingAccountSpec': [
		['spendLimit', 'spend_limit', 'sylphx.billing.v1.Money'],
		['unlimitedSpend', 'unlimited_spend'],
		['billingEmail', 'billing_email'],
	],
	'sylphx.billing.v1.BillingAccountStatus': [
		['observedGeneration', 'observed_generation'],
		['conditions', 'conditions', 'sylphx.common.v1.Condition'],
		['planVersion', 'plan_version'],
		['currencyCode', 'currency_code'],
		['periodStartTime', 'period_start_time'],
		['periodEndTime', 'period_end_time'],
		['paymentMethodVerified', 'payment_method_verified'],
		['effectiveSpendLimit', 'effective_spend_limit', 'sylphx.billing.v1.Money'],
		['paymentMethod', 'payment_method'],
	],
	'sylphx.billing.v1.BudgetLease': [
		['meta', 'meta', 'sylphx.common.v1.ResourceMeta'],
		['grantedNanoUsd', 'granted_nano_usd'],
		['expireTime', 'expire_time'],
		['reportedDebitNanoUsd', 'reported_debit_nano_usd'],
		['settledDebitNanoUsd', 'settled_debit_nano_usd'],
		['meterVersion', 'meter_version'],
		['dimensions', 'dimensions', undefined, 'map'],
		['grantedQuantity', 'granted_quantity'],
		['reportedDebitQuantity', 'reported_debit_quantity'],
		['settledQuantity', 'settled_quantity'],
	],
	'sylphx.billing.v1.CreditNote': [
		['total', 'total', 'sylphx.billing.v1.Money'],
		['issueTime', 'issue_time'],
	],
	'sylphx.billing.v1.GetBillingAccountRequest': [],
	'sylphx.billing.v1.GetBudgetLeaseRequest': [],
	'sylphx.billing.v1.GetInvoiceRequest': [],
	'sylphx.billing.v1.GetMeterRequest': [],
	'sylphx.billing.v1.GetPlanRequest': [],
	'sylphx.billing.v1.GetUsageReportRequest': [],
	'sylphx.billing.v1.Invoice': [
		['meta', 'meta', 'sylphx.common.v1.ResourceMeta'],
		['currencyCode', 'currency_code'],
		['periodStartTime', 'period_start_time'],
		['periodEndTime', 'period_end_time'],
		['lines', 'lines', 'sylphx.billing.v1.InvoiceLine'],
		['subtotal', 'subtotal', 'sylphx.billing.v1.Money'],
		['tax', 'tax', 'sylphx.billing.v1.Money'],
		['total', 'total', 'sylphx.billing.v1.Money'],
		['amountDue', 'amount_due', 'sylphx.billing.v1.Money'],
		['amountPaid', 'amount_paid', 'sylphx.billing.v1.Money'],
		['finalizeTime', 'finalize_time'],
		['dueTime', 'due_time'],
		['paidTime', 'paid_time'],
		['creditNotes', 'credit_notes', 'sylphx.billing.v1.CreditNote'],
	],
	'sylphx.billing.v1.InvoiceLine': [
		['meterVersion', 'meter_version'],
		['dimensions', 'dimensions', undefined, 'map'],
		['unitAmountMinor', 'unit_amount_minor', 'sylphx.billing.v1.Rational'],
		['amount', 'amount', 'sylphx.billing.v1.Money'],
	],
	'sylphx.billing.v1.ListBillingAccountsRequest': [
		['pageSize', 'page_size'],
		['pageToken', 'page_token'],
		['orderBy', 'order_by'],
	],
	'sylphx.billing.v1.ListBillingAccountsResponse': [
		['billingAccounts', 'billing_accounts', 'sylphx.billing.v1.BillingAccount'],
		['nextPageToken', 'next_page_token'],
	],
	'sylphx.billing.v1.ListBudgetLeasesRequest': [
		['pageSize', 'page_size'],
		['pageToken', 'page_token'],
		['orderBy', 'order_by'],
	],
	'sylphx.billing.v1.ListBudgetLeasesResponse': [
		['budgetLeases', 'budget_leases', 'sylphx.billing.v1.BudgetLease'],
		['nextPageToken', 'next_page_token'],
	],
	'sylphx.billing.v1.ListInvoicesRequest': [
		['pageSize', 'page_size'],
		['pageToken', 'page_token'],
		['orderBy', 'order_by'],
	],
	'sylphx.billing.v1.ListInvoicesResponse': [
		['invoices', 'invoices', 'sylphx.billing.v1.Invoice'],
		['nextPageToken', 'next_page_token'],
	],
	'sylphx.billing.v1.ListMetersRequest': [
		['pageSize', 'page_size'],
		['pageToken', 'page_token'],
		['orderBy', 'order_by'],
	],
	'sylphx.billing.v1.ListMetersResponse': [
		['meters', 'meters', 'sylphx.billing.v1.Meter'],
		['nextPageToken', 'next_page_token'],
	],
	'sylphx.billing.v1.ListPlansRequest': [
		['pageSize', 'page_size'],
		['pageToken', 'page_token'],
		['orderBy', 'order_by'],
	],
	'sylphx.billing.v1.ListPlansResponse': [
		['plans', 'plans', 'sylphx.billing.v1.Plan'],
		['nextPageToken', 'next_page_token'],
	],
	'sylphx.billing.v1.ListUsageReportsRequest': [
		['pageSize', 'page_size'],
		['pageToken', 'page_token'],
		['orderBy', 'order_by'],
	],
	'sylphx.billing.v1.ListUsageReportsResponse': [
		['usageReports', 'usage_reports', 'sylphx.billing.v1.UsageReport'],
		['nextPageToken', 'next_page_token'],
	],
	'sylphx.billing.v1.Meter': [
		['meta', 'meta', 'sylphx.common.v1.ResourceMeta'],
		['currentVersion', 'current_version'],
		['versions', 'versions', 'sylphx.billing.v1.MeterVersion'],
	],
	'sylphx.billing.v1.MeterDimension': [],
	'sylphx.billing.v1.MeterPrice': [
		['meterVersion', 'meter_version'],
		['dimensionMatch', 'dimension_match', undefined, 'map'],
		['tiers', 'tiers', 'sylphx.billing.v1.PriceTier'],
	],
	'sylphx.billing.v1.MeterVersion': [
		['dimensions', 'dimensions', 'sylphx.billing.v1.MeterDimension'],
		['hardSpend', 'hard_spend'],
		['valueScale', 'value_scale'],
		['effectiveTime', 'effective_time'],
	],
	'sylphx.billing.v1.Money': [
		['currencyCode', 'currency_code'],
		['unitsMinor', 'units_minor'],
	],
	'sylphx.billing.v1.Plan': [
		['meta', 'meta', 'sylphx.common.v1.ResourceMeta'],
		['currentVersion', 'current_version'],
		['versions', 'versions', 'sylphx.billing.v1.PlanVersion'],
	],
	'sylphx.billing.v1.PlanVersion': [
		['effectiveTime', 'effective_time'],
		['fee', 'fee', 'sylphx.billing.v1.Money'],
		['includedCredit', 'included_credit', 'sylphx.billing.v1.Money'],
		['paymentMethodRequired', 'payment_method_required'],
		['meterPrices', 'meter_prices', 'sylphx.billing.v1.MeterPrice'],
		['resourceLimits', 'resource_limits', undefined, 'map'],
		['rateLimits', 'rate_limits', undefined, 'map'],
		['rateLimitPolicies', 'rate_limit_policies', 'sylphx.billing.v1.RateLimitPolicy'],
	],
	'sylphx.billing.v1.PriceTier': [
		['upperBound', 'upper_bound'],
		['unitAmountMinor', 'unit_amount_minor', 'sylphx.billing.v1.Rational'],
	],
	'sylphx.billing.v1.QueryUsageReportsRequest': [
		['startTime', 'start_time'],
		['endTime', 'end_time'],
		['groupProjects', 'group_projects'],
		['groupDimensions', 'group_dimensions'],
	],
	'sylphx.billing.v1.QueryUsageReportsResponse': [
		['rows', 'rows', 'sylphx.billing.v1.UsageRow'],
		['computeTime', 'compute_time'],
		['watermarks', 'watermarks', undefined, 'map'],
	],
	'sylphx.billing.v1.RateLimitPolicy': [
		['rateClass', 'rate_class'],
		['requestsPerSecond', 'requests_per_second'],
		['minMonthlySpend', 'min_monthly_spend', 'sylphx.billing.v1.Money'],
	],
	'sylphx.billing.v1.Rational': [],
	'sylphx.billing.v1.SetupPaymentMethodRequest': [],
	'sylphx.billing.v1.SetupPaymentMethodResponse': [
		['clientSecret', 'client_secret'],
		['publishableKey', 'publishable_key'],
	],
	'sylphx.billing.v1.UpdateBillingAccountRequest': [
		['billingAccount', 'billing_account', 'sylphx.billing.v1.BillingAccount'],
		['updateMask', 'update_mask'],
		['validateOnly', 'validate_only'],
	],
	'sylphx.billing.v1.UsageLine': [
		['meterVersion', 'meter_version'],
		['dimensions', 'dimensions', undefined, 'map'],
		['eventCount', 'event_count'],
		['amount', 'amount', 'sylphx.billing.v1.Money'],
		['shadowCost', 'shadow_cost', 'sylphx.billing.v1.Money'],
	],
	'sylphx.billing.v1.UsageReport': [
		['meta', 'meta', 'sylphx.common.v1.ResourceMeta'],
		['periodStartTime', 'period_start_time'],
		['periodEndTime', 'period_end_time'],
		['lines', 'lines', 'sylphx.billing.v1.UsageLine'],
		['computeTime', 'compute_time'],
		['watermarks', 'watermarks', undefined, 'map'],
	],
	'sylphx.billing.v1.UsageRow': [
		['startTime', 'start_time'],
		['endTime', 'end_time'],
		['dimensions', 'dimensions', undefined, 'map'],
	],
})

/**
 * BillingService is Kernel Billing (docs/kernel/billing/vision.md,
 * metering.md): the meter and plan catalog, each org's billing account and
 * plan, its invoices, usage, and budget leases. Usage arrives through each
 * service's spool, never through this API; no request path calls Billing.
 *
 * Namespace of Sylphx Billing on `Sylphx`.
 */
export class BillingApi {
	/** The `meters` collection. */
	readonly meters: MetersCollection
	/** The `plans` collection. */
	readonly plans: PlansCollection
	/** The `billing_accounts` collection. */
	readonly billingAccounts: BillingAccountsCollection
	/** The `invoices` collection. */
	readonly invoices: InvoicesCollection
	/** The `usage_reports` collection. */
	readonly usageReports: UsageReportsCollection
	/** The `budget_leases` collection. */
	readonly budgetLeases: BudgetLeasesCollection

	constructor(client: runtime.Client) {
		this.meters = new MetersCollection(client)
		this.plans = new PlansCollection(client)
		this.billingAccounts = new BillingAccountsCollection(client)
		this.invoices = new InvoicesCollection(client)
		this.usageReports = new UsageReportsCollection(client)
		this.budgetLeases = new BudgetLeasesCollection(client)
	}
}

/** `meters` of Sylphx Billing: Resource type `billing.sylphx.com/Meter`. */
export class MetersCollection {
	private readonly client: runtime.Client

	constructor(client: runtime.Client) {
		this.client = client
	}

	/**
	 * Gets a meter.
	 *
	 * `GET /v1/{name=meters/*}` · permission `billing:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
	 */
	async get(request: GetMeterRequest): Promise<Meter> {
		return this.client.call<Meter>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.name, 'meters/*', 'name')}`,
			responseType: 'sylphx.billing.v1.Meter',
			mutation: false,
		})
	}

	/**
	 * Lists meters. Anonymous-readable: the pricing page renders from it.
	 *
	 * `GET /v1/meters` · permission `billing:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
	 */
	async list(request: ListMetersRequest): Promise<ListMetersResponse> {
		return this.client.call<ListMetersResponse>({
			method: 'GET',
			path: `/v1/meters`,
			query: { page_size: request.pageSize, page_token: request.pageToken, filter: request.filter, order_by: request.orderBy },
			responseType: 'sylphx.billing.v1.ListMetersResponse',
			mutation: false,
		})
	}

	/** Every item of every page of `list`. */
	async *listAll(request: ListMetersRequest): AsyncGenerator<Meter> {
		let next: ListMetersRequest = request
		for (;;) {
			const page = await this.list(next)
			yield* page.meters ?? []
			if (page.nextPageToken === undefined || page.nextPageToken === '') return
			next = { ...request, pageToken: page.nextPageToken }
		}
	}
}

/** `plans` of Sylphx Billing: Resource type `billing.sylphx.com/Plan`. */
export class PlansCollection {
	private readonly client: runtime.Client

	constructor(client: runtime.Client) {
		this.client = client
	}

	/**
	 * Gets a plan.
	 *
	 * `GET /v1/{name=plans/*}` · permission `billing:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
	 */
	async get(request: GetPlanRequest): Promise<Plan> {
		return this.client.call<Plan>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.name, 'plans/*', 'name')}`,
			responseType: 'sylphx.billing.v1.Plan',
			mutation: false,
		})
	}

	/**
	 * Lists the plans the caller can see. Anonymous-readable: the pricing page renders from it.
	 *
	 * `GET /v1/plans` · permission `billing:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
	 */
	async list(request: ListPlansRequest): Promise<ListPlansResponse> {
		return this.client.call<ListPlansResponse>({
			method: 'GET',
			path: `/v1/plans`,
			query: { page_size: request.pageSize, page_token: request.pageToken, filter: request.filter, order_by: request.orderBy },
			responseType: 'sylphx.billing.v1.ListPlansResponse',
			mutation: false,
		})
	}

	/** Every item of every page of `list`. */
	async *listAll(request: ListPlansRequest): AsyncGenerator<Plan> {
		let next: ListPlansRequest = request
		for (;;) {
			const page = await this.list(next)
			yield* page.plans ?? []
			if (page.nextPageToken === undefined || page.nextPageToken === '') return
			next = { ...request, pageToken: page.nextPageToken }
		}
	}
}

/** `billing_accounts` of Sylphx Billing: Resource type `billing.sylphx.com/BillingAccount`. */
export class BillingAccountsCollection {
	private readonly client: runtime.Client

	constructor(client: runtime.Client) {
		this.client = client
	}

	/**
	 * Gets a billing account.
	 *
	 * `GET /v1/{name=orgs/*\/billing_accounts/*}` · permission `billing:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
	 */
	async get(request: GetBillingAccountRequest): Promise<BillingAccount> {
		return this.client.call<BillingAccount>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/billing_accounts/*', 'name')}`,
			responseType: 'sylphx.billing.v1.BillingAccount',
			mutation: false,
		})
	}

	/**
	 * Lists an org's billing accounts: exactly one, `default`.
	 *
	 * `GET /v1/{parent=orgs/*}/billing_accounts` · permission `billing:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
	 */
	async list(request: ListBillingAccountsRequest): Promise<ListBillingAccountsResponse> {
		return this.client.call<ListBillingAccountsResponse>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*', 'parent')}/billing_accounts`,
			query: { page_size: request.pageSize, page_token: request.pageToken, filter: request.filter, order_by: request.orderBy },
			responseType: 'sylphx.billing.v1.ListBillingAccountsResponse',
			mutation: false,
		})
	}

	/** Every item of every page of `list`. */
	async *listAll(request: ListBillingAccountsRequest): AsyncGenerator<BillingAccount> {
		let next: ListBillingAccountsRequest = request
		for (;;) {
			const page = await this.list(next)
			yield* page.billingAccounts ?? []
			if (page.nextPageToken === undefined || page.nextPageToken === '') return
			next = { ...request, pageToken: page.nextPageToken }
		}
	}

	/**
	 * Updates a billing account: changes plan, spend limit, or billing email.
	 *
	 * `PATCH /v1/{billing_account.name=orgs/*\/billing_accounts/*}` · permission `billing:admin` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
	 */
	async update(request: UpdateBillingAccountRequest): Promise<BillingAccount> {
		return this.client.call<BillingAccount>({
			method: 'PATCH',
			path: `/v1/${runtime.pathParam(request.billingAccount?.name, 'orgs/*/billing_accounts/*', 'billing_account.name')}`,
			query: { update_mask: request.updateMask, validate_only: request.validateOnly },
			body: request.billingAccount ?? {},
			bodyType: 'sylphx.billing.v1.BillingAccount',
			responseType: 'sylphx.billing.v1.BillingAccount',
			mutation: true,
		})
	}

	/**
	 * Starts saving a payment method for the org: returns a client secret the
	 * console confirms with Stripe.js, so card data never reaches Sylphx. The
	 * saved method becomes the account's default and is charged off-session
	 * for each finalized invoice.
	 *
	 * `POST /v1/{name=orgs/*\/billing_accounts/*}:setupPaymentMethod` · permission `billing:admin` · effect `write`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `UNAVAILABLE`.
	 */
	async setupPaymentMethod(request: SetupPaymentMethodRequest): Promise<SetupPaymentMethodResponse> {
		return this.client.call<SetupPaymentMethodResponse>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/billing_accounts/*', 'name')}:setupPaymentMethod`,
			body: runtime.omit(request, ['name']),
			bodyType: 'sylphx.billing.v1.SetupPaymentMethodRequest',
			responseType: 'sylphx.billing.v1.SetupPaymentMethodResponse',
			mutation: true,
		})
	}
}

/** `invoices` of Sylphx Billing: Resource type `billing.sylphx.com/Invoice`. */
export class InvoicesCollection {
	private readonly client: runtime.Client

	constructor(client: runtime.Client) {
		this.client = client
	}

	/**
	 * Gets an invoice.
	 *
	 * `GET /v1/{name=orgs/*\/invoices/*}` · permission `billing:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
	 */
	async get(request: GetInvoiceRequest): Promise<Invoice> {
		return this.client.call<Invoice>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/invoices/*', 'name')}`,
			responseType: 'sylphx.billing.v1.Invoice',
			mutation: false,
		})
	}

	/**
	 * Lists an org's invoices.
	 *
	 * `GET /v1/{parent=orgs/*}/invoices` · permission `billing:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
	 */
	async list(request: ListInvoicesRequest): Promise<ListInvoicesResponse> {
		return this.client.call<ListInvoicesResponse>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*', 'parent')}/invoices`,
			query: { page_size: request.pageSize, page_token: request.pageToken, filter: request.filter, order_by: request.orderBy },
			responseType: 'sylphx.billing.v1.ListInvoicesResponse',
			mutation: false,
		})
	}

	/** Every item of every page of `list`. */
	async *listAll(request: ListInvoicesRequest): AsyncGenerator<Invoice> {
		let next: ListInvoicesRequest = request
		for (;;) {
			const page = await this.list(next)
			yield* page.invoices ?? []
			if (page.nextPageToken === undefined || page.nextPageToken === '') return
			next = { ...request, pageToken: page.nextPageToken }
		}
	}
}

/** `usage_reports` of Sylphx Billing: Resource type `billing.sylphx.com/UsageReport`. */
export class UsageReportsCollection {
	private readonly client: runtime.Client

	constructor(client: runtime.Client) {
		this.client = client
	}

	/**
	 * Gets an usage report.
	 *
	 * `GET /v1/{name=orgs/*\/usage_reports/*}` · permission `billing:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
	 */
	async get(request: GetUsageReportRequest): Promise<UsageReport> {
		return this.client.call<UsageReport>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/usage_reports/*', 'name')}`,
			responseType: 'sylphx.billing.v1.UsageReport',
			mutation: false,
		})
	}

	/**
	 * Lists an org's usage reports, one per billing period.
	 *
	 * `GET /v1/{parent=orgs/*}/usage_reports` · permission `billing:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
	 */
	async list(request: ListUsageReportsRequest): Promise<ListUsageReportsResponse> {
		return this.client.call<ListUsageReportsResponse>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*', 'parent')}/usage_reports`,
			query: { page_size: request.pageSize, page_token: request.pageToken, filter: request.filter, order_by: request.orderBy },
			responseType: 'sylphx.billing.v1.ListUsageReportsResponse',
			mutation: false,
		})
	}

	/** Every item of every page of `list`. */
	async *listAll(request: ListUsageReportsRequest): AsyncGenerator<UsageReport> {
		let next: ListUsageReportsRequest = request
		for (;;) {
			const page = await this.list(next)
			yield* page.usageReports ?? []
			if (page.nextPageToken === undefined || page.nextPageToken === '') return
			next = { ...request, pageToken: page.nextPageToken }
		}
	}

	/**
	 * Queries usage over any time range, bucketed and grouped: the usage
	 * summary the console charts. Reads rollups; never raw events.
	 *
	 * `POST /v1/{parent=orgs/*}/usage_reports:query` · permission `billing:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`.
	 */
	async query(request: QueryUsageReportsRequest): Promise<QueryUsageReportsResponse> {
		return this.client.call<QueryUsageReportsResponse>({
			method: 'POST',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*', 'parent')}/usage_reports:query`,
			body: runtime.omit(request, ['parent']),
			bodyType: 'sylphx.billing.v1.QueryUsageReportsRequest',
			responseType: 'sylphx.billing.v1.QueryUsageReportsResponse',
			mutation: true,
		})
	}
}

/** `budget_leases` of Sylphx Billing: Resource type `billing.sylphx.com/BudgetLease`. */
export class BudgetLeasesCollection {
	private readonly client: runtime.Client

	constructor(client: runtime.Client) {
		this.client = client
	}

	/**
	 * Gets a budget lease.
	 *
	 * `GET /v1/{name=orgs/*\/budget_leases/*}` · permission `billing:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
	 */
	async get(request: GetBudgetLeaseRequest): Promise<BudgetLease> {
		return this.client.call<BudgetLease>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.name, 'orgs/*/budget_leases/*', 'name')}`,
			responseType: 'sylphx.billing.v1.BudgetLease',
			mutation: false,
		})
	}

	/**
	 * Lists an org's budget leases.
	 *
	 * `GET /v1/{parent=orgs/*}/budget_leases` · permission `billing:read` · effect `read`
	 *
	 * Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
	 */
	async list(request: ListBudgetLeasesRequest): Promise<ListBudgetLeasesResponse> {
		return this.client.call<ListBudgetLeasesResponse>({
			method: 'GET',
			path: `/v1/${runtime.pathParam(request.parent, 'orgs/*', 'parent')}/budget_leases`,
			query: { page_size: request.pageSize, page_token: request.pageToken, filter: request.filter, order_by: request.orderBy },
			responseType: 'sylphx.billing.v1.ListBudgetLeasesResponse',
			mutation: false,
		})
	}

	/** Every item of every page of `list`. */
	async *listAll(request: ListBudgetLeasesRequest): AsyncGenerator<BudgetLease> {
		let next: ListBudgetLeasesRequest = request
		for (;;) {
			const page = await this.list(next)
			yield* page.budgetLeases ?? []
			if (page.nextPageToken === undefined || page.nextPageToken === '') return
			next = { ...request, pageToken: page.nextPageToken }
		}
	}
}
