// @generated by sylphx-gen 0.1.0 from contracts@478c308ceb6a738b4ac0675760ae37b0502b002be414f1c7954a3baf04a4d32d. Do not edit.
//! `sylphx.assets.v1`.

#![allow(clippy::all)]

/// The request of ApproveVariant.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ApproveVariantRequest {
    /// The name of the asset.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// The content hash of the variant, 64 lowercase hex characters.
    ///
    /// Field behavior: `required`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "contentHash"
    )]
    pub content_hash: String,
}

/// An Asset is one declared asset and its generated variants. Its id is the
/// 16-hex logical key of the recipe, so the same recipe is always the same
/// Asset. There is no create, update or delete: the key is immutable, and
/// `:generate` writes the record.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct Asset {
    /// `orgs/{org}/projects/{project}/envs/{env}/assets/{asset}`, where `{asset}`
    /// is the 16-hex logical key.
    ///
    /// Field behavior: `identifier`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// `ast_<cell><ulid>`; never reused.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub uid: String,
    /// Resource metadata.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<crate::common::ResourceMeta>,
    /// The logical key: 16 lowercase hex characters computed from the recipe.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub key: String,
    /// What kind of asset this is.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<AssetKind>,
    /// The recipe the asset was declared with.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recipe: Option<AssetRecipe>,
    /// The exact text the key is the hash of.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub canonical: String,
    /// How many variants the recipe asks for.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "variantsWanted"
    )]
    pub variants_wanted: i32,
    /// Where the asset is in its life.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<AssetState>,
    /// Ready, Reconciling, Stalled.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub conditions: Vec<crate::common::Condition>,
    /// The seed of the asset, a decimal integer as a string.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub seed: String,
    /// The stored variants, ordered by slot.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub variants: Vec<Variant>,
    /// When the asset was first generated.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "createTime"
    )]
    pub create_time: String,
    /// When the asset last changed.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "updateTime"
    )]
    pub update_time: String,
}

/// An AssetRecipe is what the code declares for one asset. The logical key is
/// derived from it.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct AssetRecipe {
    /// What kind of asset to make.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<AssetKind>,
    /// What to make, at most 8000 bytes. Empty only for `ASSET_KIND_CHARACTER`.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub prompt: String,
    /// The locale of the asset, a BCP 47 tag; empty for images.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub locale: String,
    /// The character this asset shows; only for `ASSET_KIND_CHARACTER`, encoded
    /// in the canonical text as `id=`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "characterId"
    )]
    pub character_id: String,
    /// Kind-specific parameters in canonical text form, such as `"2"`,
    /// `"1024x768"`, `"true"` or a 16-hex key. At most 16 pairs; keys are
    /// `[a-z_]` up to 32 characters, values up to 256 characters.
    #[serde(default, skip_serializing_if = "std::collections::BTreeMap::is_empty")]
    pub params: std::collections::BTreeMap<String, String>,
    /// The key the caller computed, 16 lowercase hex characters. When it differs
    /// from the server's, the call is refused with `INVALID_FIELD` and the
    /// problem carries the server's canonical text, which catches encoder drift.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub key: String,
}

/// An AssetSummary is the progress of one asset in a `:generate` call.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct AssetSummary {
    /// The logical key.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub key: String,
    /// The asset's resource name.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// Where the asset is in its life.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<AssetState>,
    /// How many variants are stored.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "variantsReady"
    )]
    pub variants_ready: i32,
    /// How many variants the recipe asks for.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "variantsWanted"
    )]
    pub variants_wanted: i32,
}

/// The request of ExportAssets.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ExportAssetsRequest {
    /// The environment to export from.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub parent: String,
    /// At most this many items; default 100, clamped to 1000.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageSize"
    )]
    pub page_size: i32,
    /// `next_page_token` of the previous page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageToken"
    )]
    pub page_token: String,
    /// AIP-160 filter, limited to `kind` and `review_state`; for example
    /// `kind = ASSET_KIND_IMAGE`. Without a `review_state` term, rejected and
    /// retired variants are left out.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub filter: String,
}

/// The response of ExportAssets.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ExportAssetsResponse {
    /// The page, oldest variant first.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub items: Vec<ExportedAsset>,
    /// The token of the next page; empty on the last page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "nextPageToken"
    )]
    pub next_page_token: String,
    /// On the last page only: `sha256:` and the hex SHA-256 of the `content_hash`
    /// of every item the filter matches (one line per item, sorted, each ended
    /// by a line feed). A client that downloaded every page recomputes it from
    /// the items it holds.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "manifestDigest"
    )]
    pub manifest_digest: String,
}

/// An ExportedAsset is one variant in the flat export manifest. Download the
/// bytes from `url` and check them against `content_hash`.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ExportedAsset {
    /// The logical key of the asset the variant belongs to.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "assetKey"
    )]
    pub asset_key: String,
    /// The asset's immutable uid.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "assetUid"
    )]
    pub asset_uid: String,
    /// What the asset is.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<AssetKind>,
    /// SHA-256 of the file, 64 lowercase hex characters.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "contentHash"
    )]
    pub content_hash: String,
    /// The file extension, without the dot.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub ext: String,
    /// The IANA media type.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "mediaType"
    )]
    pub media_type: String,
    /// The file size in bytes.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        with = "crate::runtime::int64"
    )]
    pub bytes: i64,
    /// Pixel width.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub width: i32,
    /// Pixel height.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub height: i32,
    /// The public, content-addressed, immutable download URL.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub url: String,
    /// The human review of the variant.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "reviewState"
    )]
    pub review_state: Option<ReviewState>,
    /// Who approved the variant; empty until approved.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "approvedBy"
    )]
    pub approved_by: String,
    /// The recorded model id; informational.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub model: String,
    /// The seed, an unsigned decimal string.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub seed: String,
}

/// The request of GenerateAssets.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct GenerateAssetsRequest {
    /// The environment to generate in.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub parent: String,
    /// The recipes the code declares; 1 to 1000.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub recipes: Vec<AssetRecipe>,
    /// Validate the recipes and return the counts without writing or
    /// generating anything.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "validateOnly"
    )]
    pub validate_only: bool,
}

/// The response of GenerateAssets.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct GenerateAssetsResponse {
    /// Assets new in this call.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub created: i32,
    /// Assets that already existed with the same key.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub unchanged: i32,
    /// Variants stored by this call.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub generated: i32,
    /// Variants still to generate; call again until it is 0.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub pending: i32,
    /// Assets whose slots still fail after their attempts.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub failed: i32,
    /// Assets refused, for example by moderation.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub refused: i32,
    /// Assets of a kind the service does not generate yet.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub unsupported: i32,
    /// One summary per recipe, in the order sent.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub assets: Vec<AssetSummary>,
    /// What this call used.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage: Option<Usage>,
}

/// The request of GetAsset.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct GetAssetRequest {
    /// The name of the asset to get.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
}

/// The request of ListAssets.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ListAssetsRequest {
    /// The parent to list in.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub parent: String,
    /// At most this many; default 50, clamped to 1000.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageSize"
    )]
    pub page_size: i32,
    /// `next_page_token` of the previous page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageToken"
    )]
    pub page_token: String,
    /// AIP-160 filter, limited to `kind`, `state`, and `review_state`; for
    /// example `kind = ASSET_KIND_IMAGE AND state = ASSET_STATE_READY`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub filter: String,
}

/// The response of ListAssets.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ListAssetsResponse {
    /// The page.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub assets: Vec<Asset>,
    /// The token of the next page; empty on the last page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "nextPageToken"
    )]
    pub next_page_token: String,
}

/// The request of LockAssets.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct LockAssetsRequest {
    /// The environment to read from.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub parent: String,
    /// The logical keys the code declares, 1 to 5000, each 16 lowercase hex
    /// characters. The lock holds only these, so a removed recipe drops out.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub keys: Vec<String>,
}

/// The response of LockAssets.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct LockAssetsResponse {
    /// The lock entries of the keys that have a complete record, sorted by key.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub entries: Vec<LockEntry>,
    /// Keys with no record.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub missing: Vec<String>,
    /// Keys whose stored variants are fewer than wanted, or whose state is
    /// neither ready nor approved.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub incomplete: Vec<String>,
    /// The canonical `assets.lock` text, version 1.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub content: String,
}

/// A LockEntry is one asset as it appears in `assets.lock`.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct LockEntry {
    /// The logical key.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub key: String,
    /// What kind of asset this is.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<AssetKind>,
    /// The seed, a decimal integer as a string.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub seed: String,
    /// The variants, ordered by slot.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub variants: Vec<LockVariant>,
}

/// A LockVariant is one variant as it appears in `assets.lock`. Its URL is the
/// lock's base URL, the content hash, a dot, and the extension.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct LockVariant {
    /// The SHA-256 of the file's bytes, 64 lowercase hex characters.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "contentHash"
    )]
    pub content_hash: String,
    /// The file's extension without the dot.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub ext: String,
    /// The file's media type.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "mediaType"
    )]
    pub media_type: String,
    /// Width in pixels.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub width: i32,
    /// Height in pixels.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub height: i32,
    /// The file's size in bytes.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        with = "crate::runtime::int64"
    )]
    pub bytes: i64,
    /// The model that made this variant.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub model: String,
    /// The principal that approved the variant; empty when unreviewed.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "approvedBy"
    )]
    pub approved_by: String,
}

/// A QaFinding is one problem QA found in a variant.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct QaFinding {
    /// The check that found it.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub check: Option<QaCheck>,
    /// How serious it is.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub severity: Option<QaSeverity>,
    /// What is wrong.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub message: String,
}

/// The request of RejectVariant.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct RejectVariantRequest {
    /// The name of the asset.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// The content hash of the variant, 64 lowercase hex characters.
    ///
    /// Field behavior: `required`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "contentHash"
    )]
    pub content_hash: String,
}

/// The request of RetireVariant.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct RetireVariantRequest {
    /// The name of the asset.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// The content hash of the variant, 64 lowercase hex characters.
    ///
    /// Field behavior: `required`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "contentHash"
    )]
    pub content_hash: String,
    /// Why the variant is retired, at most 500 characters.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub reason: String,
}

/// Usage is what one call consumed.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct Usage {
    /// Images stored by this call, the billed quantity.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        with = "crate::runtime::int64"
    )]
    pub images: i64,
}

/// A Variant is one stored result for an asset: a file addressed by the hash of
/// its bytes. A variant is immutable; only its review changes.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct Variant {
    /// The slot the variant fills, from 0.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub slot: i32,
    /// The SHA-256 of the file's bytes, 64 lowercase hex characters.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "contentHash"
    )]
    pub content_hash: String,
    /// The immutable public URL: the project's base URL, then the content hash
    /// and extension.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub url: String,
    /// The file's media type, such as `image/png`.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "mediaType"
    )]
    pub media_type: String,
    /// The file's extension without the dot, such as `png`.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub ext: String,
    /// Width in pixels.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub width: i32,
    /// Height in pixels.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub height: i32,
    /// The file's size in bytes.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        with = "crate::runtime::int64"
    )]
    pub bytes: i64,
    /// The model that made this variant.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub model: String,
    /// The seed this variant was made with, a decimal integer as a string.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub seed: String,
    /// The human review of the variant.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "reviewState"
    )]
    pub review_state: Option<ReviewState>,
    /// The result of QA on the file.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "qaState")]
    pub qa_state: Option<QaState>,
    /// What QA found.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub findings: Vec<QaFinding>,
    /// Whether the file carries content credentials.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "contentCredentials"
    )]
    pub content_credentials: bool,
    /// The principal that approved the variant; empty until it is approved.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "approvedBy"
    )]
    pub approved_by: String,
    /// When the variant was stored.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "createTime"
    )]
    pub create_time: String,
}

/// AssetKind is what an asset is.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum AssetKind {
    /// A still image.
    Image,
    /// A sound effect.
    Sfx,
    /// A piece of music.
    Music,
    /// A video clip.
    Video,
    /// A character, the reference other assets show.
    Character,
    /// A spoken voice line.
    Voice,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl AssetKind {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Image => "image",
            Self::Sfx => "sfx",
            Self::Music => "music",
            Self::Video => "video",
            Self::Character => "character",
            Self::Voice => "voice",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "image" => Self::Image,
            "sfx" => Self::Sfx,
            "music" => Self::Music,
            "video" => Self::Video,
            "character" => Self::Character,
            "voice" => Self::Voice,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for AssetKind {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for AssetKind {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for AssetKind {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

/// AssetState is where an asset is in its life.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum AssetState {
    /// Variants are still to generate.
    Pending,
    /// Every wanted variant is stored and none is approved yet.
    Ready,
    /// Every wanted variant is stored and approved.
    Approved,
    /// A slot still fails after its attempts; change the prompt.
    Failed,
    /// The recipe was refused, for example by moderation.
    Refused,
    /// The service does not generate this kind yet; nothing is billed.
    Unsupported,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl AssetState {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Pending => "pending",
            Self::Ready => "ready",
            Self::Approved => "approved",
            Self::Failed => "failed",
            Self::Refused => "refused",
            Self::Unsupported => "unsupported",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "pending" => Self::Pending,
            "ready" => Self::Ready,
            "approved" => Self::Approved,
            "failed" => Self::Failed,
            "refused" => Self::Refused,
            "unsupported" => Self::Unsupported,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for AssetState {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for AssetState {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for AssetState {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

/// QaCheck is a QA check.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum QaCheck {
    /// The file is not a valid file of the expected format.
    Format,
    /// The file's dimensions are outside what the recipe asks for.
    Size,
    /// The content credentials are missing or do not verify.
    ContentCredentials,
    /// The content was flagged by moderation.
    Moderation,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl QaCheck {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Format => "format",
            Self::Size => "size",
            Self::ContentCredentials => "content_credentials",
            Self::Moderation => "moderation",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "format" => Self::Format,
            "size" => Self::Size,
            "content_credentials" => Self::ContentCredentials,
            "moderation" => Self::Moderation,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for QaCheck {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for QaCheck {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for QaCheck {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

/// QaSeverity is how serious a QA finding is.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum QaSeverity {
    /// The variant fails QA.
    Error,
    /// The variant is still served.
    Warning,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl QaSeverity {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Error => "error",
            Self::Warning => "warning",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "error" => Self::Error,
            "warning" => Self::Warning,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for QaSeverity {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for QaSeverity {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for QaSeverity {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

/// QaState is the QA result of a variant.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum QaState {
    /// No findings.
    Passed,
    /// Warnings only; the variant is served.
    Warning,
    /// At least one error.
    Failed,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl QaState {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Passed => "passed",
            Self::Warning => "warning",
            Self::Failed => "failed",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "passed" => Self::Passed,
            "warning" => Self::Warning,
            "failed" => Self::Failed,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for QaState {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for QaState {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for QaState {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

/// ReviewState is the human review of a variant.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum ReviewState {
    /// Nobody has reviewed the variant.
    Unreviewed,
    /// A person approved the variant.
    Approved,
    /// A person rejected the variant; its slot is generated again and its URL
    /// keeps serving.
    Rejected,
    /// A person retired the variant; its URL answers 404 and its slot is
    /// generated again.
    Retired,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl ReviewState {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Unreviewed => "unreviewed",
            Self::Approved => "approved",
            Self::Rejected => "rejected",
            Self::Retired => "retired",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "unreviewed" => Self::Unreviewed,
            "approved" => Self::Approved,
            "rejected" => Self::Rejected,
            "retired" => Self::Retired,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for ReviewState {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for ReviewState {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for ReviewState {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

impl<T: crate::runtime::Transport> crate::runtime::Client<T> {
    /// Sylphx Generated Assets (`preview`).
    pub fn assets(&self) -> AssetsApi<'_, T> {
        AssetsApi { client: self }
    }
}

/// AssetsService is Sylphx Generated Assets: declare images in code, generate
/// them once, lock them, and serve them from a CDN by content hash. An Asset
/// holds a recipe and its variants; `:generate` makes what is missing, and
/// `:lock` returns the `assets.lock` text a build commits. Generation happens
/// only in these calls, never at build or run time.
///
/// Namespace of Sylphx Generated Assets on the client.
pub struct AssetsApi<'a, T> {
    client: &'a crate::runtime::Client<T>,
}

impl<'a, T: crate::runtime::Transport> AssetsApi<'a, T> {
    /// The `assets` collection.
    pub fn assets(&self) -> AssetsCollection<'a, T> {
        AssetsCollection {
            client: self.client,
        }
    }
}

/// `assets` of Sylphx Generated Assets: Resource type `assets.sylphx.com/Asset`.
pub struct AssetsCollection<'a, T> {
    client: &'a crate::runtime::Client<T>,
}

impl<'a, T: crate::runtime::Transport> AssetsCollection<'a, T> {
    /// Gets an asset.
    ///
    /// `GET /v1/{name=orgs/*/projects/*/envs/*/assets/*}` · permission `assets:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
    pub async fn get(&self, request: GetAssetRequest) -> Result<Asset, crate::runtime::Error> {
        let path = format!(
            "/v1/{}",
            crate::runtime::path_param(&request.name, "orgs/*/projects/*/envs/*/assets/*", "name")?
        );
        let query = crate::runtime::Query::default();
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Lists assets. The filter is limited to `kind`, `state`, and
    /// `review_state`.
    ///
    /// `GET /v1/{parent=orgs/*/projects/*/envs/*}/assets` · permission `assets:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
    pub async fn list(
        &self,
        request: ListAssetsRequest,
    ) -> Result<ListAssetsResponse, crate::runtime::Error> {
        let path = format!(
            "/v1/{}/assets",
            crate::runtime::path_param(&request.parent, "orgs/*/projects/*/envs/*", "parent")?
        );
        let mut query = crate::runtime::Query::default();
        query.push("page_size", &request.page_size);
        query.push("page_token", &request.page_token);
        query.push("filter", &request.filter);
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Every page of [`Self::list`], collected.
    pub async fn list_all(
        &self,
        mut request: ListAssetsRequest,
    ) -> Result<Vec<Asset>, crate::runtime::Error> {
        let mut items = Vec::new();
        loop {
            let page = self.list(request.clone()).await?;
            items.extend(page.assets);
            if page.next_page_token.is_empty() {
                return Ok(items);
            }
            request.page_token = page.next_page_token;
        }
    }

    /// Exports every servable variant in the environment as one flat, paged
    /// manifest, independent of the keys the code declares. Rejected and retired
    /// variants are left out unless `filter` asks for their `review_state`. The
    /// last page carries a digest a client checks to know it holds the whole set.
    ///
    /// `GET /v1/{parent=orgs/*/projects/*/envs/*}/assets:export` · permission `assets:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
    pub async fn export(
        &self,
        request: ExportAssetsRequest,
    ) -> Result<ExportAssetsResponse, crate::runtime::Error> {
        let path = format!(
            "/v1/{}/assets:export",
            crate::runtime::path_param(&request.parent, "orgs/*/projects/*/envs/*", "parent")?
        );
        let mut query = crate::runtime::Query::default();
        query.push("page_size", &request.page_size);
        query.push("page_token", &request.page_token);
        query.push("filter", &request.filter);
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Records the recipes as assets and generates the variants that are
    /// missing. Each call is idempotent and works within a bounded time; call
    /// again until `pending` is 0.
    ///
    /// `POST /v1/{parent=orgs/*/projects/*/envs/*}/assets:generate` · permission `assets:write` · effect `write`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_FIELD`, `RATE_LIMITED`, `SPEND_LIMIT_REACHED`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
    pub async fn generate(
        &self,
        request: GenerateAssetsRequest,
    ) -> Result<GenerateAssetsResponse, crate::runtime::Error> {
        let path = format!(
            "/v1/{}/assets:generate",
            crate::runtime::path_param(&request.parent, "orgs/*/projects/*/envs/*", "parent")?
        );
        let query = crate::runtime::Query::default();
        let http = crate::runtime::HttpRequest {
            method: "POST",
            path,
            query: query.0,
            body: Some(crate::runtime::body_without(&request, &["parent"])?),
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Returns the `assets.lock` entries and canonical text for the keys the call
    /// names, and only those. A read with a request body, like a query.
    ///
    /// `POST /v1/{parent=orgs/*/projects/*/envs/*}/assets:lock` · permission `assets:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`.
    pub async fn lock(
        &self,
        request: LockAssetsRequest,
    ) -> Result<LockAssetsResponse, crate::runtime::Error> {
        let path = format!(
            "/v1/{}/assets:lock",
            crate::runtime::path_param(&request.parent, "orgs/*/projects/*/envs/*", "parent")?
        );
        let query = crate::runtime::Query::default();
        let http = crate::runtime::HttpRequest {
            method: "POST",
            path,
            query: query.0,
            body: Some(crate::runtime::body_without(&request, &["parent"])?),
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Approves one variant and records who approved it.
    ///
    /// `POST /v1/{name=orgs/*/projects/*/envs/*/assets/*}:approveVariant` · permission `assets:write` · effect `write`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_FIELD`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
    pub async fn approve_variant(
        &self,
        request: ApproveVariantRequest,
    ) -> Result<Asset, crate::runtime::Error> {
        let path = format!(
            "/v1/{}:approveVariant",
            crate::runtime::path_param(&request.name, "orgs/*/projects/*/envs/*/assets/*", "name")?
        );
        let query = crate::runtime::Query::default();
        let http = crate::runtime::HttpRequest {
            method: "POST",
            path,
            query: query.0,
            body: Some(crate::runtime::body_without(&request, &["name"])?),
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Rejects one variant. Its slot is freed and the next `:generate` fills it;
    /// the rejected file keeps serving at its URL.
    ///
    /// `POST /v1/{name=orgs/*/projects/*/envs/*/assets/*}:rejectVariant` · permission `assets:write` · effect `write`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_FIELD`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
    pub async fn reject_variant(
        &self,
        request: RejectVariantRequest,
    ) -> Result<Asset, crate::runtime::Error> {
        let path = format!(
            "/v1/{}:rejectVariant",
            crate::runtime::path_param(&request.name, "orgs/*/projects/*/envs/*/assets/*", "name")?
        );
        let query = crate::runtime::Query::default();
        let http = crate::runtime::HttpRequest {
            method: "POST",
            path,
            query: query.0,
            body: Some(crate::runtime::body_without(&request, &["name"])?),
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Retires one variant. Its URL answers 404 from then on and its slot is
    /// freed.
    ///
    /// `POST /v1/{name=orgs/*/projects/*/envs/*/assets/*}:retireVariant` · permission `assets:write` · effect `destructive`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_FIELD`, `INVALID_STATE`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
    pub async fn retire_variant(
        &self,
        request: RetireVariantRequest,
    ) -> Result<Asset, crate::runtime::Error> {
        let path = format!(
            "/v1/{}:retireVariant",
            crate::runtime::path_param(&request.name, "orgs/*/projects/*/envs/*/assets/*", "name")?
        );
        let query = crate::runtime::Query::default();
        let http = crate::runtime::HttpRequest {
            method: "POST",
            path,
            query: query.0,
            body: Some(crate::runtime::body_without(&request, &["name"])?),
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }
}
