// @generated by sylphx-gen 0.1.0 from contracts@0fa762a86d779ab04e332e131e530c4049a971ca72bbf98a7f286cc97dcbff80. Do not edit.
//! `sylphx.build.v1`.

#![allow(clippy::all)]

/// An Build turns one commit into an image, an SBOM, and signed
/// provenance. An Build is immutable once created; it ends with Artifact
/// digests or a typed failure.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct Build {
    /// `orgs/{org}/projects/{project}/builds/{build}`.
    ///
    /// Field behavior: `identifier`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// `bld_<cell><ulid>`; never reused.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub uid: String,
    /// Resource metadata.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<crate::common::ResourceMeta>,
    /// Desired state.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub spec: Option<BuildSpec>,
    /// Observed state.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<BuildStatus>,
}

/// A BuildCache is a per-project layer cache. It makes builds faster and never
/// changes their result; a missing or unreachable cache only slows a build.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct BuildCache {
    /// `orgs/{org}/projects/{project}/build_caches/{build_cache}`.
    ///
    /// Field behavior: `identifier`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// `bch_<cell><ulid>`; never reused.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub uid: String,
    /// Resource metadata.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<crate::common::ResourceMeta>,
    /// Desired state.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub spec: Option<BuildCacheSpec>,
    /// Observed state.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<BuildCacheStatus>,
}

/// BuildCacheSpec is the caller-writable state of a BuildCache.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct BuildCacheSpec {
    /// Entries unused this long are evicted; default 7 days.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub retention: String,
}

/// BuildCacheStatus is the observed state of a BuildCache.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct BuildCacheStatus {
    /// The generation this status was computed from.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        with = "crate::runtime::int64",
        alias = "observedGeneration"
    )]
    pub observed_generation: i64,
    /// Ready, Reconciling, Stalled.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub conditions: Vec<crate::common::Condition>,
    /// Bytes stored.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        with = "crate::runtime::int64",
        alias = "sizeBytes"
    )]
    pub size_bytes: i64,
    /// When a build last read the cache.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "lastUseTime"
    )]
    pub last_use_time: String,
}

/// BuildOutput is what a successful Build wrote to Kernel Artifacts, by
/// digest.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct BuildOutput {
    /// The image reference: `registry.sylphx.net/<path>@sha256:<hex>`.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub image: String,
    /// The image manifest digest.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "imageDigest"
    )]
    pub image_digest: String,
    /// The SBOM Artifact digest.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "sbomDigest"
    )]
    pub sbom_digest: String,
    /// The signed SLSA provenance Artifact digest.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "provenanceDigest"
    )]
    pub provenance_digest: String,
    /// The Kernel Artifact holding the three.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub artifact: String,
}

/// BuildSource is the exact source a Build reads, fetched at `commit`
/// through a Broker-minted token narrowed to the repository; never from a
/// webhook payload.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct BuildSource {
    /// The Hosting SourceLink naming the repository and its Connection.
    ///
    /// Field behavior: `required`, `immutable`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "sourceLink"
    )]
    pub source_link: String,
    /// The full commit SHA to build.
    ///
    /// Field behavior: `required`, `immutable`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub commit: String,
    /// The directory inside the repository to build; default the root.
    ///
    /// Field behavior: `immutable`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "rootDirectory"
    )]
    pub root_directory: String,
}

/// BuildSpec is the caller-writable state of a Build.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct BuildSpec {
    /// The exact source.
    ///
    /// Field behavior: `required`, `immutable`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<BuildSource>,
    /// A Dockerfile path relative to the root directory; unset lets the zero-
    /// config frontend detect the stack.
    ///
    /// Field behavior: `immutable`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub dockerfile: String,
    /// The Dockerfile stage to build.
    ///
    /// Field behavior: `immutable`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub target: String,
    /// The class, `sylphx-<os>-<size>`; default `sylphx-linux-standard`.
    ///
    /// Field behavior: `immutable`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "buildClass"
    )]
    pub build_class: String,
    /// Build arguments. Secret values bind through Kernel Secrets, never here.
    ///
    /// Field behavior: `immutable`.
    #[serde(
        default,
        skip_serializing_if = "std::collections::BTreeMap::is_empty",
        alias = "buildArgs"
    )]
    pub build_args: std::collections::BTreeMap<String, String>,
    /// The BuildCache to read and write; default the project's `default` cache.
    ///
    /// Field behavior: `immutable`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub cache: String,
}

/// BuildStatus is the observed state of a Build.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct BuildStatus {
    /// The generation this status was computed from.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        with = "crate::runtime::int64",
        alias = "observedGeneration"
    )]
    pub observed_generation: i64,
    /// Ready, Reconciling, Stalled.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub conditions: Vec<crate::common::Condition>,
    /// The lifecycle state.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<BuildState>,
    /// Why the build failed, when `state` is FAILED.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure: Option<BuildFailure>,
    /// The result, when `state` is SUCCEEDED.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output: Option<BuildOutput>,
    /// The Sandboxes lease the build ran on.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub lease: String,
    /// When the build started running.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "startTime"
    )]
    pub start_time: String,
    /// When the build reached a final state.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "endTime"
    )]
    pub end_time: String,
    /// Where the build log is read, through Observability.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "logUri"
    )]
    pub log_uri: String,
}

/// The request of CancelBuild.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct CancelBuildRequest {
    /// The name of the build.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// Act only if the current etag matches.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub etag: String,
    /// Validate without acting.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "validateOnly"
    )]
    pub validate_only: bool,
}

/// The request of CreateBuild.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct CreateBuildRequest {
    /// The parent to create in.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub parent: String,
    /// The build to create; only spec and caller-writable metadata are
    /// read.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub build: Option<Build>,
    /// The id segment of the name; the server assigns one when unset.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "buildId"
    )]
    pub build_id: String,
    /// Validate and return the result without writing anything.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "validateOnly"
    )]
    pub validate_only: bool,
}

/// The request of DeleteBuildCache.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct DeleteBuildCacheRequest {
    /// The name of the build cache to delete.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// Delete only if the current etag matches.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub etag: String,
    /// Succeed when the Resource does not exist.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "allowMissing"
    )]
    pub allow_missing: bool,
    /// Validate without deleting anything.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "validateOnly"
    )]
    pub validate_only: bool,
}

/// The request of GetBuildCache.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct GetBuildCacheRequest {
    /// The name of the build cache to get.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
}

/// The request of GetBuild.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct GetBuildRequest {
    /// The name of the build to get.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
}

/// The request of ListBuildCaches.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ListBuildCachesRequest {
    /// The parent to list in.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub parent: String,
    /// At most this many; default 50, clamped to 1000.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageSize"
    )]
    pub page_size: i32,
    /// `next_page_token` of the previous page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageToken"
    )]
    pub page_token: String,
    /// AIP-160 filter over labels, filterable fields, and Ready.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub filter: String,
    /// AIP-132 ordering over filterable fields.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "orderBy"
    )]
    pub order_by: String,
}

/// The response of ListBuildCaches.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ListBuildCachesResponse {
    /// The page.
    #[serde(default, skip_serializing_if = "Vec::is_empty", alias = "buildCaches")]
    pub build_caches: Vec<BuildCache>,
    /// The token of the next page; empty on the last page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "nextPageToken"
    )]
    pub next_page_token: String,
}

/// The request of ListBuilds.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ListBuildsRequest {
    /// The parent to list in.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub parent: String,
    /// At most this many; default 50, clamped to 1000.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageSize"
    )]
    pub page_size: i32,
    /// `next_page_token` of the previous page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageToken"
    )]
    pub page_token: String,
    /// AIP-160 filter over labels, filterable fields, and Ready.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub filter: String,
    /// AIP-132 ordering over filterable fields.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "orderBy"
    )]
    pub order_by: String,
}

/// The response of ListBuilds.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ListBuildsResponse {
    /// The page.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub builds: Vec<Build>,
    /// The token of the next page; empty on the last page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "nextPageToken"
    )]
    pub next_page_token: String,
}

/// The request of UpdateBuildCache.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct UpdateBuildCacheRequest {
    /// The build cache to update; `name` identifies it.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "buildCache")]
    pub build_cache: Option<BuildCache>,
    /// The fields to write; unset writes every populated field.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "updateMask"
    )]
    pub update_mask: String,
    /// Create the Resource when it does not exist (declarative upsert).
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "allowMissing"
    )]
    pub allow_missing: bool,
    /// Validate and return the result without writing anything.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "validateOnly"
    )]
    pub validate_only: bool,
}

/// BuildFailure is the typed reason a Build ended without a result.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum BuildFailure {
    /// The commit could not be read through the Connection.
    SourceUnavailable,
    /// The build itself failed; see the log.
    BuildError,
    /// Sandboxes had no capacity for the build class.
    NoCapacity,
    /// The build class is not sold, for example a macOS class before Apple
    /// hardware exists.
    ClassNotOffered,
    /// Provenance could not be signed; nothing unsigned is published.
    SigningUnavailable,
    /// The build exceeded its time limit.
    Timeout,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl BuildFailure {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::SourceUnavailable => "source_unavailable",
            Self::BuildError => "build_error",
            Self::NoCapacity => "no_capacity",
            Self::ClassNotOffered => "class_not_offered",
            Self::SigningUnavailable => "signing_unavailable",
            Self::Timeout => "timeout",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "source_unavailable" => Self::SourceUnavailable,
            "build_error" => Self::BuildError,
            "no_capacity" => Self::NoCapacity,
            "class_not_offered" => Self::ClassNotOffered,
            "signing_unavailable" => Self::SigningUnavailable,
            "timeout" => Self::Timeout,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for BuildFailure {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for BuildFailure {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for BuildFailure {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

/// BuildState is the lifecycle of a Build.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum BuildState {
    /// Waiting for a Sandboxes lease.
    Queued,
    /// Building on its lease.
    Running,
    /// Signed and written to Artifacts; `output` is set.
    Succeeded,
    /// Ended with a typed failure; nothing was published.
    Failed,
    /// Cancelled by a caller; nothing was published.
    Cancelled,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl BuildState {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Queued => "queued",
            Self::Running => "running",
            Self::Succeeded => "succeeded",
            Self::Failed => "failed",
            Self::Cancelled => "cancelled",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "queued" => Self::Queued,
            "running" => Self::Running,
            "succeeded" => Self::Succeeded,
            "failed" => Self::Failed,
            "cancelled" => Self::Cancelled,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for BuildState {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for BuildState {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for BuildState {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

impl<T: crate::runtime::Transport> crate::runtime::Client<T> {
    /// Sylphx Build (`preview`).
    pub fn build(&self) -> BuildApi<'_, T> {
        BuildApi { client: self }
    }
}

/// BuildService is Sylphx Build: given a repository and a commit, an image with
/// an SBOM and signed SLSA provenance, all written to Kernel Artifacts by
/// digest (docs/services/build/vision.md).
///
/// Namespace of Sylphx Build on the client.
pub struct BuildApi<'a, T> {
    client: &'a crate::runtime::Client<T>,
}

impl<'a, T: crate::runtime::Transport> BuildApi<'a, T> {
    /// The `builds` collection.
    pub fn builds(&self) -> BuildsCollection<'a, T> {
        BuildsCollection {
            client: self.client,
        }
    }

    /// The `build_caches` collection.
    pub fn build_caches(&self) -> BuildCachesCollection<'a, T> {
        BuildCachesCollection {
            client: self.client,
        }
    }
}

/// `builds` of Sylphx Build: Resource type `build.sylphx.com/Build`.
pub struct BuildsCollection<'a, T> {
    client: &'a crate::runtime::Client<T>,
}

impl<'a, T: crate::runtime::Transport> BuildsCollection<'a, T> {
    /// Gets a build.
    ///
    /// `GET /v1/{name=orgs/*/projects/*/builds/*}` · permission `build:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
    pub async fn get(&self, request: GetBuildRequest) -> Result<Build, crate::runtime::Error> {
        let path = format!(
            "/v1/{}",
            crate::runtime::path_param(&request.name, "orgs/*/projects/*/builds/*", "name")?
        );
        let query = crate::runtime::Query::default();
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Lists builds in a project.
    ///
    /// `GET /v1/{parent=orgs/*/projects/*}/builds` · permission `build:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
    pub async fn list(
        &self,
        request: ListBuildsRequest,
    ) -> Result<ListBuildsResponse, crate::runtime::Error> {
        let path = format!(
            "/v1/{}/builds",
            crate::runtime::path_param(&request.parent, "orgs/*/projects/*", "parent")?
        );
        let mut query = crate::runtime::Query::default();
        query.push("page_size", &request.page_size);
        query.push("page_token", &request.page_token);
        query.push("filter", &request.filter);
        query.push("order_by", &request.order_by);
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Every page of [`Self::list`], collected.
    pub async fn list_all(
        &self,
        mut request: ListBuildsRequest,
    ) -> Result<Vec<Build>, crate::runtime::Error> {
        let mut items = Vec::new();
        loop {
            let page = self.list(request.clone()).await?;
            items.extend(page.builds);
            if page.next_page_token.is_empty() {
                return Ok(items);
            }
            request.page_token = page.next_page_token;
        }
    }

    /// Creates a build. The Operation is done when the controller settles
    /// it.
    ///
    /// `POST /v1/{parent=orgs/*/projects/*}/builds` · permission `build:write` · effect `write`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `RESOURCE_ALREADY_EXISTS`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`, `PLAN_LIMIT_REACHED`, `SPEND_LIMIT_REACHED`.
    pub async fn create(
        &self,
        request: CreateBuildRequest,
    ) -> Result<crate::runtime::Operation<'a, T, Build>, crate::runtime::Error> {
        let path = format!(
            "/v1/{}/builds",
            crate::runtime::path_param(&request.parent, "orgs/*/projects/*", "parent")?
        );
        let mut query = crate::runtime::Query::default();
        query.push("build_id", &request.build_id);
        query.push("validate_only", &request.validate_only);
        let http = crate::runtime::HttpRequest {
            method: "POST",
            path,
            query: query.0,
            body: Some(crate::runtime::body(&request.build)?),
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        let operation = self.client.call(http).await?;
        Ok(crate::runtime::Operation::new(self.client, operation))
    }

    /// Cancels a queued or running Build; its lease is released and nothing
    /// is published.
    ///
    /// `POST /v1/{name=orgs/*/projects/*/builds/*}:cancel` · permission `build:write` · effect `destructive`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `ETAG_MISMATCH`, `INVALID_STATE`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
    pub async fn cancel(
        &self,
        request: CancelBuildRequest,
    ) -> Result<crate::runtime::Operation<'a, T, Build>, crate::runtime::Error> {
        let path = format!(
            "/v1/{}:cancel",
            crate::runtime::path_param(&request.name, "orgs/*/projects/*/builds/*", "name")?
        );
        let query = crate::runtime::Query::default();
        let http = crate::runtime::HttpRequest {
            method: "POST",
            path,
            query: query.0,
            body: Some(crate::runtime::body_without(&request, &["name"])?),
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        let operation = self.client.call(http).await?;
        Ok(crate::runtime::Operation::new(self.client, operation))
    }
}

/// `build_caches` of Sylphx Build: Resource type `build.sylphx.com/BuildCache`.
pub struct BuildCachesCollection<'a, T> {
    client: &'a crate::runtime::Client<T>,
}

impl<'a, T: crate::runtime::Transport> BuildCachesCollection<'a, T> {
    /// Gets a build cache.
    ///
    /// `GET /v1/{name=orgs/*/projects/*/build_caches/*}` · permission `build:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
    pub async fn get(
        &self,
        request: GetBuildCacheRequest,
    ) -> Result<BuildCache, crate::runtime::Error> {
        let path = format!(
            "/v1/{}",
            crate::runtime::path_param(&request.name, "orgs/*/projects/*/build_caches/*", "name")?
        );
        let query = crate::runtime::Query::default();
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Lists build caches in a project.
    ///
    /// `GET /v1/{parent=orgs/*/projects/*}/build_caches` · permission `build:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
    pub async fn list(
        &self,
        request: ListBuildCachesRequest,
    ) -> Result<ListBuildCachesResponse, crate::runtime::Error> {
        let path = format!(
            "/v1/{}/build_caches",
            crate::runtime::path_param(&request.parent, "orgs/*/projects/*", "parent")?
        );
        let mut query = crate::runtime::Query::default();
        query.push("page_size", &request.page_size);
        query.push("page_token", &request.page_token);
        query.push("filter", &request.filter);
        query.push("order_by", &request.order_by);
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Every page of [`Self::list`], collected.
    pub async fn list_all(
        &self,
        mut request: ListBuildCachesRequest,
    ) -> Result<Vec<BuildCache>, crate::runtime::Error> {
        let mut items = Vec::new();
        loop {
            let page = self.list(request.clone()).await?;
            items.extend(page.build_caches);
            if page.next_page_token.is_empty() {
                return Ok(items);
            }
            request.page_token = page.next_page_token;
        }
    }

    /// Updates a build cache.
    ///
    /// `PATCH /v1/{build_cache.name=orgs/*/projects/*/build_caches/*}` · permission `build:write` · effect `write`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
    pub async fn update(
        &self,
        request: UpdateBuildCacheRequest,
    ) -> Result<BuildCache, crate::runtime::Error> {
        let path = format!(
            "/v1/{}",
            crate::runtime::path_param(
                request
                    .build_cache
                    .as_ref()
                    .map(|v| v.name.as_str())
                    .unwrap_or(""),
                "orgs/*/projects/*/build_caches/*",
                "build_cache.name"
            )?
        );
        let mut query = crate::runtime::Query::default();
        query.push("update_mask", &request.update_mask);
        query.push("allow_missing", &request.allow_missing);
        query.push("validate_only", &request.validate_only);
        let http = crate::runtime::HttpRequest {
            method: "PATCH",
            path,
            query: query.0,
            body: Some(crate::runtime::body(&request.build_cache)?),
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Deletes a build cache.
    ///
    /// `DELETE /v1/{name=orgs/*/projects/*/build_caches/*}` · permission `build:write` · effect `destructive`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `ETAG_MISMATCH`, `INVALID_STATE`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
    pub async fn delete(
        &self,
        request: DeleteBuildCacheRequest,
    ) -> Result<crate::runtime::Empty, crate::runtime::Error> {
        let path = format!(
            "/v1/{}",
            crate::runtime::path_param(&request.name, "orgs/*/projects/*/build_caches/*", "name")?
        );
        let mut query = crate::runtime::Query::default();
        query.push("etag", &request.etag);
        query.push("allow_missing", &request.allow_missing);
        query.push("validate_only", &request.validate_only);
        let http = crate::runtime::HttpRequest {
            method: "DELETE",
            path,
            query: query.0,
            body: None,
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }
}
