// @generated by sylphx-gen 0.1.0 from contracts@cbff780dd8580c9f8238c376d04cecbc13590e46010ba4e06b53c7338af6eb5b. Do not edit.
//! The Sylphx Rust SDK: one API, one key, one namespace per service.
//!
//! ```no_run
//! # async fn run() -> Result<(), sylphx::Error> {
//! let sx = sylphx::Client::from_env()?; // SYLPHX_API_KEY
//! let me = sx.access().whoami(Default::default()).await?;
//! println!("{} in {}", me.principal, me.org);
//! # Ok(()) }
//! ```
//!
//! Generated from the Sylphx schema registry (`contracts/`) by `sylphx-gen`;
//! the wire is <https://api.sylphx.com/v1/openapi.json>.

pub mod access;
pub mod ai;
pub mod artifacts;
pub mod auth;
pub mod billing;
pub mod broker;
pub mod build;
pub mod common;
pub mod config;
pub mod connections;
pub mod data;
pub mod entitlement;
pub mod events;
pub mod hosting;
pub mod keys;
pub mod methods;
pub mod network;
pub mod notify;
pub mod observability;
pub mod release;
pub mod runners;
pub mod runtime;
pub mod sandboxes;
pub mod secrets;
pub mod workflows;

pub use runtime::{Client, Error, HttpRequest, HttpResponse, MethodSpec, Operation, Transport};
#[cfg(feature = "http")]
pub use runtime::{HttpTransport, HttpTransportBuilder};
