// @generated by sylphx-gen 0.1.0 from contracts@5aa346fb9fe13a3fff715aae36440d5312208be7155c3a09b6f5def05fa0ae2f. Do not edit.
//! `sylphx.localization.v1`.

#![allow(clippy::all)]

/// A Catalog is a string catalog: one source locale, its target locales, and
/// how to translate them. Its entries are written by `:sync`; `:export` returns
/// the files per locale.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct Catalog {
    /// `orgs/{org}/projects/{project}/envs/{env}/catalogs/{catalog}`.
    ///
    /// Field behavior: `identifier`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// `cat_<cell><ulid>`; never reused.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub uid: String,
    /// Resource metadata.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<crate::common::ResourceMeta>,
    /// Desired state.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub spec: Option<CatalogSpec>,
    /// Observed state.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<CatalogStatus>,
}

/// A Catalog Entry is one source message and its translations. `:sync` writes
/// it; it is never created directly. Its id is a stable hash of the file and
/// key, assigned by the server.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct CatalogEntry {
    /// `orgs/{org}/projects/{project}/envs/{env}/catalogs/{catalog}/entries/{entry}`.
    ///
    /// Field behavior: `identifier`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// `ent_<cell><ulid>`; never reused.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub uid: String,
    /// Resource metadata.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<crate::common::ResourceMeta>,
    /// The source text plus an optional `|context`, or an id for id-keyed
    /// formats.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub key: String,
    /// The source file's path within the upload; empty for a single-file
    /// catalog.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub file: String,
    /// The source message, a Unicode MessageFormat 2 pattern.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "sourceText"
    )]
    pub source_text: String,
    /// Disambiguates the same text with different meanings.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub context: String,
    /// A note for translators.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub description: String,
    /// The longest a translation may be, in characters; 0 is no limit.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "maxLength"
    )]
    pub max_length: i32,
    /// The first 16 lowercase hex characters of the SHA-256 of the UTF-8 source
    /// pattern. A translation is stale when its source hash differs.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "sourceHash"
    )]
    pub source_hash: String,
    /// Whether the source still has this message.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<EntryState>,
    /// The translations, one per target locale at most.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub translations: Vec<Translation>,
    /// When the entry was first synced.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "createTime"
    )]
    pub create_time: String,
    /// When the entry last changed.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "updateTime"
    )]
    pub update_time: String,
}

/// A CatalogFile is one file of a catalog.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct CatalogFile {
    /// The file's path. The service does not interpret it and echoes it back, for
    /// example a namespace file name.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub path: String,
    /// The file's locale, a BCP 47 tag.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub locale: String,
    /// The file's text, UTF-8; at most 4 MiB.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub content: String,
}

/// CatalogSpec is the caller-writable state of a Catalog.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct CatalogSpec {
    /// The locale the source texts are written in, a BCP 47 tag such as `en`.
    ///
    /// Field behavior: `required`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "sourceLocale"
    )]
    pub source_locale: String,
    /// The locales to translate into, BCP 47 tags. `zh-Hant-HK` and `zh-Hant-TW`
    /// are separate locales. At most 60, each once.
    #[serde(
        default,
        skip_serializing_if = "Vec::is_empty",
        alias = "targetLocales"
    )]
    pub target_locales: Vec<String>,
    /// Pseudo-locales to generate at export. They are never stored or
    /// translated.
    #[serde(
        default,
        skip_serializing_if = "Vec::is_empty",
        alias = "pseudoLocales"
    )]
    pub pseudo_locales: Vec<PseudoLocale>,
    /// The brand voice every translation follows, at most 2000 characters.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub tone: String,
    /// Extra instructions per target locale, for example the vocabulary of a
    /// region. Keys are target locales; at most 60 entries, each at most 2000
    /// characters.
    #[serde(
        default,
        skip_serializing_if = "std::collections::BTreeMap::is_empty",
        alias = "localeGuidance"
    )]
    pub locale_guidance: std::collections::BTreeMap<String, String>,
    /// The glossaries this catalog applies, as Glossary names; at most 10.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub glossaries: Vec<String>,
}

/// CatalogStatus is the observed state of a Catalog.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct CatalogStatus {
    /// The generation this status was computed from.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        with = "crate::runtime::int64",
        alias = "observedGeneration"
    )]
    pub observed_generation: i64,
    /// Ready, Reconciling, Stalled.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub conditions: Vec<crate::common::Condition>,
    /// The number of active entries.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "entryCount"
    )]
    pub entry_count: i32,
    /// Progress per target locale.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub locales: Vec<LocaleProgress>,
    /// When `:sync` last completed.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "lastSyncTime"
    )]
    pub last_sync_time: String,
}

/// The request of CreateCatalog.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct CreateCatalogRequest {
    /// The parent to create in.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub parent: String,
    /// The catalog id, the final name segment; the server assigns one when
    /// empty.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "catalogId"
    )]
    pub catalog_id: String,
    /// The catalog to create; only caller-writable fields are read.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub catalog: Option<Catalog>,
    /// Validate and return the result without writing anything.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "validateOnly"
    )]
    pub validate_only: bool,
}

/// The request of CreateGlossary.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct CreateGlossaryRequest {
    /// The parent to create in.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub parent: String,
    /// The glossary id, the final name segment; the server assigns one when
    /// empty.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "glossaryId"
    )]
    pub glossary_id: String,
    /// The glossary to create; only caller-writable fields are read.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub glossary: Option<Glossary>,
    /// Validate and return the result without writing anything.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "validateOnly"
    )]
    pub validate_only: bool,
}

/// The request of DeleteCatalog.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct DeleteCatalogRequest {
    /// The name of the catalog to delete.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// Delete only if the current etag matches.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub etag: String,
    /// Succeed when the catalog does not exist.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "allowMissing"
    )]
    pub allow_missing: bool,
    /// Validate without deleting anything.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "validateOnly"
    )]
    pub validate_only: bool,
    /// Also delete the catalog's entries; without it, a catalog that has entries
    /// is refused with `INVALID_STATE`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub force: bool,
}

/// The request of DeleteGlossary.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct DeleteGlossaryRequest {
    /// The name of the glossary to delete.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// Delete only if the current etag matches.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub etag: String,
    /// Succeed when the glossary does not exist.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "allowMissing"
    )]
    pub allow_missing: bool,
    /// Validate without deleting anything.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "validateOnly"
    )]
    pub validate_only: bool,
}

/// The request of ExportCatalog.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ExportCatalogRequest {
    /// The name of the catalog.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// The format of the files.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub format: Option<Format>,
    /// The locales to export; default every target locale and the pseudo-locales.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub locales: Vec<String>,
    /// Emit the source text for keys that have no passing translation, for
    /// runtimes that do not fall back to the source themselves.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "sourceFallback"
    )]
    pub source_fallback: bool,
}

/// The response of ExportCatalog.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ExportCatalogResponse {
    /// One file per source file per locale, with the source file's `path`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub files: Vec<CatalogFile>,
    /// The QA report. A translation with an error is never exported.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub report: Option<QaReport>,
    /// Translations still to make.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub pending: i32,
    /// The characters each locale's texts use.
    #[serde(default, skip_serializing_if = "Vec::is_empty", alias = "glyphSets")]
    pub glyph_sets: Vec<GlyphSet>,
}

/// The request of GetCatalogEntry.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct GetCatalogEntryRequest {
    /// The name of the catalog entry to get.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
}

/// The request of GetCatalog.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct GetCatalogRequest {
    /// The name of the catalog to get.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
}

/// The request of GetGlossary.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct GetGlossaryRequest {
    /// The name of the glossary to get.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
}

/// A Glossary is the terms shared by the catalogs that name it, one per brand
/// or product family.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct Glossary {
    /// `orgs/{org}/projects/{project}/envs/{env}/glossaries/{glossary}`.
    ///
    /// Field behavior: `identifier`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// `gls_<cell><ulid>`; never reused.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub uid: String,
    /// Resource metadata.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<crate::common::ResourceMeta>,
    /// Desired state.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub spec: Option<GlossarySpec>,
    /// Observed state.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<GlossaryStatus>,
}

/// GlossarySpec is the caller-writable state of a Glossary.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct GlossarySpec {
    /// The terms; at most 5000.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub terms: Vec<GlossaryTerm>,
}

/// GlossaryStatus is the observed state of a Glossary.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct GlossaryStatus {
    /// The generation this status was computed from.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        with = "crate::runtime::int64",
        alias = "observedGeneration"
    )]
    pub observed_generation: i64,
    /// Ready, Reconciling, Stalled.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub conditions: Vec<crate::common::Condition>,
    /// The number of terms.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "termCount"
    )]
    pub term_count: i32,
}

/// A GlossaryTerm is one term and the rule for it.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct GlossaryTerm {
    /// The term, as written in the source.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub term: String,
    /// A note for translators, at most 500 characters.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub description: String,
    /// What to do with the term.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rule: Option<TermRule>,
    /// Locale to the required translation; used by `TERM_RULE_TRANSLATE`.
    #[serde(default, skip_serializing_if = "std::collections::BTreeMap::is_empty")]
    pub translations: std::collections::BTreeMap<String, String>,
    /// Suggested wording; used by `TERM_RULE_FORBIDDEN`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub replacement: String,
    /// The locales the term applies to; empty is every locale.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub locales: Vec<String>,
    /// Match the term's letter case exactly.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "caseSensitive"
    )]
    pub case_sensitive: bool,
}

/// A GlyphSet is the characters one locale uses, for font atlases.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct GlyphSet {
    /// The locale.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub locale: String,
    /// Every distinct character the locale's texts use, sorted.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub characters: String,
}

/// The request of ListCatalogEntries.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ListCatalogEntriesRequest {
    /// The catalog to list in.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub parent: String,
    /// At most this many; default 50, clamped to 1000.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageSize"
    )]
    pub page_size: i32,
    /// `next_page_token` of the previous page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageToken"
    )]
    pub page_token: String,
    /// AIP-160 filter, limited to `state`, `locale`, and `qa_state`; for example
    /// `state = ENTRY_STATE_ACTIVE AND locale = "ja" AND qa_state = QA_STATE_FAILED`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub filter: String,
}

/// The response of ListCatalogEntries.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ListCatalogEntriesResponse {
    /// The page.
    #[serde(
        default,
        skip_serializing_if = "Vec::is_empty",
        alias = "catalogEntries"
    )]
    pub catalog_entries: Vec<CatalogEntry>,
    /// The token of the next page; empty on the last page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "nextPageToken"
    )]
    pub next_page_token: String,
}

/// The request of ListCatalogs.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ListCatalogsRequest {
    /// The parent to list in.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub parent: String,
    /// At most this many; default 50, clamped to 1000.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageSize"
    )]
    pub page_size: i32,
    /// `next_page_token` of the previous page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageToken"
    )]
    pub page_token: String,
    /// AIP-160 filter over labels and filterable fields.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub filter: String,
    /// AIP-132 ordering over filterable fields.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "orderBy"
    )]
    pub order_by: String,
}

/// The response of ListCatalogs.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ListCatalogsResponse {
    /// The page.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub catalogs: Vec<Catalog>,
    /// The token of the next page; empty on the last page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "nextPageToken"
    )]
    pub next_page_token: String,
}

/// The request of ListGlossaries.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ListGlossariesRequest {
    /// The parent to list in.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub parent: String,
    /// At most this many; default 50, clamped to 1000.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageSize"
    )]
    pub page_size: i32,
    /// `next_page_token` of the previous page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageToken"
    )]
    pub page_token: String,
    /// AIP-160 filter over labels and filterable fields.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub filter: String,
    /// AIP-132 ordering over filterable fields.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "orderBy"
    )]
    pub order_by: String,
}

/// The response of ListGlossaries.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ListGlossariesResponse {
    /// The page.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub glossaries: Vec<Glossary>,
    /// The token of the next page; empty on the last page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "nextPageToken"
    )]
    pub next_page_token: String,
}

/// LocaleProgress counts the active entries of one target locale by state.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct LocaleProgress {
    /// The target locale.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub locale: String,
    /// Entries with a translation that passed QA.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub translated: i32,
    /// Entries still to translate.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub pending: i32,
    /// Entries whose translation still fails QA after repair.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub failed: i32,
    /// Entries with a human-pinned translation.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub pinned: i32,
}

/// The request of PinTranslation.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct PinTranslationRequest {
    /// The name of the catalog entry.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// The target locale.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub locale: String,
    /// The translated message, a Unicode MessageFormat 2 pattern.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub text: String,
}

/// A QaFinding is one problem QA found in a translation.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct QaFinding {
    /// The Catalog Entry, as a resource name.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub entry: String,
    /// The entry's key.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub key: String,
    /// The target locale.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub locale: String,
    /// The check that found it.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub check: Option<QaCheck>,
    /// How serious it is.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub severity: Option<QaSeverity>,
    /// What is wrong.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub message: String,
}

/// A QaReport is the QA result of an export.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct QaReport {
    /// Whether there are no errors.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub passed: bool,
    /// The number of errors.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub errors: i32,
    /// The number of warnings.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub warnings: i32,
    /// The findings.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub findings: Vec<QaFinding>,
}

/// The request of SyncCatalog.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct SyncCatalogRequest {
    /// The name of the catalog.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// The format of the files.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub format: Option<Format>,
    /// The source-locale files; 1 to 500.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub sources: Vec<CatalogFile>,
    /// The committed target-locale files; at most 10000. A text that differs from
    /// the service's last export is recorded as a pinned human override.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub translations: Vec<CatalogFile>,
    /// Validate the files and return the counts without writing or translating.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "validateOnly"
    )]
    pub validate_only: bool,
}

/// The response of SyncCatalog.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct SyncCatalogResponse {
    /// The catalog after this call.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub catalog: Option<Catalog>,
    /// Entries new in the source.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub added: i32,
    /// Entries whose source changed.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub changed: i32,
    /// Entries no longer in the source.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub obsoleted: i32,
    /// Existing translations taken from the committed files.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub adopted: i32,
    /// Committed edits recorded as human overrides.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub pinned: i32,
    /// Translations made by this call.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub translated: i32,
    /// Translations still to make; call again until it is 0.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub pending: i32,
    /// Translations still failing QA after repair.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub failed: i32,
    /// What this call used.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage: Option<Usage>,
}

/// A Translation is the text of one entry in one target locale.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct Translation {
    /// The target locale.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub locale: String,
    /// The translated message, a Unicode MessageFormat 2 pattern.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub text: String,
    /// Where the text came from.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub origin: Option<TranslationOrigin>,
    /// A human override that AI never overwrites.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub pinned: bool,
    /// The source changed since this text was made.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub stale: bool,
    /// The result of QA on the text.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "qaState")]
    pub qa_state: Option<QaState>,
    /// What QA found.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub findings: Vec<QaFinding>,
    /// When the text last changed.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "updateTime"
    )]
    pub update_time: String,
}

/// The request of UnpinTranslation.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct UnpinTranslationRequest {
    /// The name of the catalog entry.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// The target locale.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub locale: String,
}

/// The request of UpdateCatalog.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct UpdateCatalogRequest {
    /// The catalog to update; `name` identifies it.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub catalog: Option<Catalog>,
    /// The fields to write; unset writes every populated field.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "updateMask"
    )]
    pub update_mask: String,
    /// Create the catalog when it does not exist (declarative upsert).
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "allowMissing"
    )]
    pub allow_missing: bool,
    /// Validate and return the result without writing anything.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "validateOnly"
    )]
    pub validate_only: bool,
}

/// The request of UpdateGlossary.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct UpdateGlossaryRequest {
    /// The glossary to update; `name` identifies it.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub glossary: Option<Glossary>,
    /// The fields to write; unset writes every populated field.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "updateMask"
    )]
    pub update_mask: String,
    /// Create the glossary when it does not exist (declarative upsert).
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "allowMissing"
    )]
    pub allow_missing: bool,
    /// Validate and return the result without writing anything.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "validateOnly"
    )]
    pub validate_only: bool,
}

/// Usage is what one call consumed.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct Usage {
    /// Source characters translated by this call, per target locale; the billed
    /// quantity.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        with = "crate::runtime::int64",
        alias = "translatedCharacters"
    )]
    pub translated_characters: i64,
    /// Translations reused from the translation memory, which are free.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "memoryMatches"
    )]
    pub memory_matches: i32,
}

/// EntryState is whether a Catalog Entry is still in the source.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum EntryState {
    /// The source has this message.
    Active,
    /// The source no longer has this message.
    Obsolete,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl EntryState {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Active => "active",
            Self::Obsolete => "obsolete",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "active" => Self::Active,
            "obsolete" => Self::Obsolete,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for EntryState {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for EntryState {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for EntryState {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

/// A file format the catalog is read from and written to. The canonical
/// catalog is `FORMAT_SYLPHX_JSON`; every other format is an adapter, never a
/// second store.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum Format {
    /// One JSON file per locale, Unicode MessageFormat 2, keyed by source text.
    SylphxJson,
    /// Nested JSON keyed by id, with ICU MessageFormat 1 values.
    IcuJson,
    /// A gettext `.po` file with ICU MessageFormat 1.
    GettextPo,
    /// XLIFF 2.0.
    Xliff2,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl Format {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::SylphxJson => "sylphx_json",
            Self::IcuJson => "icu_json",
            Self::GettextPo => "gettext_po",
            Self::Xliff2 => "xliff2",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "sylphx_json" => Self::SylphxJson,
            "icu_json" => Self::IcuJson,
            "gettext_po" => Self::GettextPo,
            "xliff2" => Self::Xliff2,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for Format {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for Format {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for Format {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

/// A pseudo-locale is a synthetic locale generated at export to test layout.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum PseudoLocale {
    /// `en-XA`: accented characters, 40% longer.
    Accented,
    /// `ar-XB`: right-to-left.
    Bidi,
    /// `zh-XW`: full-width characters.
    Wide,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl PseudoLocale {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Accented => "accented",
            Self::Bidi => "bidi",
            Self::Wide => "wide",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "accented" => Self::Accented,
            "bidi" => Self::Bidi,
            "wide" => Self::Wide,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for PseudoLocale {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for PseudoLocale {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for PseudoLocale {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

/// QaCheck is a QA check.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum QaCheck {
    /// The message does not parse as MessageFormat 2.
    Syntax,
    /// The placeholders differ from the source.
    Placeholders,
    /// The markup differs from the source.
    Markup,
    /// A plural or select misses the `*` catch-all or a category the locale
    /// needs.
    Plural,
    /// The text is over `max_length`, or its length ratio is suspicious.
    Length,
    /// A `KEEP` term was altered or a required `TRANSLATE` term was not used.
    Glossary,
    /// A `FORBIDDEN` term appears.
    ForbiddenTerm,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl QaCheck {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Syntax => "syntax",
            Self::Placeholders => "placeholders",
            Self::Markup => "markup",
            Self::Plural => "plural",
            Self::Length => "length",
            Self::Glossary => "glossary",
            Self::ForbiddenTerm => "forbidden_term",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "syntax" => Self::Syntax,
            "placeholders" => Self::Placeholders,
            "markup" => Self::Markup,
            "plural" => Self::Plural,
            "length" => Self::Length,
            "glossary" => Self::Glossary,
            "forbidden_term" => Self::ForbiddenTerm,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for QaCheck {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for QaCheck {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for QaCheck {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

/// QaSeverity is how serious a QA finding is.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum QaSeverity {
    /// The translation fails closed: it is never exported.
    Error,
    /// The translation is exported.
    Warning,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl QaSeverity {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Error => "error",
            Self::Warning => "warning",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "error" => Self::Error,
            "warning" => Self::Warning,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for QaSeverity {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for QaSeverity {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for QaSeverity {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

/// QaState is the QA result of a translation.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum QaState {
    /// No findings.
    Passed,
    /// Warnings only; the text is exported.
    Warning,
    /// At least one error; the text is never exported.
    Failed,
    /// QA has not run yet.
    Pending,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl QaState {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Passed => "passed",
            Self::Warning => "warning",
            Self::Failed => "failed",
            Self::Pending => "pending",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "passed" => Self::Passed,
            "warning" => Self::Warning,
            "failed" => Self::Failed,
            "pending" => Self::Pending,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for QaState {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for QaState {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for QaState {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

/// TermRule is what a glossary term requires.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum TermRule {
    /// Use the given translation for each locale.
    Translate,
    /// Never translate the term.
    Keep,
    /// The term must never appear in a translation.
    Forbidden,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl TermRule {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Translate => "translate",
            Self::Keep => "keep",
            Self::Forbidden => "forbidden",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "translate" => Self::Translate,
            "keep" => Self::Keep,
            "forbidden" => Self::Forbidden,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for TermRule {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for TermRule {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for TermRule {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

/// TranslationOrigin is where a translation's text came from.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum TranslationOrigin {
    /// Translated by AI.
    Ai,
    /// Reused from the translation memory.
    Memory,
    /// Written or pinned by a person.
    Human,
    /// Adopted from a committed file.
    Imported,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl TranslationOrigin {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Ai => "ai",
            Self::Memory => "memory",
            Self::Human => "human",
            Self::Imported => "imported",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "ai" => Self::Ai,
            "memory" => Self::Memory,
            "human" => Self::Human,
            "imported" => Self::Imported,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for TranslationOrigin {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for TranslationOrigin {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for TranslationOrigin {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

impl<T: crate::runtime::Transport> crate::runtime::Client<T> {
    /// Sylphx Localization (`preview`).
    pub fn localization(&self) -> LocalizationApi<'_, T> {
        LocalizationApi { client: self }
    }
}

/// LocalizationService is Sylphx Localization: translate an app's strings in CI
/// with AI, a translation memory, and a glossary. A Catalog holds the source
/// messages and their translations; `:sync` translates what is new or changed,
/// and `:export` returns the files per locale with a QA report. Translation
/// happens only in these calls, never at build or run time.
///
/// Namespace of Sylphx Localization on the client.
pub struct LocalizationApi<'a, T> {
    client: &'a crate::runtime::Client<T>,
}

impl<'a, T: crate::runtime::Transport> LocalizationApi<'a, T> {
    /// The `catalogs` collection.
    pub fn catalogs(&self) -> CatalogsCollection<'a, T> {
        CatalogsCollection {
            client: self.client,
        }
    }

    /// The `entries` collection.
    pub fn entries(&self) -> EntriesCollection<'a, T> {
        EntriesCollection {
            client: self.client,
        }
    }

    /// The `glossaries` collection.
    pub fn glossaries(&self) -> GlossariesCollection<'a, T> {
        GlossariesCollection {
            client: self.client,
        }
    }
}

/// `catalogs` of Sylphx Localization: Resource type `localization.sylphx.com/Catalog`.
pub struct CatalogsCollection<'a, T> {
    client: &'a crate::runtime::Client<T>,
}

impl<'a, T: crate::runtime::Transport> CatalogsCollection<'a, T> {
    /// Gets a catalog.
    ///
    /// `GET /v1/{name=orgs/*/projects/*/envs/*/catalogs/*}` · permission `localization:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
    pub async fn get(&self, request: GetCatalogRequest) -> Result<Catalog, crate::runtime::Error> {
        let path = format!(
            "/v1/{}",
            crate::runtime::path_param(
                &request.name,
                "orgs/*/projects/*/envs/*/catalogs/*",
                "name"
            )?
        );
        let query = crate::runtime::Query::default();
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Lists catalogs.
    ///
    /// `GET /v1/{parent=orgs/*/projects/*/envs/*}/catalogs` · permission `localization:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
    pub async fn list(
        &self,
        request: ListCatalogsRequest,
    ) -> Result<ListCatalogsResponse, crate::runtime::Error> {
        let path = format!(
            "/v1/{}/catalogs",
            crate::runtime::path_param(&request.parent, "orgs/*/projects/*/envs/*", "parent")?
        );
        let mut query = crate::runtime::Query::default();
        query.push("page_size", &request.page_size);
        query.push("page_token", &request.page_token);
        query.push("filter", &request.filter);
        query.push("order_by", &request.order_by);
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Every page of [`Self::list`], collected.
    pub async fn list_all(
        &self,
        mut request: ListCatalogsRequest,
    ) -> Result<Vec<Catalog>, crate::runtime::Error> {
        let mut items = Vec::new();
        loop {
            let page = self.list(request.clone()).await?;
            items.extend(page.catalogs);
            if page.next_page_token.is_empty() {
                return Ok(items);
            }
            request.page_token = page.next_page_token;
        }
    }

    /// Creates a catalog.
    ///
    /// `POST /v1/{parent=orgs/*/projects/*/envs/*}/catalogs` · permission `localization:write` · effect `write`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `RESOURCE_ALREADY_EXISTS`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`, `PLAN_LIMIT_REACHED`.
    pub async fn create(
        &self,
        request: CreateCatalogRequest,
    ) -> Result<Catalog, crate::runtime::Error> {
        let path = format!(
            "/v1/{}/catalogs",
            crate::runtime::path_param(&request.parent, "orgs/*/projects/*/envs/*", "parent")?
        );
        let mut query = crate::runtime::Query::default();
        query.push("catalog_id", &request.catalog_id);
        query.push("validate_only", &request.validate_only);
        let http = crate::runtime::HttpRequest {
            method: "POST",
            path,
            query: query.0,
            body: Some(crate::runtime::body(&request.catalog)?),
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Updates a catalog.
    ///
    /// `PATCH /v1/{catalog.name=orgs/*/projects/*/envs/*/catalogs/*}` · permission `localization:write` · effect `write`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
    pub async fn update(
        &self,
        request: UpdateCatalogRequest,
    ) -> Result<Catalog, crate::runtime::Error> {
        let path = format!(
            "/v1/{}",
            crate::runtime::path_param(
                request
                    .catalog
                    .as_ref()
                    .map(|v| v.name.as_str())
                    .unwrap_or(""),
                "orgs/*/projects/*/envs/*/catalogs/*",
                "catalog.name"
            )?
        );
        let mut query = crate::runtime::Query::default();
        query.push("update_mask", &request.update_mask);
        query.push("allow_missing", &request.allow_missing);
        query.push("validate_only", &request.validate_only);
        let http = crate::runtime::HttpRequest {
            method: "PATCH",
            path,
            query: query.0,
            body: Some(crate::runtime::body(&request.catalog)?),
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Deletes a catalog.
    ///
    /// `DELETE /v1/{name=orgs/*/projects/*/envs/*/catalogs/*}` · permission `localization:write` · effect `destructive`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_STATE`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
    pub async fn delete(
        &self,
        request: DeleteCatalogRequest,
    ) -> Result<crate::runtime::Empty, crate::runtime::Error> {
        let path = format!(
            "/v1/{}",
            crate::runtime::path_param(
                &request.name,
                "orgs/*/projects/*/envs/*/catalogs/*",
                "name"
            )?
        );
        let mut query = crate::runtime::Query::default();
        query.push("etag", &request.etag);
        query.push("allow_missing", &request.allow_missing);
        query.push("validate_only", &request.validate_only);
        query.push("force", &request.force);
        let http = crate::runtime::HttpRequest {
            method: "DELETE",
            path,
            query: query.0,
            body: None,
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Reads the source files and the committed translations into the catalog,
    /// then translates what is new or stale. Each call is idempotent and works
    /// within a bounded time; call again until `pending` is 0.
    ///
    /// `POST /v1/{name=orgs/*/projects/*/envs/*/catalogs/*}:sync` · permission `localization:write` · effect `write`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_FIELD`, `RATE_LIMITED`, `SPEND_LIMIT_REACHED`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
    pub async fn sync(
        &self,
        request: SyncCatalogRequest,
    ) -> Result<SyncCatalogResponse, crate::runtime::Error> {
        let path = format!(
            "/v1/{}:sync",
            crate::runtime::path_param(
                &request.name,
                "orgs/*/projects/*/envs/*/catalogs/*",
                "name"
            )?
        );
        let query = crate::runtime::Query::default();
        let http = crate::runtime::HttpRequest {
            method: "POST",
            path,
            query: query.0,
            body: Some(crate::runtime::body_without(&request, &["name"])?),
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Returns the catalog's files per locale in the requested format, with the QA
    /// report. A read with a request body, like a query.
    ///
    /// `POST /v1/{name=orgs/*/projects/*/envs/*/catalogs/*}:export` · permission `localization:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_FIELD`.
    pub async fn export(
        &self,
        request: ExportCatalogRequest,
    ) -> Result<ExportCatalogResponse, crate::runtime::Error> {
        let path = format!(
            "/v1/{}:export",
            crate::runtime::path_param(
                &request.name,
                "orgs/*/projects/*/envs/*/catalogs/*",
                "name"
            )?
        );
        let query = crate::runtime::Query::default();
        let http = crate::runtime::HttpRequest {
            method: "POST",
            path,
            query: query.0,
            body: Some(crate::runtime::body_without(&request, &["name"])?),
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }
}

/// `entries` of Sylphx Localization: Resource type `localization.sylphx.com/CatalogEntry`.
pub struct EntriesCollection<'a, T> {
    client: &'a crate::runtime::Client<T>,
}

impl<'a, T: crate::runtime::Transport> EntriesCollection<'a, T> {
    /// Gets a catalog entry.
    ///
    /// `GET /v1/{name=orgs/*/projects/*/envs/*/catalogs/*/entries/*}` · permission `localization:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
    pub async fn get(
        &self,
        request: GetCatalogEntryRequest,
    ) -> Result<CatalogEntry, crate::runtime::Error> {
        let path = format!(
            "/v1/{}",
            crate::runtime::path_param(
                &request.name,
                "orgs/*/projects/*/envs/*/catalogs/*/entries/*",
                "name"
            )?
        );
        let query = crate::runtime::Query::default();
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Lists catalog entries. The filter is limited to `state`, `locale`, and
    /// `qa_state`.
    ///
    /// `GET /v1/{parent=orgs/*/projects/*/envs/*/catalogs/*}/entries` · permission `localization:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
    pub async fn list(
        &self,
        request: ListCatalogEntriesRequest,
    ) -> Result<ListCatalogEntriesResponse, crate::runtime::Error> {
        let path = format!(
            "/v1/{}/entries",
            crate::runtime::path_param(
                &request.parent,
                "orgs/*/projects/*/envs/*/catalogs/*",
                "parent"
            )?
        );
        let mut query = crate::runtime::Query::default();
        query.push("page_size", &request.page_size);
        query.push("page_token", &request.page_token);
        query.push("filter", &request.filter);
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Every page of [`Self::list`], collected.
    pub async fn list_all(
        &self,
        mut request: ListCatalogEntriesRequest,
    ) -> Result<Vec<CatalogEntry>, crate::runtime::Error> {
        let mut items = Vec::new();
        loop {
            let page = self.list(request.clone()).await?;
            items.extend(page.catalog_entries);
            if page.next_page_token.is_empty() {
                return Ok(items);
            }
            request.page_token = page.next_page_token;
        }
    }

    /// Sets the text of one locale as a human override that AI never overwrites.
    /// QA runs on the text first; a text with a QA error is rejected with
    /// `INVALID_FIELD`, and the problem lists the findings.
    ///
    /// `POST /v1/{name=orgs/*/projects/*/envs/*/catalogs/*/entries/*}:pinTranslation` · permission `localization:write` · effect `write`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_FIELD`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
    pub async fn pin_translation(
        &self,
        request: PinTranslationRequest,
    ) -> Result<CatalogEntry, crate::runtime::Error> {
        let path = format!(
            "/v1/{}:pinTranslation",
            crate::runtime::path_param(
                &request.name,
                "orgs/*/projects/*/envs/*/catalogs/*/entries/*",
                "name"
            )?
        );
        let query = crate::runtime::Query::default();
        let http = crate::runtime::HttpRequest {
            method: "POST",
            path,
            query: query.0,
            body: Some(crate::runtime::body_without(&request, &["name"])?),
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Removes the human override of one locale; the next sync may translate it
    /// again.
    ///
    /// `POST /v1/{name=orgs/*/projects/*/envs/*/catalogs/*/entries/*}:unpinTranslation` · permission `localization:write` · effect `write`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `INVALID_FIELD`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
    pub async fn unpin_translation(
        &self,
        request: UnpinTranslationRequest,
    ) -> Result<CatalogEntry, crate::runtime::Error> {
        let path = format!(
            "/v1/{}:unpinTranslation",
            crate::runtime::path_param(
                &request.name,
                "orgs/*/projects/*/envs/*/catalogs/*/entries/*",
                "name"
            )?
        );
        let query = crate::runtime::Query::default();
        let http = crate::runtime::HttpRequest {
            method: "POST",
            path,
            query: query.0,
            body: Some(crate::runtime::body_without(&request, &["name"])?),
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }
}

/// `glossaries` of Sylphx Localization: Resource type `localization.sylphx.com/Glossary`.
pub struct GlossariesCollection<'a, T> {
    client: &'a crate::runtime::Client<T>,
}

impl<'a, T: crate::runtime::Transport> GlossariesCollection<'a, T> {
    /// Gets a glossary.
    ///
    /// `GET /v1/{name=orgs/*/projects/*/envs/*/glossaries/*}` · permission `localization:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
    pub async fn get(
        &self,
        request: GetGlossaryRequest,
    ) -> Result<Glossary, crate::runtime::Error> {
        let path = format!(
            "/v1/{}",
            crate::runtime::path_param(
                &request.name,
                "orgs/*/projects/*/envs/*/glossaries/*",
                "name"
            )?
        );
        let query = crate::runtime::Query::default();
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Lists glossarys.
    ///
    /// `GET /v1/{parent=orgs/*/projects/*/envs/*}/glossaries` · permission `localization:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
    pub async fn list(
        &self,
        request: ListGlossariesRequest,
    ) -> Result<ListGlossariesResponse, crate::runtime::Error> {
        let path = format!(
            "/v1/{}/glossaries",
            crate::runtime::path_param(&request.parent, "orgs/*/projects/*/envs/*", "parent")?
        );
        let mut query = crate::runtime::Query::default();
        query.push("page_size", &request.page_size);
        query.push("page_token", &request.page_token);
        query.push("filter", &request.filter);
        query.push("order_by", &request.order_by);
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Every page of [`Self::list`], collected.
    pub async fn list_all(
        &self,
        mut request: ListGlossariesRequest,
    ) -> Result<Vec<Glossary>, crate::runtime::Error> {
        let mut items = Vec::new();
        loop {
            let page = self.list(request.clone()).await?;
            items.extend(page.glossaries);
            if page.next_page_token.is_empty() {
                return Ok(items);
            }
            request.page_token = page.next_page_token;
        }
    }

    /// Creates a glossary.
    ///
    /// `POST /v1/{parent=orgs/*/projects/*/envs/*}/glossaries` · permission `localization:write` · effect `write`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `RESOURCE_ALREADY_EXISTS`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`, `PLAN_LIMIT_REACHED`.
    pub async fn create(
        &self,
        request: CreateGlossaryRequest,
    ) -> Result<Glossary, crate::runtime::Error> {
        let path = format!(
            "/v1/{}/glossaries",
            crate::runtime::path_param(&request.parent, "orgs/*/projects/*/envs/*", "parent")?
        );
        let mut query = crate::runtime::Query::default();
        query.push("glossary_id", &request.glossary_id);
        query.push("validate_only", &request.validate_only);
        let http = crate::runtime::HttpRequest {
            method: "POST",
            path,
            query: query.0,
            body: Some(crate::runtime::body(&request.glossary)?),
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Updates a glossary.
    ///
    /// `PATCH /v1/{glossary.name=orgs/*/projects/*/envs/*/glossaries/*}` · permission `localization:write` · effect `write`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
    pub async fn update(
        &self,
        request: UpdateGlossaryRequest,
    ) -> Result<Glossary, crate::runtime::Error> {
        let path = format!(
            "/v1/{}",
            crate::runtime::path_param(
                request
                    .glossary
                    .as_ref()
                    .map(|v| v.name.as_str())
                    .unwrap_or(""),
                "orgs/*/projects/*/envs/*/glossaries/*",
                "glossary.name"
            )?
        );
        let mut query = crate::runtime::Query::default();
        query.push("update_mask", &request.update_mask);
        query.push("allow_missing", &request.allow_missing);
        query.push("validate_only", &request.validate_only);
        let http = crate::runtime::HttpRequest {
            method: "PATCH",
            path,
            query: query.0,
            body: Some(crate::runtime::body(&request.glossary)?),
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Deletes a glossary.
    ///
    /// `DELETE /v1/{name=orgs/*/projects/*/envs/*/glossaries/*}` · permission `localization:write` · effect `destructive`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
    pub async fn delete(
        &self,
        request: DeleteGlossaryRequest,
    ) -> Result<crate::runtime::Empty, crate::runtime::Error> {
        let path = format!(
            "/v1/{}",
            crate::runtime::path_param(
                &request.name,
                "orgs/*/projects/*/envs/*/glossaries/*",
                "name"
            )?
        );
        let mut query = crate::runtime::Query::default();
        query.push("etag", &request.etag);
        query.push("allow_missing", &request.allow_missing);
        query.push("validate_only", &request.validate_only);
        let http = crate::runtime::HttpRequest {
            method: "DELETE",
            path,
            query: query.0,
            body: None,
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }
}
