// @generated by sylphx-gen 0.1.0 from contracts@190f1b33b937c1aef79697684018db853389b521c75e19ff69ac6af609e96f45. Do not edit.
//! `sylphx.release.v1`.

#![allow(clippy::all)]

/// The request of CreateRelease.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct CreateReleaseRequest {
    /// The environment to create in.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub parent: String,
    /// The release to create; only spec and caller-writable metadata are read.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub release: Option<Release>,
    /// The id of the new release, `^[a-z]([a-z0-9_-]{0,61}[a-z0-9])?$`; the server assigns one when
    /// empty.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "releaseId"
    )]
    pub release_id: String,
    /// Validate and return the result without writing anything.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "validateOnly"
    )]
    pub validate_only: bool,
}

/// The request of GetRelease.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct GetReleaseRequest {
    /// The name of the release to get.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
}

/// The request of GetRollout.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct GetRolloutRequest {
    /// The name of the rollout to get.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
}

/// The request of ListReleases.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ListReleasesRequest {
    /// The environment to list in.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub parent: String,
    /// At most this many; default 50, clamped to 1000.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageSize"
    )]
    pub page_size: i32,
    /// `next_page_token` of the previous page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageToken"
    )]
    pub page_token: String,
    /// AIP-160 filter over labels and filterable fields.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub filter: String,
    /// AIP-132 ordering over filterable fields.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "orderBy"
    )]
    pub order_by: String,
}

/// The response of ListReleases.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ListReleasesResponse {
    /// The page.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub releases: Vec<Release>,
    /// The token of the next page; empty on the last page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "nextPageToken"
    )]
    pub next_page_token: String,
}

/// The request of ListRollouts.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ListRolloutsRequest {
    /// The environment to list in.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub parent: String,
    /// At most this many; default 50, clamped to 1000.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageSize"
    )]
    pub page_size: i32,
    /// `next_page_token` of the previous page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageToken"
    )]
    pub page_token: String,
    /// AIP-160 filter over labels and filterable fields.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub filter: String,
    /// AIP-132 ordering over filterable fields.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "orderBy"
    )]
    pub order_by: String,
}

/// The response of ListRollouts.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ListRolloutsResponse {
    /// The page.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub rollouts: Vec<Rollout>,
    /// The token of the next page; empty on the last page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "nextPageToken"
    )]
    pub next_page_token: String,
}

/// Placement is attribute matching against the Cell registry: a workload is
/// placed on a Ready Cell that has every attribute, or refused.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct Placement {
    /// Regions allowed, for example `fsn1`; empty means any.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub regions: Vec<String>,
    /// Specific cells, for example `fs01`; empty means any matching cell.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub cells: Vec<String>,
    /// Required cell attributes, for example `{"substrate": "metal"}`.
    #[serde(default, skip_serializing_if = "std::collections::BTreeMap::is_empty")]
    pub attributes: std::collections::BTreeMap<String, String>,
    /// Replicas per cell; default 1.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub replicas: i32,
}

/// A Release is an immutable desired state of an environment's workloads.
/// Writing a newer Release supersedes the live one; a rollback is a new
/// Release naming older digests.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct Release {
    /// `orgs/{org}/projects/{project}/envs/{env}/releases/{release}`.
    ///
    /// Field behavior: `identifier`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// `rel_<cell><ulid>`.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub uid: String,
    /// Resource metadata.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<crate::common::ResourceMeta>,
    /// Desired state.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub spec: Option<ReleaseSpec>,
    /// Observed state.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<ReleaseStatus>,
}

/// ReleaseMember is one workload of a Release.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ReleaseMember {
    /// The workload's name in the environment, for example `api`: the owning
    /// service's Resource id (a Hosting service, a Workflows worker, ...).
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub workload: String,
    /// The Artifact to run, by digest.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub artifact: String,
    /// Plain configuration values delivered as environment variables. Never a
    /// secret value: those are Secret bindings.
    #[serde(default, skip_serializing_if = "std::collections::BTreeMap::is_empty")]
    pub config: std::collections::BTreeMap<String, String>,
    /// The Secret bindings the workload receives, each pinned to a version.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub secrets: Vec<SecretPin>,
    /// Where the workload runs.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub placement: Option<Placement>,
}

/// ReleaseMemberStatus is one member's convergence.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ReleaseMemberStatus {
    /// The workload.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub workload: String,
    /// The digest the cells report running.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "observedDigest"
    )]
    pub observed_digest: String,
    /// How many cells run the member at this Release.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "convergedCellCount"
    )]
    pub converged_cell_count: i32,
    /// How many cells the member is placed on.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "cellCount"
    )]
    pub cell_count: i32,
}

/// ReleaseSpec is the caller-writable state of a Release; it never changes
/// after Create.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ReleaseSpec {
    /// The workloads, each by artifact digest. A member that names a tag or an
    /// unverified Artifact is refused.
    ///
    /// Field behavior: `required`, `immutable`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub members: Vec<ReleaseMember>,
    /// How the Release rolls out.
    ///
    /// Field behavior: `immutable`.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "rolloutPolicy"
    )]
    pub rollout_policy: Option<RolloutPolicy>,
}

/// ReleaseStatus is the observed state of a Release, derived from Cell
/// Status.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ReleaseStatus {
    /// The generation this status was computed from.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        with = "crate::runtime::int64",
        alias = "observedGeneration"
    )]
    pub observed_generation: i64,
    /// Ready, Reconciling, Stalled.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub conditions: Vec<crate::common::Condition>,
    /// The Release's lifecycle state.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<ReleaseState>,
    /// The rollout carrying this Release.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub rollout: String,
    /// The Release that was live when this one was admitted.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "previousRelease"
    )]
    pub previous_release: String,
    /// The Release that replaced this one.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub successor: String,
    /// Per-member convergence.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "Vec::is_empty",
        alias = "memberStatuses"
    )]
    pub member_statuses: Vec<ReleaseMemberStatus>,
    /// When every cell first served the Release.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "liveTime"
    )]
    pub live_time: String,
}

/// A Rollout is the progress of one Release through its waves, derived from
/// the cell status the Release controller reports.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct Rollout {
    /// `orgs/{org}/projects/{project}/envs/{env}/rollouts/{rollout}`.
    ///
    /// Field behavior: `identifier`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// `rol_<cell><ulid>`.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub uid: String,
    /// Resource metadata.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<crate::common::ResourceMeta>,
    /// The Release rolling out.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub release: String,
    /// The rollout's lifecycle state.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<RolloutState>,
    /// The waves, in order.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub waves: Vec<Wave>,
    /// The index of the wave in progress, from 0.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "currentWave"
    )]
    pub current_wave: i32,
    /// When the first wave started.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "startTime"
    )]
    pub start_time: String,
    /// When the rollout finished.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "endTime"
    )]
    pub end_time: String,
    /// A customer-safe reason the rollout halted.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "haltReason"
    )]
    pub halt_reason: String,
}

/// RolloutPolicy is how a Release moves through waves.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct RolloutPolicy {
    /// How long each wave bakes, healthy, before the next starts; default
    /// 10 minutes.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "bakeDuration"
    )]
    pub bake_duration: String,
    /// Halt the rollout when a wave's health gate fails; default true.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "haltOnFailure"
    )]
    pub halt_on_failure: Option<bool>,
    /// Skip the waves and apply to every cell together: break-glass only, and
    /// refused for any other principal.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "skipWaves"
    )]
    pub skip_waves: bool,
}

/// SecretPin pins a Secret binding to one version for a Release.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct SecretPin {
    /// The binding.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub binding: String,
    /// The version it delivers; unset pins the binding's resolved version at
    /// admission.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub version: String,
}

/// Wave is one step of a rollout.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct Wave {
    /// What the wave covers.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scope: Option<WaveScope>,
    /// The cells in the wave.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub cells: Vec<String>,
    /// The wave's lifecycle state.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<RolloutState>,
    /// How many of the wave's cells report the Release converged and healthy.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "healthyCellCount"
    )]
    pub healthy_cell_count: i32,
    /// When the wave started.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "startTime"
    )]
    pub start_time: String,
    /// When the wave passed its health gate or failed.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "endTime"
    )]
    pub end_time: String,
}

/// ReleaseState is the lifecycle state of a Release.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum ReleaseState {
    /// Admitted, waiting for its rollout to start.
    Pending,
    /// Rolling out.
    RollingOut,
    /// Served by every placed Cell.
    Live,
    /// Halted by a failed health gate.
    Failed,
    /// Replaced by a newer Release.
    Superseded,
    /// Refused at admission, for example for an unverified digest.
    Rejected,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl ReleaseState {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Pending => "pending",
            Self::RollingOut => "rolling_out",
            Self::Live => "live",
            Self::Failed => "failed",
            Self::Superseded => "superseded",
            Self::Rejected => "rejected",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "pending" => Self::Pending,
            "rolling_out" => Self::RollingOut,
            "live" => Self::Live,
            "failed" => Self::Failed,
            "superseded" => Self::Superseded,
            "rejected" => Self::Rejected,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for ReleaseState {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for ReleaseState {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for ReleaseState {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

/// RolloutState is the lifecycle state of a Rollout or one of its waves.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum RolloutState {
    /// Not started.
    Waiting,
    /// Applying or baking.
    InProgress,
    /// Every wave passed its health gate.
    Succeeded,
    /// A health gate failed; the rollout halted.
    Failed,
    /// A newer Release superseded it before it finished.
    Superseded,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl RolloutState {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Waiting => "waiting",
            Self::InProgress => "in_progress",
            Self::Succeeded => "succeeded",
            Self::Failed => "failed",
            Self::Superseded => "superseded",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "waiting" => Self::Waiting,
            "in_progress" => Self::InProgress,
            "succeeded" => Self::Succeeded,
            "failed" => Self::Failed,
            "superseded" => Self::Superseded,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for RolloutState {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for RolloutState {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for RolloutState {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

/// WaveScope is what one wave of a rollout covers.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum WaveScope {
    /// One canary Cell.
    Canary,
    /// One more Cell.
    Cell,
    /// One region.
    Region,
    /// Every remaining Cell.
    All,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl WaveScope {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Canary => "canary",
            Self::Cell => "cell",
            Self::Region => "region",
            Self::All => "all",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "canary" => Self::Canary,
            "cell" => Self::Cell,
            "region" => Self::Region,
            "all" => Self::All,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for WaveScope {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for WaveScope {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for WaveScope {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

impl<T: crate::runtime::Transport> crate::runtime::Client<T> {
    /// Sylphx Release (`preview`).
    pub fn release(&self) -> ReleaseApi<'_, T> {
        ReleaseApi { client: self }
    }
}

/// ReleaseService is Sylphx Release: the only deployable unit and the progress
/// of its rollouts. Releases are immutable; there is no Update or Delete.
///
/// Namespace of Sylphx Release on the client.
pub struct ReleaseApi<'a, T> {
    client: &'a crate::runtime::Client<T>,
}

impl<'a, T: crate::runtime::Transport> ReleaseApi<'a, T> {
    /// The `releases` collection.
    pub fn releases(&self) -> ReleasesCollection<'a, T> {
        ReleasesCollection {
            client: self.client,
        }
    }

    /// The `rollouts` collection.
    pub fn rollouts(&self) -> RolloutsCollection<'a, T> {
        RolloutsCollection {
            client: self.client,
        }
    }
}

/// `releases` of Sylphx Release: Resource type `release.sylphx.com/Release`.
pub struct ReleasesCollection<'a, T> {
    client: &'a crate::runtime::Client<T>,
}

impl<'a, T: crate::runtime::Transport> ReleasesCollection<'a, T> {
    /// Gets a release.
    ///
    /// `GET /v1/{name=orgs/*/projects/*/envs/*/releases/*}` · permission `release:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
    pub async fn get(&self, request: GetReleaseRequest) -> Result<Release, crate::runtime::Error> {
        let path = format!(
            "/v1/{}",
            crate::runtime::path_param(
                &request.name,
                "orgs/*/projects/*/envs/*/releases/*",
                "name"
            )?
        );
        let query = crate::runtime::Query::default();
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Lists releases in an environment, newest first by default.
    ///
    /// `GET /v1/{parent=orgs/*/projects/*/envs/*}/releases` · permission `release:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
    pub async fn list(
        &self,
        request: ListReleasesRequest,
    ) -> Result<ListReleasesResponse, crate::runtime::Error> {
        let path = format!(
            "/v1/{}/releases",
            crate::runtime::path_param(&request.parent, "orgs/*/projects/*/envs/*", "parent")?
        );
        let mut query = crate::runtime::Query::default();
        query.push("page_size", &request.page_size);
        query.push("page_token", &request.page_token);
        query.push("filter", &request.filter);
        query.push("order_by", &request.order_by);
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Every page of [`Self::list`], collected.
    pub async fn list_all(
        &self,
        mut request: ListReleasesRequest,
    ) -> Result<Vec<Release>, crate::runtime::Error> {
        let mut items = Vec::new();
        loop {
            let page = self.list(request.clone()).await?;
            items.extend(page.releases);
            if page.next_page_token.is_empty() {
                return Ok(items);
            }
            request.page_token = page.next_page_token;
        }
    }

    /// Creates a release: admits it and rolls it out in waves. The Operation is done when the release is live or halted.
    ///
    /// `POST /v1/{parent=orgs/*/projects/*/envs/*}/releases` · permission `release:write` · effect `write`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `RESOURCE_ALREADY_EXISTS`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`, `PLAN_LIMIT_REACHED`, `INVALID_STATE`.
    pub async fn create(
        &self,
        request: CreateReleaseRequest,
    ) -> Result<crate::runtime::Operation<'a, T, Release>, crate::runtime::Error> {
        let path = format!(
            "/v1/{}/releases",
            crate::runtime::path_param(&request.parent, "orgs/*/projects/*/envs/*", "parent")?
        );
        let mut query = crate::runtime::Query::default();
        query.push("release_id", &request.release_id);
        query.push("validate_only", &request.validate_only);
        let http = crate::runtime::HttpRequest {
            method: "POST",
            path,
            query: query.0,
            body: Some(crate::runtime::body(&request.release)?),
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        let operation = self.client.call(http).await?;
        Ok(crate::runtime::Operation::new(self.client, operation))
    }
}

/// `rollouts` of Sylphx Release: Resource type `release.sylphx.com/Rollout`.
pub struct RolloutsCollection<'a, T> {
    client: &'a crate::runtime::Client<T>,
}

impl<'a, T: crate::runtime::Transport> RolloutsCollection<'a, T> {
    /// Gets a rollout.
    ///
    /// `GET /v1/{name=orgs/*/projects/*/envs/*/rollouts/*}` · permission `release:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
    pub async fn get(&self, request: GetRolloutRequest) -> Result<Rollout, crate::runtime::Error> {
        let path = format!(
            "/v1/{}",
            crate::runtime::path_param(
                &request.name,
                "orgs/*/projects/*/envs/*/rollouts/*",
                "name"
            )?
        );
        let query = crate::runtime::Query::default();
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Lists rollouts in an environment.
    ///
    /// `GET /v1/{parent=orgs/*/projects/*/envs/*}/rollouts` · permission `release:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
    pub async fn list(
        &self,
        request: ListRolloutsRequest,
    ) -> Result<ListRolloutsResponse, crate::runtime::Error> {
        let path = format!(
            "/v1/{}/rollouts",
            crate::runtime::path_param(&request.parent, "orgs/*/projects/*/envs/*", "parent")?
        );
        let mut query = crate::runtime::Query::default();
        query.push("page_size", &request.page_size);
        query.push("page_token", &request.page_token);
        query.push("filter", &request.filter);
        query.push("order_by", &request.order_by);
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Every page of [`Self::list`], collected.
    pub async fn list_all(
        &self,
        mut request: ListRolloutsRequest,
    ) -> Result<Vec<Rollout>, crate::runtime::Error> {
        let mut items = Vec::new();
        loop {
            let page = self.list(request.clone()).await?;
            items.extend(page.rollouts);
            if page.next_page_token.is_empty() {
                return Ok(items);
            }
            request.page_token = page.next_page_token;
        }
    }
}
