// @generated by sylphx-gen 0.1.0 from contracts@5a34e8ad528d553a34388c40f9e0974abb2c71eaa0990538da340de8cf767f89. Do not edit.
//! `sylphx.runners.v1`.

#![allow(clippy::all)]

/// The request of CreateScaleSet.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct CreateScaleSetRequest {
    /// The parent to create in.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub parent: String,
    /// The scale set to create; only spec and caller-writable metadata are read.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "scaleSet")]
    pub scale_set: Option<ScaleSet>,
    /// The id segment of the name; the server assigns one when unset.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "scaleSetId"
    )]
    pub scale_set_id: String,
    /// Validate and return the result without writing anything.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "validateOnly"
    )]
    pub validate_only: bool,
}

/// The request of DeleteScaleSet.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct DeleteScaleSetRequest {
    /// The name of the scale set to delete.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// Delete only if the current etag matches.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub etag: String,
    /// Succeed when the Resource does not exist.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "allowMissing"
    )]
    pub allow_missing: bool,
    /// Validate without deleting anything.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "validateOnly"
    )]
    pub validate_only: bool,
    /// Also delete every child Resource; without it a parent with children fails
    /// with FAILED_PRECONDITION.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub force: bool,
}

/// The request of GetRunner.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct GetRunnerRequest {
    /// The name of the runner to get.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
}

/// The request of GetScaleSet.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct GetScaleSetRequest {
    /// The name of the scale set to get.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
}

/// The request of ListRunners.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ListRunnersRequest {
    /// The parent to list in.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub parent: String,
    /// At most this many; default 50, clamped to 1000.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageSize"
    )]
    pub page_size: i32,
    /// `next_page_token` of the previous page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageToken"
    )]
    pub page_token: String,
    /// AIP-160 filter over labels, filterable fields, and Ready.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub filter: String,
    /// AIP-132 ordering over filterable fields.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "orderBy"
    )]
    pub order_by: String,
}

/// The response of ListRunners.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ListRunnersResponse {
    /// The page.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub runners: Vec<Runner>,
    /// The token of the next page; empty on the last page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "nextPageToken"
    )]
    pub next_page_token: String,
}

/// The request of ListScaleSets.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ListScaleSetsRequest {
    /// The parent to list in.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub parent: String,
    /// At most this many; default 50, clamped to 1000.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageSize"
    )]
    pub page_size: i32,
    /// `next_page_token` of the previous page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "pageToken"
    )]
    pub page_token: String,
    /// AIP-160 filter over labels, filterable fields, and Ready.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub filter: String,
    /// AIP-132 ordering over filterable fields.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "orderBy"
    )]
    pub order_by: String,
}

/// The response of ListScaleSets.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ListScaleSetsResponse {
    /// The page.
    #[serde(default, skip_serializing_if = "Vec::is_empty", alias = "scaleSets")]
    pub scale_sets: Vec<ScaleSet>,
    /// The token of the next page; empty on the last page.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "nextPageToken"
    )]
    pub next_page_token: String,
}

/// A Runner is one runner: one machine for exactly one job, on its own
/// Sandboxes lease, released and wiped after. Runners is its only writer;
/// callers read it.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct Runner {
    /// `orgs/{org}/scale_sets/{scale_set}/runners/{runner}`.
    ///
    /// Field behavior: `identifier`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// `rnr_<cell><ulid>`; never reused.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub uid: String,
    /// Resource metadata.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<crate::common::ResourceMeta>,
    /// The lifecycle state.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<RunnerState>,
    /// Why it never ran a job, when `state` is FAILED.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure: Option<RunnerFailure>,
    /// The class it runs as.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "runnerClass"
    )]
    pub runner_class: String,
    /// Its Sandboxes lease.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub lease: String,
    /// The repository of its job, `<owner>/<name>`.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub repository: String,
    /// The job on the forge.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "jobUri"
    )]
    pub job_uri: String,
    /// When its job started.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "startTime"
    )]
    pub start_time: String,
    /// When its job ended.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "endTime"
    )]
    pub end_time: String,
}

/// A ScaleSet registers one runner class on one Sylphx Runners installation.
/// Runners holds its message session with one fenced holder, and GitHub matches
/// jobs to its runners; Runners keeps no global queue.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ScaleSet {
    /// `orgs/{org}/scale_sets/{scale_set}`.
    ///
    /// Field behavior: `identifier`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub name: String,
    /// `rss_<cell><ulid>`; never reused.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub uid: String,
    /// Resource metadata.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<crate::common::ResourceMeta>,
    /// Desired state.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub spec: Option<ScaleSetSpec>,
    /// Observed state.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<ScaleSetStatus>,
}

/// ScaleSetSpec is the caller-writable state of a ScaleSet.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ScaleSetSpec {
    /// The Sylphx Runners installation Connection.
    ///
    /// Field behavior: `required`, `immutable`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub connection: String,
    /// The class, `sylphx-<os>-<size>`, for example `sylphx-linux-standard`. It
    /// is the label workflows ask for.
    ///
    /// Field behavior: `required`, `immutable`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "runnerClass"
    )]
    pub runner_class: String,
    /// The forge runner group to register in; default the installation's default
    /// group.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "runnerGroup"
    )]
    pub runner_group: String,
    /// Concurrent runners at most; 0 means the plan's limit.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "maxRunners"
    )]
    pub max_runners: i32,
}

/// ScaleSetStatus is the observed state of a ScaleSet.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct ScaleSetStatus {
    /// The generation this status was computed from.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        with = "crate::runtime::int64",
        alias = "observedGeneration"
    )]
    pub observed_generation: i64,
    /// Ready, Reconciling, Stalled.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub conditions: Vec<crate::common::Condition>,
    /// The forge's id of the registered scale set.
    ///
    /// Field behavior: `output_only`.
    #[serde(default, skip_serializing_if = "crate::runtime::is_default")]
    pub registration: String,
    /// The region whose holder owns the message session.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "sessionRegion"
    )]
    pub session_region: String,
    /// Runners running a job.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "busyRunners"
    )]
    pub busy_runners: i32,
    /// Runners waiting for a job.
    ///
    /// Field behavior: `output_only`.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "idleRunners"
    )]
    pub idle_runners: i32,
}

/// The request of UpdateScaleSet.
#[derive(Debug, Clone, Default, PartialEq, serde::Serialize, serde::Deserialize)]
#[non_exhaustive]
pub struct UpdateScaleSetRequest {
    /// The scale set to update; `name` identifies it.
    ///
    /// Field behavior: `required`.
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "scaleSet")]
    pub scale_set: Option<ScaleSet>,
    /// The fields to write; unset writes every populated field.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "updateMask"
    )]
    pub update_mask: String,
    /// Create the Resource when it does not exist (declarative upsert).
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "allowMissing"
    )]
    pub allow_missing: bool,
    /// Validate and return the result without writing anything.
    #[serde(
        default,
        skip_serializing_if = "crate::runtime::is_default",
        alias = "validateOnly"
    )]
    pub validate_only: bool,
}

/// RunnerFailure is why a runner never ran its job. The job keeps waiting at
/// the forge.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum RunnerFailure {
    /// Sandboxes had no capacity for the class.
    NoCapacity,
    /// The class is not sold, for example `sylphx-macos-*` before Apple hardware
    /// exists.
    ClassNotOffered,
    /// The installation lacks a permission the runner needs; the remedy is on the
    /// ScaleSet's conditions.
    CapabilityMissing,
    /// The machine did not boot the runner image.
    BootFailed,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl RunnerFailure {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::NoCapacity => "no_capacity",
            Self::ClassNotOffered => "class_not_offered",
            Self::CapabilityMissing => "capability_missing",
            Self::BootFailed => "boot_failed",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "no_capacity" => Self::NoCapacity,
            "class_not_offered" => Self::ClassNotOffered,
            "capability_missing" => Self::CapabilityMissing,
            "boot_failed" => Self::BootFailed,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for RunnerFailure {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for RunnerFailure {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for RunnerFailure {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

/// RunnerState is the lifecycle of one runner.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum RunnerState {
    /// Its Sandboxes lease is being granted.
    Provisioning,
    /// Registered and waiting for its one job.
    Idle,
    /// Running its job.
    Busy,
    /// Its job ended; the lease is released and wiped.
    Finished,
    /// It never ran a job; see `failure`.
    Failed,
    /// A value this SDK version does not know.
    Unknown(String),
}

impl RunnerState {
    /// The wire string.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Provisioning => "provisioning",
            Self::Idle => "idle",
            Self::Busy => "busy",
            Self::Finished => "finished",
            Self::Failed => "failed",
            Self::Unknown(s) => s.as_str(),
        }
    }

    /// Parses a wire string; unknown values are kept.
    pub fn from_wire(s: &str) -> Self {
        match s {
            "provisioning" => Self::Provisioning,
            "idle" => Self::Idle,
            "busy" => Self::Busy,
            "finished" => Self::Finished,
            "failed" => Self::Failed,
            other => Self::Unknown(other.to_string()),
        }
    }
}

impl serde::Serialize for RunnerState {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_str())
    }
}

impl<'de> serde::Deserialize<'de> for RunnerState {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(Self::from_wire(&s))
    }
}

impl crate::runtime::QueryValue for RunnerState {
    fn query_value(&self) -> Option<String> {
        Some(self.as_str().to_string())
    }
}

impl<T: crate::runtime::Transport> crate::runtime::Client<T> {
    /// Sylphx Runners (`preview`).
    pub fn runners(&self) -> RunnersApi<'_, T> {
        RunnersApi { client: self }
    }
}

/// RunnersService is Sylphx Runners: CI runners of a class
/// `sylphx-<os>-<size>`, one clean Sandboxes lease per job, registered as scale
/// sets on a Sylphx Runners installation (docs/services/runners/vision.md).
/// Runners are read-only: GitHub matches jobs to runners, and Runners reports
/// them.
///
/// Namespace of Sylphx Runners on the client.
pub struct RunnersApi<'a, T> {
    client: &'a crate::runtime::Client<T>,
}

impl<'a, T: crate::runtime::Transport> RunnersApi<'a, T> {
    /// The `scale_sets` collection.
    pub fn scale_sets(&self) -> ScaleSetsCollection<'a, T> {
        ScaleSetsCollection {
            client: self.client,
        }
    }

    /// The `runners` collection.
    pub fn runners(&self) -> RunnersCollection<'a, T> {
        RunnersCollection {
            client: self.client,
        }
    }
}

/// `scale_sets` of Sylphx Runners: Resource type `runners.sylphx.com/ScaleSet`.
pub struct ScaleSetsCollection<'a, T> {
    client: &'a crate::runtime::Client<T>,
}

impl<'a, T: crate::runtime::Transport> ScaleSetsCollection<'a, T> {
    /// Gets a scale set.
    ///
    /// `GET /v1/{name=orgs/*/scale_sets/*}` · permission `runners:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
    pub async fn get(
        &self,
        request: GetScaleSetRequest,
    ) -> Result<ScaleSet, crate::runtime::Error> {
        let path = format!(
            "/v1/{}",
            crate::runtime::path_param(&request.name, "orgs/*/scale_sets/*", "name")?
        );
        let query = crate::runtime::Query::default();
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Lists scale sets in a org.
    ///
    /// `GET /v1/{parent=orgs/*}/scale_sets` · permission `runners:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
    pub async fn list(
        &self,
        request: ListScaleSetsRequest,
    ) -> Result<ListScaleSetsResponse, crate::runtime::Error> {
        let path = format!(
            "/v1/{}/scale_sets",
            crate::runtime::path_param(&request.parent, "orgs/*", "parent")?
        );
        let mut query = crate::runtime::Query::default();
        query.push("page_size", &request.page_size);
        query.push("page_token", &request.page_token);
        query.push("filter", &request.filter);
        query.push("order_by", &request.order_by);
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Every page of [`Self::list`], collected.
    pub async fn list_all(
        &self,
        mut request: ListScaleSetsRequest,
    ) -> Result<Vec<ScaleSet>, crate::runtime::Error> {
        let mut items = Vec::new();
        loop {
            let page = self.list(request.clone()).await?;
            items.extend(page.scale_sets);
            if page.next_page_token.is_empty() {
                return Ok(items);
            }
            request.page_token = page.next_page_token;
        }
    }

    /// Creates a scale set. The Operation is done when the controller settles it.
    ///
    /// `POST /v1/{parent=orgs/*}/scale_sets` · permission `runners:write` · effect `write`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `RESOURCE_ALREADY_EXISTS`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`, `PLAN_LIMIT_REACHED`, `SPEND_LIMIT_REACHED`.
    pub async fn create(
        &self,
        request: CreateScaleSetRequest,
    ) -> Result<crate::runtime::Operation<'a, T, ScaleSet>, crate::runtime::Error> {
        let path = format!(
            "/v1/{}/scale_sets",
            crate::runtime::path_param(&request.parent, "orgs/*", "parent")?
        );
        let mut query = crate::runtime::Query::default();
        query.push("scale_set_id", &request.scale_set_id);
        query.push("validate_only", &request.validate_only);
        let http = crate::runtime::HttpRequest {
            method: "POST",
            path,
            query: query.0,
            body: Some(crate::runtime::body(&request.scale_set)?),
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        let operation = self.client.call(http).await?;
        Ok(crate::runtime::Operation::new(self.client, operation))
    }

    /// Updates a scale set.
    ///
    /// `PATCH /v1/{scale_set.name=orgs/*/scale_sets/*}` · permission `runners:write` · effect `write`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `UNKNOWN_FIELD`, `INVALID_FIELD`, `ETAG_MISMATCH`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
    pub async fn update(
        &self,
        request: UpdateScaleSetRequest,
    ) -> Result<crate::runtime::Operation<'a, T, ScaleSet>, crate::runtime::Error> {
        let path = format!(
            "/v1/{}",
            crate::runtime::path_param(
                request
                    .scale_set
                    .as_ref()
                    .map(|v| v.name.as_str())
                    .unwrap_or(""),
                "orgs/*/scale_sets/*",
                "scale_set.name"
            )?
        );
        let mut query = crate::runtime::Query::default();
        query.push("update_mask", &request.update_mask);
        query.push("allow_missing", &request.allow_missing);
        query.push("validate_only", &request.validate_only);
        let http = crate::runtime::HttpRequest {
            method: "PATCH",
            path,
            query: query.0,
            body: Some(crate::runtime::body(&request.scale_set)?),
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        let operation = self.client.call(http).await?;
        Ok(crate::runtime::Operation::new(self.client, operation))
    }

    /// Deletes a scale set.
    ///
    /// `DELETE /v1/{name=orgs/*/scale_sets/*}` · permission `runners:write` · effect `destructive`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`, `ETAG_MISMATCH`, `INVALID_STATE`, `IDEMPOTENCY_KEY_REUSED`, `IDEMPOTENCY_IN_PROGRESS`.
    pub async fn delete(
        &self,
        request: DeleteScaleSetRequest,
    ) -> Result<crate::runtime::Operation<'a, T, crate::runtime::Empty>, crate::runtime::Error>
    {
        let path = format!(
            "/v1/{}",
            crate::runtime::path_param(&request.name, "orgs/*/scale_sets/*", "name")?
        );
        let mut query = crate::runtime::Query::default();
        query.push("etag", &request.etag);
        query.push("allow_missing", &request.allow_missing);
        query.push("validate_only", &request.validate_only);
        query.push("force", &request.force);
        let http = crate::runtime::HttpRequest {
            method: "DELETE",
            path,
            query: query.0,
            body: None,
            mutation: true,
            origin: None,
            effect_ids: false,
        };
        let operation = self.client.call(http).await?;
        Ok(crate::runtime::Operation::new(self.client, operation))
    }
}

/// `runners` of Sylphx Runners: Resource type `runners.sylphx.com/Runner`.
pub struct RunnersCollection<'a, T> {
    client: &'a crate::runtime::Client<T>,
}

impl<'a, T: crate::runtime::Transport> RunnersCollection<'a, T> {
    /// Gets a runner.
    ///
    /// `GET /v1/{name=orgs/*/scale_sets/*/runners/*}` · permission `runners:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `RESOURCE_NOT_FOUND`.
    pub async fn get(&self, request: GetRunnerRequest) -> Result<Runner, crate::runtime::Error> {
        let path = format!(
            "/v1/{}",
            crate::runtime::path_param(&request.name, "orgs/*/scale_sets/*/runners/*", "name")?
        );
        let query = crate::runtime::Query::default();
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Lists runners in a scale set.
    ///
    /// `GET /v1/{parent=orgs/*/scale_sets/*}/runners` · permission `runners:read` · effect `read`
    ///
    /// Errors: `UNAUTHENTICATED`, `PERMISSION_DENIED`, `INVALID_FIELD`, `PAGE_TOKEN_MISMATCH`.
    pub async fn list(
        &self,
        request: ListRunnersRequest,
    ) -> Result<ListRunnersResponse, crate::runtime::Error> {
        let path = format!(
            "/v1/{}/runners",
            crate::runtime::path_param(&request.parent, "orgs/*/scale_sets/*", "parent")?
        );
        let mut query = crate::runtime::Query::default();
        query.push("page_size", &request.page_size);
        query.push("page_token", &request.page_token);
        query.push("filter", &request.filter);
        query.push("order_by", &request.order_by);
        let http = crate::runtime::HttpRequest {
            method: "GET",
            path,
            query: query.0,
            body: None,
            mutation: false,
            origin: None,
            effect_ids: false,
        };
        self.client.call(http).await
    }

    /// Every page of [`Self::list`], collected.
    pub async fn list_all(
        &self,
        mut request: ListRunnersRequest,
    ) -> Result<Vec<Runner>, crate::runtime::Error> {
        let mut items = Vec::new();
        loop {
            let page = self.list(request.clone()).await?;
            items.extend(page.runners);
            if page.next_page_token.is_empty() {
                return Ok(items);
            }
            request.page_token = page.next_page_token;
        }
    }
}
